// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cart.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCartsByEvent = `-- name: CountCartsByEvent :one
SELECT COUNT(*)::int as count FROM carts WHERE event_id = $1 AND status = 'pending'
`

func (q *Queries) CountCartsByEvent(ctx context.Context, eventID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countCartsByEvent, eventID)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const createCart = `-- name: CreateCart :one

INSERT INTO carts (event_id, session_id, platform_user_id, platform_handle, token, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, event_id, platform_user_id, platform_handle, token, status, checkout_url, payment_integration_id, external_order_id, payment_status, paid_at, notify_status, notify_error, notified_at, created_at, expires_at, session_id
`

type CreateCartParams struct {
	EventID        pgtype.UUID        `json:"event_id"`
	SessionID      pgtype.UUID        `json:"session_id"`
	PlatformUserID string             `json:"platform_user_id"`
	PlatformHandle string             `json:"platform_handle"`
	Token          string             `json:"token"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
}

// =============================================================================
// CARTS (belong to events, with optional session tracking)
// =============================================================================
func (q *Queries) CreateCart(ctx context.Context, arg CreateCartParams) (Cart, error) {
	row := q.db.QueryRow(ctx, createCart,
		arg.EventID,
		arg.SessionID,
		arg.PlatformUserID,
		arg.PlatformHandle,
		arg.Token,
		arg.ExpiresAt,
	)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.PlatformUserID,
		&i.PlatformHandle,
		&i.Token,
		&i.Status,
		&i.CheckoutUrl,
		&i.PaymentIntegrationID,
		&i.ExternalOrderID,
		&i.PaymentStatus,
		&i.PaidAt,
		&i.NotifyStatus,
		&i.NotifyError,
		&i.NotifiedAt,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.SessionID,
	)
	return i, err
}

const createCartItem = `-- name: CreateCartItem :one
INSERT INTO cart_items (cart_id, product_id, quantity, unit_price, waitlisted)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, cart_id, product_id, quantity, unit_price, waitlisted
`

type CreateCartItemParams struct {
	CartID     pgtype.UUID `json:"cart_id"`
	ProductID  pgtype.UUID `json:"product_id"`
	Quantity   pgtype.Int4 `json:"quantity"`
	UnitPrice  pgtype.Int8 `json:"unit_price"`
	Waitlisted bool        `json:"waitlisted"`
}

func (q *Queries) CreateCartItem(ctx context.Context, arg CreateCartItemParams) (CartItem, error) {
	row := q.db.QueryRow(ctx, createCartItem,
		arg.CartID,
		arg.ProductID,
		arg.Quantity,
		arg.UnitPrice,
		arg.Waitlisted,
	)
	var i CartItem
	err := row.Scan(
		&i.ID,
		&i.CartID,
		&i.ProductID,
		&i.Quantity,
		&i.UnitPrice,
		&i.Waitlisted,
	)
	return i, err
}

const deleteCartItem = `-- name: DeleteCartItem :exec
DELETE FROM cart_items WHERE id = $1
`

func (q *Queries) DeleteCartItem(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCartItem, id)
	return err
}

const deleteCartItemByCartAndProduct = `-- name: DeleteCartItemByCartAndProduct :exec
DELETE FROM cart_items WHERE cart_id = $1 AND product_id = $2
`

type DeleteCartItemByCartAndProductParams struct {
	CartID    pgtype.UUID `json:"cart_id"`
	ProductID pgtype.UUID `json:"product_id"`
}

func (q *Queries) DeleteCartItemByCartAndProduct(ctx context.Context, arg DeleteCartItemByCartAndProductParams) error {
	_, err := q.db.Exec(ctx, deleteCartItemByCartAndProduct, arg.CartID, arg.ProductID)
	return err
}

const finalizeCartsByEvent = `-- name: FinalizeCartsByEvent :exec
UPDATE carts
SET status = 'checkout'
WHERE event_id = $1 AND status = 'pending'
`

// Updates all pending carts in an event to checkout status
func (q *Queries) FinalizeCartsByEvent(ctx context.Context, eventID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, finalizeCartsByEvent, eventID)
	return err
}

const getCartByEventAndUser = `-- name: GetCartByEventAndUser :one
SELECT id, event_id, platform_user_id, platform_handle, token, status, checkout_url, payment_integration_id, external_order_id, payment_status, paid_at, notify_status, notify_error, notified_at, created_at, expires_at, session_id FROM carts WHERE event_id = $1 AND platform_user_id = $2
`

type GetCartByEventAndUserParams struct {
	EventID        pgtype.UUID `json:"event_id"`
	PlatformUserID string      `json:"platform_user_id"`
}

func (q *Queries) GetCartByEventAndUser(ctx context.Context, arg GetCartByEventAndUserParams) (Cart, error) {
	row := q.db.QueryRow(ctx, getCartByEventAndUser, arg.EventID, arg.PlatformUserID)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.PlatformUserID,
		&i.PlatformHandle,
		&i.Token,
		&i.Status,
		&i.CheckoutUrl,
		&i.PaymentIntegrationID,
		&i.ExternalOrderID,
		&i.PaymentStatus,
		&i.PaidAt,
		&i.NotifyStatus,
		&i.NotifyError,
		&i.NotifiedAt,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.SessionID,
	)
	return i, err
}

const getCartByEventAndUserForUpdate = `-- name: GetCartByEventAndUserForUpdate :one
SELECT id, event_id, platform_user_id, platform_handle, token, status, checkout_url, payment_integration_id, external_order_id, payment_status, paid_at, notify_status, notify_error, notified_at, created_at, expires_at, session_id FROM carts WHERE event_id = $1 AND platform_user_id = $2 FOR UPDATE
`

type GetCartByEventAndUserForUpdateParams struct {
	EventID        pgtype.UUID `json:"event_id"`
	PlatformUserID string      `json:"platform_user_id"`
}

// Lock the cart row for concurrent safety
func (q *Queries) GetCartByEventAndUserForUpdate(ctx context.Context, arg GetCartByEventAndUserForUpdateParams) (Cart, error) {
	row := q.db.QueryRow(ctx, getCartByEventAndUserForUpdate, arg.EventID, arg.PlatformUserID)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.PlatformUserID,
		&i.PlatformHandle,
		&i.Token,
		&i.Status,
		&i.CheckoutUrl,
		&i.PaymentIntegrationID,
		&i.ExternalOrderID,
		&i.PaymentStatus,
		&i.PaidAt,
		&i.NotifyStatus,
		&i.NotifyError,
		&i.NotifiedAt,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.SessionID,
	)
	return i, err
}

const getCartByID = `-- name: GetCartByID :one
SELECT id, event_id, platform_user_id, platform_handle, token, status, checkout_url, payment_integration_id, external_order_id, payment_status, paid_at, notify_status, notify_error, notified_at, created_at, expires_at, session_id FROM carts WHERE id = $1
`

func (q *Queries) GetCartByID(ctx context.Context, id pgtype.UUID) (Cart, error) {
	row := q.db.QueryRow(ctx, getCartByID, id)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.PlatformUserID,
		&i.PlatformHandle,
		&i.Token,
		&i.Status,
		&i.CheckoutUrl,
		&i.PaymentIntegrationID,
		&i.ExternalOrderID,
		&i.PaymentStatus,
		&i.PaidAt,
		&i.NotifyStatus,
		&i.NotifyError,
		&i.NotifiedAt,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.SessionID,
	)
	return i, err
}

const getCartByToken = `-- name: GetCartByToken :one
SELECT id, event_id, platform_user_id, platform_handle, token, status, checkout_url, payment_integration_id, external_order_id, payment_status, paid_at, notify_status, notify_error, notified_at, created_at, expires_at, session_id FROM carts WHERE token = $1
`

func (q *Queries) GetCartByToken(ctx context.Context, token string) (Cart, error) {
	row := q.db.QueryRow(ctx, getCartByToken, token)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.PlatformUserID,
		&i.PlatformHandle,
		&i.Token,
		&i.Status,
		&i.CheckoutUrl,
		&i.PaymentIntegrationID,
		&i.ExternalOrderID,
		&i.PaymentStatus,
		&i.PaidAt,
		&i.NotifyStatus,
		&i.NotifyError,
		&i.NotifiedAt,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.SessionID,
	)
	return i, err
}

const getCartItem = `-- name: GetCartItem :one
SELECT id, cart_id, product_id, quantity, unit_price, waitlisted FROM cart_items WHERE id = $1
`

func (q *Queries) GetCartItem(ctx context.Context, id pgtype.UUID) (CartItem, error) {
	row := q.db.QueryRow(ctx, getCartItem, id)
	var i CartItem
	err := row.Scan(
		&i.ID,
		&i.CartID,
		&i.ProductID,
		&i.Quantity,
		&i.UnitPrice,
		&i.Waitlisted,
	)
	return i, err
}

const getEventStats = `-- name: GetEventStats :one

SELECT
    COALESCE((SELECT SUM(ls.total_comments) FROM live_sessions ls WHERE ls.event_id = $1), 0)::int AS total_comments,
    COALESCE((SELECT COUNT(*) FROM carts ct WHERE ct.event_id = $1 AND ct.status = 'pending'), 0)::int AS open_carts,
    COALESCE((SELECT COUNT(*) FROM carts ct WHERE ct.event_id = $1 AND ct.payment_status = 'paid'), 0)::int AS paid_carts,
    COALESCE((
        SELECT SUM(ci.quantity)
        FROM carts ct
        JOIN cart_items ci ON ci.cart_id = ct.id
        WHERE ct.event_id = $1 AND ct.status != 'expired'
    ), 0)::int AS total_products_sold,
    COALESCE((
        SELECT SUM(ci.quantity * ci.unit_price)
        FROM carts ct
        JOIN cart_items ci ON ci.cart_id = ct.id
        WHERE ct.event_id = $1 AND ct.status = 'pending'
    ), 0)::bigint AS projected_revenue,
    COALESCE((
        SELECT SUM(ci.quantity * ci.unit_price)
        FROM carts ct
        JOIN cart_items ci ON ci.cart_id = ct.id
        WHERE ct.event_id = $1 AND ct.payment_status = 'paid'
    ), 0)::bigint AS confirmed_revenue
`

type GetEventStatsRow struct {
	TotalComments     int32 `json:"total_comments"`
	OpenCarts         int32 `json:"open_carts"`
	PaidCarts         int32 `json:"paid_carts"`
	TotalProductsSold int32 `json:"total_products_sold"`
	ProjectedRevenue  int64 `json:"projected_revenue"`
	ConfirmedRevenue  int64 `json:"confirmed_revenue"`
}

// =============================================================================
// EVENT DETAILS - Stats and Cart Listing
// =============================================================================
// Returns stats for an event: comments, carts, revenue, products sold
func (q *Queries) GetEventStats(ctx context.Context, eventID pgtype.UUID) (GetEventStatsRow, error) {
	row := q.db.QueryRow(ctx, getEventStats, eventID)
	var i GetEventStatsRow
	err := row.Scan(
		&i.TotalComments,
		&i.OpenCarts,
		&i.PaidCarts,
		&i.TotalProductsSold,
		&i.ProjectedRevenue,
		&i.ConfirmedRevenue,
	)
	return i, err
}

const getSessionStats = `-- name: GetSessionStats :one

SELECT
    COALESCE((SELECT COUNT(*) FROM carts ct WHERE ct.session_id = $1), 0)::int AS total_carts,
    COALESCE((SELECT COUNT(*) FROM carts ct WHERE ct.session_id = $1 AND ct.payment_status = 'paid'), 0)::int AS paid_carts,
    COALESCE((
        SELECT SUM(ci.quantity * ci.unit_price)
        FROM carts ct
        JOIN cart_items ci ON ci.cart_id = ct.id
        WHERE ct.session_id = $1 AND ct.status != 'expired'
    ), 0)::bigint AS total_revenue,
    COALESCE((
        SELECT SUM(ci.quantity * ci.unit_price)
        FROM carts ct
        JOIN cart_items ci ON ci.cart_id = ct.id
        WHERE ct.session_id = $1 AND ct.payment_status = 'paid'
    ), 0)::bigint AS paid_revenue
`

type GetSessionStatsRow struct {
	TotalCarts   int32 `json:"total_carts"`
	PaidCarts    int32 `json:"paid_carts"`
	TotalRevenue int64 `json:"total_revenue"`
	PaidRevenue  int64 `json:"paid_revenue"`
}

// =============================================================================
// SESSION DETAILS - Stats per session
// =============================================================================
// Returns stats for a specific session: carts count and revenue
func (q *Queries) GetSessionStats(ctx context.Context, sessionID pgtype.UUID) (GetSessionStatsRow, error) {
	row := q.db.QueryRow(ctx, getSessionStats, sessionID)
	var i GetSessionStatsRow
	err := row.Scan(
		&i.TotalCarts,
		&i.PaidCarts,
		&i.TotalRevenue,
		&i.PaidRevenue,
	)
	return i, err
}

const listCartItems = `-- name: ListCartItems :many
SELECT ci.id, ci.cart_id, ci.product_id, ci.quantity, ci.unit_price, ci.waitlisted, p.name AS product_name, p.image_url AS product_image_url
FROM cart_items ci
JOIN products p ON p.id = ci.product_id
WHERE ci.cart_id = $1
`

type ListCartItemsRow struct {
	ID              pgtype.UUID `json:"id"`
	CartID          pgtype.UUID `json:"cart_id"`
	ProductID       pgtype.UUID `json:"product_id"`
	Quantity        pgtype.Int4 `json:"quantity"`
	UnitPrice       pgtype.Int8 `json:"unit_price"`
	Waitlisted      bool        `json:"waitlisted"`
	ProductName     string      `json:"product_name"`
	ProductImageUrl pgtype.Text `json:"product_image_url"`
}

func (q *Queries) ListCartItems(ctx context.Context, cartID pgtype.UUID) ([]ListCartItemsRow, error) {
	rows, err := q.db.Query(ctx, listCartItems, cartID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCartItemsRow{}
	for rows.Next() {
		var i ListCartItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.CartID,
			&i.ProductID,
			&i.Quantity,
			&i.UnitPrice,
			&i.Waitlisted,
			&i.ProductName,
			&i.ProductImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCartsByEvent = `-- name: ListCartsByEvent :many
SELECT id, event_id, platform_user_id, platform_handle, token, status, checkout_url, payment_integration_id, external_order_id, payment_status, paid_at, notify_status, notify_error, notified_at, created_at, expires_at, session_id FROM carts WHERE event_id = $1 ORDER BY created_at
`

func (q *Queries) ListCartsByEvent(ctx context.Context, eventID pgtype.UUID) ([]Cart, error) {
	rows, err := q.db.Query(ctx, listCartsByEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Cart{}
	for rows.Next() {
		var i Cart
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.PlatformUserID,
			&i.PlatformHandle,
			&i.Token,
			&i.Status,
			&i.CheckoutUrl,
			&i.PaymentIntegrationID,
			&i.ExternalOrderID,
			&i.PaymentStatus,
			&i.PaidAt,
			&i.NotifyStatus,
			&i.NotifyError,
			&i.NotifiedAt,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.SessionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCartsWithTotalByEvent = `-- name: ListCartsWithTotalByEvent :many
SELECT
    c.id,
    c.event_id,
    c.platform_user_id,
    c.platform_handle,
    c.status,
    c.payment_status,
    c.created_at,
    c.expires_at,
    COALESCE(SUM(ci.quantity * ci.unit_price), 0)::bigint AS total_value,
    COALESCE(SUM(ci.quantity), 0)::int AS total_items
FROM carts c
LEFT JOIN cart_items ci ON ci.cart_id = c.id
WHERE c.event_id = $1
GROUP BY c.id
ORDER BY c.created_at DESC
`

type ListCartsWithTotalByEventRow struct {
	ID             pgtype.UUID        `json:"id"`
	EventID        pgtype.UUID        `json:"event_id"`
	PlatformUserID string             `json:"platform_user_id"`
	PlatformHandle string             `json:"platform_handle"`
	Status         string             `json:"status"`
	PaymentStatus  pgtype.Text        `json:"payment_status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	TotalValue     int64              `json:"total_value"`
	TotalItems     int32              `json:"total_items"`
}

// Returns carts for an event with total value and item count
func (q *Queries) ListCartsWithTotalByEvent(ctx context.Context, eventID pgtype.UUID) ([]ListCartsWithTotalByEventRow, error) {
	rows, err := q.db.Query(ctx, listCartsWithTotalByEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCartsWithTotalByEventRow{}
	for rows.Next() {
		var i ListCartsWithTotalByEventRow
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.PlatformUserID,
			&i.PlatformHandle,
			&i.Status,
			&i.PaymentStatus,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.TotalValue,
			&i.TotalItems,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredCarts = `-- name: ListExpiredCarts :many
SELECT c.id, c.event_id, c.platform_user_id, c.platform_handle, c.token, c.status, c.checkout_url, c.payment_integration_id, c.external_order_id, c.payment_status, c.paid_at, c.notify_status, c.notify_error, c.notified_at, c.created_at, c.expires_at, c.session_id, le.store_id
FROM carts c
JOIN live_events le ON le.id = c.event_id
WHERE c.status = 'pending' AND c.expires_at IS NOT NULL AND c.expires_at < now()
`

type ListExpiredCartsRow struct {
	ID                   pgtype.UUID        `json:"id"`
	EventID              pgtype.UUID        `json:"event_id"`
	PlatformUserID       string             `json:"platform_user_id"`
	PlatformHandle       string             `json:"platform_handle"`
	Token                string             `json:"token"`
	Status               string             `json:"status"`
	CheckoutUrl          pgtype.Text        `json:"checkout_url"`
	PaymentIntegrationID pgtype.UUID        `json:"payment_integration_id"`
	ExternalOrderID      pgtype.Text        `json:"external_order_id"`
	PaymentStatus        pgtype.Text        `json:"payment_status"`
	PaidAt               pgtype.Timestamptz `json:"paid_at"`
	NotifyStatus         pgtype.Text        `json:"notify_status"`
	NotifyError          pgtype.Text        `json:"notify_error"`
	NotifiedAt           pgtype.Timestamptz `json:"notified_at"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	ExpiresAt            pgtype.Timestamptz `json:"expires_at"`
	SessionID            pgtype.UUID        `json:"session_id"`
	StoreID              pgtype.UUID        `json:"store_id"`
}

// Returns carts that have expired (pending + past expires_at), with store_id from event
func (q *Queries) ListExpiredCarts(ctx context.Context) ([]ListExpiredCartsRow, error) {
	rows, err := q.db.Query(ctx, listExpiredCarts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExpiredCartsRow{}
	for rows.Next() {
		var i ListExpiredCartsRow
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.PlatformUserID,
			&i.PlatformHandle,
			&i.Token,
			&i.Status,
			&i.CheckoutUrl,
			&i.PaymentIntegrationID,
			&i.ExternalOrderID,
			&i.PaymentStatus,
			&i.PaidAt,
			&i.NotifyStatus,
			&i.NotifyError,
			&i.NotifiedAt,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.SessionID,
			&i.StoreID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredCartsByEventAndProduct = `-- name: ListExpiredCartsByEventAndProduct :many
SELECT DISTINCT c.id, c.event_id, c.platform_user_id, c.platform_handle, c.token, c.status, c.checkout_url, c.payment_integration_id, c.external_order_id, c.payment_status, c.paid_at, c.notify_status, c.notify_error, c.notified_at, c.created_at, c.expires_at, c.session_id, le.store_id
FROM carts c
JOIN live_events le ON le.id = c.event_id
JOIN cart_items ci ON ci.cart_id = c.id
WHERE c.event_id = $1
  AND c.status = 'pending'
  AND c.expires_at IS NOT NULL
  AND c.expires_at < now()
  AND ci.product_id = $2
  AND ci.waitlisted = false
`

type ListExpiredCartsByEventAndProductParams struct {
	EventID   pgtype.UUID `json:"event_id"`
	ProductID pgtype.UUID `json:"product_id"`
}

type ListExpiredCartsByEventAndProductRow struct {
	ID                   pgtype.UUID        `json:"id"`
	EventID              pgtype.UUID        `json:"event_id"`
	PlatformUserID       string             `json:"platform_user_id"`
	PlatformHandle       string             `json:"platform_handle"`
	Token                string             `json:"token"`
	Status               string             `json:"status"`
	CheckoutUrl          pgtype.Text        `json:"checkout_url"`
	PaymentIntegrationID pgtype.UUID        `json:"payment_integration_id"`
	ExternalOrderID      pgtype.Text        `json:"external_order_id"`
	PaymentStatus        pgtype.Text        `json:"payment_status"`
	PaidAt               pgtype.Timestamptz `json:"paid_at"`
	NotifyStatus         pgtype.Text        `json:"notify_status"`
	NotifyError          pgtype.Text        `json:"notify_error"`
	NotifiedAt           pgtype.Timestamptz `json:"notified_at"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	ExpiresAt            pgtype.Timestamptz `json:"expires_at"`
	SessionID            pgtype.UUID        `json:"session_id"`
	StoreID              pgtype.UUID        `json:"store_id"`
}

// Returns expired carts for a specific event that contain a specific product
func (q *Queries) ListExpiredCartsByEventAndProduct(ctx context.Context, arg ListExpiredCartsByEventAndProductParams) ([]ListExpiredCartsByEventAndProductRow, error) {
	rows, err := q.db.Query(ctx, listExpiredCartsByEventAndProduct, arg.EventID, arg.ProductID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExpiredCartsByEventAndProductRow{}
	for rows.Next() {
		var i ListExpiredCartsByEventAndProductRow
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.PlatformUserID,
			&i.PlatformHandle,
			&i.Token,
			&i.Status,
			&i.CheckoutUrl,
			&i.PaymentIntegrationID,
			&i.ExternalOrderID,
			&i.PaymentStatus,
			&i.PaidAt,
			&i.NotifyStatus,
			&i.NotifyError,
			&i.NotifiedAt,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.SessionID,
			&i.StoreID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNonWaitlistedCartItems = `-- name: ListNonWaitlistedCartItems :many
SELECT ci.id, ci.cart_id, ci.product_id, ci.quantity, ci.unit_price, ci.waitlisted, p.name AS product_name, p.external_id AS product_external_id,
       p.keyword AS product_keyword, p.image_url AS product_image_url
FROM cart_items ci
JOIN products p ON p.id = ci.product_id
WHERE ci.cart_id = $1 AND ci.waitlisted = false
`

type ListNonWaitlistedCartItemsRow struct {
	ID                pgtype.UUID `json:"id"`
	CartID            pgtype.UUID `json:"cart_id"`
	ProductID         pgtype.UUID `json:"product_id"`
	Quantity          pgtype.Int4 `json:"quantity"`
	UnitPrice         pgtype.Int8 `json:"unit_price"`
	Waitlisted        bool        `json:"waitlisted"`
	ProductName       string      `json:"product_name"`
	ProductExternalID pgtype.Text `json:"product_external_id"`
	ProductKeyword    string      `json:"product_keyword"`
	ProductImageUrl   pgtype.Text `json:"product_image_url"`
}

// Returns cart items that are NOT waitlisted, with product external_id for ERP sync
func (q *Queries) ListNonWaitlistedCartItems(ctx context.Context, cartID pgtype.UUID) ([]ListNonWaitlistedCartItemsRow, error) {
	rows, err := q.db.Query(ctx, listNonWaitlistedCartItems, cartID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNonWaitlistedCartItemsRow{}
	for rows.Next() {
		var i ListNonWaitlistedCartItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.CartID,
			&i.ProductID,
			&i.Quantity,
			&i.UnitPrice,
			&i.Waitlisted,
			&i.ProductName,
			&i.ProductExternalID,
			&i.ProductKeyword,
			&i.ProductImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsByEvent = `-- name: ListProductsByEvent :many
SELECT
    p.id,
    p.name,
    p.image_url,
    p.keyword,
    COALESCE(SUM(ci.quantity), 0)::int AS total_quantity,
    COALESCE(SUM(ci.quantity * ci.unit_price), 0)::bigint AS total_revenue
FROM cart_items ci
JOIN carts c ON c.id = ci.cart_id
JOIN products p ON p.id = ci.product_id
WHERE c.event_id = $1 AND c.status != 'expired'
GROUP BY p.id, p.name, p.image_url, p.keyword
ORDER BY total_quantity DESC
`

type ListProductsByEventRow struct {
	ID            pgtype.UUID `json:"id"`
	Name          string      `json:"name"`
	ImageUrl      pgtype.Text `json:"image_url"`
	Keyword       string      `json:"keyword"`
	TotalQuantity int32       `json:"total_quantity"`
	TotalRevenue  int64       `json:"total_revenue"`
}

// Returns products sold in an event with quantity and revenue
func (q *Queries) ListProductsByEvent(ctx context.Context, eventID pgtype.UUID) ([]ListProductsByEventRow, error) {
	rows, err := q.db.Query(ctx, listProductsByEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProductsByEventRow{}
	for rows.Next() {
		var i ListProductsByEventRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ImageUrl,
			&i.Keyword,
			&i.TotalQuantity,
			&i.TotalRevenue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCartExternalOrderID = `-- name: UpdateCartExternalOrderID :exec

UPDATE carts SET external_order_id = $2 WHERE id = $1
`

type UpdateCartExternalOrderIDParams struct {
	ID              pgtype.UUID `json:"id"`
	ExternalOrderID pgtype.Text `json:"external_order_id"`
}

// =============================================================================
// ERP SYNC & EXPIRATION
// =============================================================================
func (q *Queries) UpdateCartExternalOrderID(ctx context.Context, arg UpdateCartExternalOrderIDParams) error {
	_, err := q.db.Exec(ctx, updateCartExternalOrderID, arg.ID, arg.ExternalOrderID)
	return err
}

const updateCartItem = `-- name: UpdateCartItem :one
UPDATE cart_items
SET quantity = $2
WHERE id = $1
RETURNING id, cart_id, product_id, quantity, unit_price, waitlisted
`

type UpdateCartItemParams struct {
	ID       pgtype.UUID `json:"id"`
	Quantity pgtype.Int4 `json:"quantity"`
}

func (q *Queries) UpdateCartItem(ctx context.Context, arg UpdateCartItemParams) (CartItem, error) {
	row := q.db.QueryRow(ctx, updateCartItem, arg.ID, arg.Quantity)
	var i CartItem
	err := row.Scan(
		&i.ID,
		&i.CartID,
		&i.ProductID,
		&i.Quantity,
		&i.UnitPrice,
		&i.Waitlisted,
	)
	return i, err
}

const updateCartItemWaitlisted = `-- name: UpdateCartItemWaitlisted :exec
UPDATE cart_items SET waitlisted = $3 WHERE cart_id = $1 AND product_id = $2
`

type UpdateCartItemWaitlistedParams struct {
	CartID     pgtype.UUID `json:"cart_id"`
	ProductID  pgtype.UUID `json:"product_id"`
	Waitlisted bool        `json:"waitlisted"`
}

func (q *Queries) UpdateCartItemWaitlisted(ctx context.Context, arg UpdateCartItemWaitlistedParams) error {
	_, err := q.db.Exec(ctx, updateCartItemWaitlisted, arg.CartID, arg.ProductID, arg.Waitlisted)
	return err
}

const updateCartNotifyStatus = `-- name: UpdateCartNotifyStatus :one
UPDATE carts
SET notify_status = $2, notify_error = $3, notified_at = $4
WHERE id = $1
RETURNING id, event_id, platform_user_id, platform_handle, token, status, checkout_url, payment_integration_id, external_order_id, payment_status, paid_at, notify_status, notify_error, notified_at, created_at, expires_at, session_id
`

type UpdateCartNotifyStatusParams struct {
	ID           pgtype.UUID        `json:"id"`
	NotifyStatus pgtype.Text        `json:"notify_status"`
	NotifyError  pgtype.Text        `json:"notify_error"`
	NotifiedAt   pgtype.Timestamptz `json:"notified_at"`
}

func (q *Queries) UpdateCartNotifyStatus(ctx context.Context, arg UpdateCartNotifyStatusParams) (Cart, error) {
	row := q.db.QueryRow(ctx, updateCartNotifyStatus,
		arg.ID,
		arg.NotifyStatus,
		arg.NotifyError,
		arg.NotifiedAt,
	)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.PlatformUserID,
		&i.PlatformHandle,
		&i.Token,
		&i.Status,
		&i.CheckoutUrl,
		&i.PaymentIntegrationID,
		&i.ExternalOrderID,
		&i.PaymentStatus,
		&i.PaidAt,
		&i.NotifyStatus,
		&i.NotifyError,
		&i.NotifiedAt,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.SessionID,
	)
	return i, err
}

const updateCartPayment = `-- name: UpdateCartPayment :one
UPDATE carts
SET payment_status = $2, external_order_id = $3, paid_at = $4
WHERE id = $1
RETURNING id, event_id, platform_user_id, platform_handle, token, status, checkout_url, payment_integration_id, external_order_id, payment_status, paid_at, notify_status, notify_error, notified_at, created_at, expires_at, session_id
`

type UpdateCartPaymentParams struct {
	ID              pgtype.UUID        `json:"id"`
	PaymentStatus   pgtype.Text        `json:"payment_status"`
	ExternalOrderID pgtype.Text        `json:"external_order_id"`
	PaidAt          pgtype.Timestamptz `json:"paid_at"`
}

func (q *Queries) UpdateCartPayment(ctx context.Context, arg UpdateCartPaymentParams) (Cart, error) {
	row := q.db.QueryRow(ctx, updateCartPayment,
		arg.ID,
		arg.PaymentStatus,
		arg.ExternalOrderID,
		arg.PaidAt,
	)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.PlatformUserID,
		&i.PlatformHandle,
		&i.Token,
		&i.Status,
		&i.CheckoutUrl,
		&i.PaymentIntegrationID,
		&i.ExternalOrderID,
		&i.PaymentStatus,
		&i.PaidAt,
		&i.NotifyStatus,
		&i.NotifyError,
		&i.NotifiedAt,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.SessionID,
	)
	return i, err
}

const updateCartStatus = `-- name: UpdateCartStatus :one
UPDATE carts SET status = $2 WHERE id = $1 RETURNING id, event_id, platform_user_id, platform_handle, token, status, checkout_url, payment_integration_id, external_order_id, payment_status, paid_at, notify_status, notify_error, notified_at, created_at, expires_at, session_id
`

type UpdateCartStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateCartStatus(ctx context.Context, arg UpdateCartStatusParams) (Cart, error) {
	row := q.db.QueryRow(ctx, updateCartStatus, arg.ID, arg.Status)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.PlatformUserID,
		&i.PlatformHandle,
		&i.Token,
		&i.Status,
		&i.CheckoutUrl,
		&i.PaymentIntegrationID,
		&i.ExternalOrderID,
		&i.PaymentStatus,
		&i.PaidAt,
		&i.NotifyStatus,
		&i.NotifyError,
		&i.NotifiedAt,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.SessionID,
	)
	return i, err
}

const upsertCartItem = `-- name: UpsertCartItem :one
INSERT INTO cart_items (cart_id, product_id, quantity, unit_price, waitlisted)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (cart_id, product_id)
DO UPDATE SET quantity = cart_items.quantity + EXCLUDED.quantity,
             waitlisted = EXCLUDED.waitlisted
RETURNING id, cart_id, product_id, quantity, unit_price, waitlisted
`

type UpsertCartItemParams struct {
	CartID     pgtype.UUID `json:"cart_id"`
	ProductID  pgtype.UUID `json:"product_id"`
	Quantity   pgtype.Int4 `json:"quantity"`
	UnitPrice  pgtype.Int8 `json:"unit_price"`
	Waitlisted bool        `json:"waitlisted"`
}

// Adds quantity to existing cart item or creates new one
func (q *Queries) UpsertCartItem(ctx context.Context, arg UpsertCartItemParams) (CartItem, error) {
	row := q.db.QueryRow(ctx, upsertCartItem,
		arg.CartID,
		arg.ProductID,
		arg.Quantity,
		arg.UnitPrice,
		arg.Waitlisted,
	)
	var i CartItem
	err := row.Scan(
		&i.ID,
		&i.CartID,
		&i.ProductID,
		&i.Quantity,
		&i.UnitPrice,
		&i.Waitlisted,
	)
	return i, err
}
