// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cart.sql

package sqlc

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCartsByEvent = `-- name: CountCartsByEvent :one
SELECT COUNT(*)::int as count FROM carts WHERE event_id = $1 AND status = 'active'
`

func (q *Queries) CountCartsByEvent(ctx context.Context, eventID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countCartsByEvent, eventID)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const createCart = `-- name: CreateCart :one

INSERT INTO carts (event_id, session_id, platform_user_id, platform_handle, token, status, expires_at, customer_id, short_id)
VALUES ($1, $2, $3, $4, $5, 'active', $6, $7, $8)
RETURNING id, event_id, platform_user_id, platform_handle, token, status, checkout_url, payment_integration_id, external_order_id, payment_status, paid_at, notify_status, notify_error, notified_at, created_at, expires_at, session_id, checkout_id, checkout_expires_at, customer_email, payment_method, customer_name, customer_document, customer_phone, shipping_address, customer_id, shipping_service_id, shipping_service_name, shipping_carrier, shipping_cost_cents, shipping_cost_real_cents, shipping_deadline_days, shipping_quoted_at, shipping_provider, last_shipping_quote_options, last_shipping_quote_at, card_brand, card_last_four, card_installments, card_authorization_code, initial_snapshot_taken_at, initial_subtotal_cents, short_id
`

type CreateCartParams struct {
	EventID        pgtype.UUID        `json:"event_id"`
	SessionID      pgtype.UUID        `json:"session_id"`
	PlatformUserID string             `json:"platform_user_id"`
	PlatformHandle string             `json:"platform_handle"`
	Token          string             `json:"token"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	CustomerID     pgtype.UUID        `json:"customer_id"`
	ShortID        int32              `json:"short_id"`
}

// =============================================================================
// CARTS (belong to events, with optional session tracking)
// =============================================================================
func (q *Queries) CreateCart(ctx context.Context, arg CreateCartParams) (Cart, error) {
	row := q.db.QueryRow(ctx, createCart,
		arg.EventID,
		arg.SessionID,
		arg.PlatformUserID,
		arg.PlatformHandle,
		arg.Token,
		arg.ExpiresAt,
		arg.CustomerID,
		arg.ShortID,
	)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.PlatformUserID,
		&i.PlatformHandle,
		&i.Token,
		&i.Status,
		&i.CheckoutUrl,
		&i.PaymentIntegrationID,
		&i.ExternalOrderID,
		&i.PaymentStatus,
		&i.PaidAt,
		&i.NotifyStatus,
		&i.NotifyError,
		&i.NotifiedAt,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.SessionID,
		&i.CheckoutID,
		&i.CheckoutExpiresAt,
		&i.CustomerEmail,
		&i.PaymentMethod,
		&i.CustomerName,
		&i.CustomerDocument,
		&i.CustomerPhone,
		&i.ShippingAddress,
		&i.CustomerID,
		&i.ShippingServiceID,
		&i.ShippingServiceName,
		&i.ShippingCarrier,
		&i.ShippingCostCents,
		&i.ShippingCostRealCents,
		&i.ShippingDeadlineDays,
		&i.ShippingQuotedAt,
		&i.ShippingProvider,
		&i.LastShippingQuoteOptions,
		&i.LastShippingQuoteAt,
		&i.CardBrand,
		&i.CardLastFour,
		&i.CardInstallments,
		&i.CardAuthorizationCode,
		&i.InitialSnapshotTakenAt,
		&i.InitialSubtotalCents,
		&i.ShortID,
	)
	return i, err
}

const createCartItem = `-- name: CreateCartItem :one
INSERT INTO cart_items (cart_id, product_id, quantity, unit_price, waitlisted_quantity)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, cart_id, product_id, quantity, unit_price, waitlisted_quantity
`

type CreateCartItemParams struct {
	CartID             pgtype.UUID `json:"cart_id"`
	ProductID          pgtype.UUID `json:"product_id"`
	Quantity           pgtype.Int4 `json:"quantity"`
	UnitPrice          pgtype.Int8 `json:"unit_price"`
	WaitlistedQuantity int32       `json:"waitlisted_quantity"`
}

func (q *Queries) CreateCartItem(ctx context.Context, arg CreateCartItemParams) (CartItem, error) {
	row := q.db.QueryRow(ctx, createCartItem,
		arg.CartID,
		arg.ProductID,
		arg.Quantity,
		arg.UnitPrice,
		arg.WaitlistedQuantity,
	)
	var i CartItem
	err := row.Scan(
		&i.ID,
		&i.CartID,
		&i.ProductID,
		&i.Quantity,
		&i.UnitPrice,
		&i.WaitlistedQuantity,
	)
	return i, err
}

const deleteCartItem = `-- name: DeleteCartItem :exec
DELETE FROM cart_items WHERE id = $1
`

func (q *Queries) DeleteCartItem(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCartItem, id)
	return err
}

const deleteCartItemByCartAndProduct = `-- name: DeleteCartItemByCartAndProduct :exec
DELETE FROM cart_items WHERE cart_id = $1 AND product_id = $2
`

type DeleteCartItemByCartAndProductParams struct {
	CartID    pgtype.UUID `json:"cart_id"`
	ProductID pgtype.UUID `json:"product_id"`
}

func (q *Queries) DeleteCartItemByCartAndProduct(ctx context.Context, arg DeleteCartItemByCartAndProductParams) error {
	_, err := q.db.Exec(ctx, deleteCartItemByCartAndProduct, arg.CartID, arg.ProductID)
	return err
}

const finalizeCartsByEvent = `-- name: FinalizeCartsByEvent :exec
UPDATE carts
SET status = 'checkout'
WHERE event_id = $1 AND status = 'active'
`

// Updates all active carts in an event to checkout status (live ended)
func (q *Queries) FinalizeCartsByEvent(ctx context.Context, eventID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, finalizeCartsByEvent, eventID)
	return err
}

const getCartByCheckoutID = `-- name: GetCartByCheckoutID :one
SELECT id, event_id, platform_user_id, platform_handle, token, status, checkout_url, payment_integration_id, external_order_id, payment_status, paid_at, notify_status, notify_error, notified_at, created_at, expires_at, session_id, checkout_id, checkout_expires_at, customer_email, payment_method, customer_name, customer_document, customer_phone, shipping_address, customer_id, shipping_service_id, shipping_service_name, shipping_carrier, shipping_cost_cents, shipping_cost_real_cents, shipping_deadline_days, shipping_quoted_at, shipping_provider, last_shipping_quote_options, last_shipping_quote_at, card_brand, card_last_four, card_installments, card_authorization_code, initial_snapshot_taken_at, initial_subtotal_cents, short_id FROM carts WHERE checkout_id = $1
`

// Used by webhook to find cart when payment is confirmed
func (q *Queries) GetCartByCheckoutID(ctx context.Context, checkoutID pgtype.Text) (Cart, error) {
	row := q.db.QueryRow(ctx, getCartByCheckoutID, checkoutID)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.PlatformUserID,
		&i.PlatformHandle,
		&i.Token,
		&i.Status,
		&i.CheckoutUrl,
		&i.PaymentIntegrationID,
		&i.ExternalOrderID,
		&i.PaymentStatus,
		&i.PaidAt,
		&i.NotifyStatus,
		&i.NotifyError,
		&i.NotifiedAt,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.SessionID,
		&i.CheckoutID,
		&i.CheckoutExpiresAt,
		&i.CustomerEmail,
		&i.PaymentMethod,
		&i.CustomerName,
		&i.CustomerDocument,
		&i.CustomerPhone,
		&i.ShippingAddress,
		&i.CustomerID,
		&i.ShippingServiceID,
		&i.ShippingServiceName,
		&i.ShippingCarrier,
		&i.ShippingCostCents,
		&i.ShippingCostRealCents,
		&i.ShippingDeadlineDays,
		&i.ShippingQuotedAt,
		&i.ShippingProvider,
		&i.LastShippingQuoteOptions,
		&i.LastShippingQuoteAt,
		&i.CardBrand,
		&i.CardLastFour,
		&i.CardInstallments,
		&i.CardAuthorizationCode,
		&i.InitialSnapshotTakenAt,
		&i.InitialSubtotalCents,
		&i.ShortID,
	)
	return i, err
}

const getCartByEventAndUser = `-- name: GetCartByEventAndUser :one
SELECT id, event_id, platform_user_id, platform_handle, token, status, checkout_url, payment_integration_id, external_order_id, payment_status, paid_at, notify_status, notify_error, notified_at, created_at, expires_at, session_id, checkout_id, checkout_expires_at, customer_email, payment_method, customer_name, customer_document, customer_phone, shipping_address, customer_id, shipping_service_id, shipping_service_name, shipping_carrier, shipping_cost_cents, shipping_cost_real_cents, shipping_deadline_days, shipping_quoted_at, shipping_provider, last_shipping_quote_options, last_shipping_quote_at, card_brand, card_last_four, card_installments, card_authorization_code, initial_snapshot_taken_at, initial_subtotal_cents, short_id FROM carts WHERE event_id = $1 AND platform_user_id = $2
`

type GetCartByEventAndUserParams struct {
	EventID        pgtype.UUID `json:"event_id"`
	PlatformUserID string      `json:"platform_user_id"`
}

func (q *Queries) GetCartByEventAndUser(ctx context.Context, arg GetCartByEventAndUserParams) (Cart, error) {
	row := q.db.QueryRow(ctx, getCartByEventAndUser, arg.EventID, arg.PlatformUserID)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.PlatformUserID,
		&i.PlatformHandle,
		&i.Token,
		&i.Status,
		&i.CheckoutUrl,
		&i.PaymentIntegrationID,
		&i.ExternalOrderID,
		&i.PaymentStatus,
		&i.PaidAt,
		&i.NotifyStatus,
		&i.NotifyError,
		&i.NotifiedAt,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.SessionID,
		&i.CheckoutID,
		&i.CheckoutExpiresAt,
		&i.CustomerEmail,
		&i.PaymentMethod,
		&i.CustomerName,
		&i.CustomerDocument,
		&i.CustomerPhone,
		&i.ShippingAddress,
		&i.CustomerID,
		&i.ShippingServiceID,
		&i.ShippingServiceName,
		&i.ShippingCarrier,
		&i.ShippingCostCents,
		&i.ShippingCostRealCents,
		&i.ShippingDeadlineDays,
		&i.ShippingQuotedAt,
		&i.ShippingProvider,
		&i.LastShippingQuoteOptions,
		&i.LastShippingQuoteAt,
		&i.CardBrand,
		&i.CardLastFour,
		&i.CardInstallments,
		&i.CardAuthorizationCode,
		&i.InitialSnapshotTakenAt,
		&i.InitialSubtotalCents,
		&i.ShortID,
	)
	return i, err
}

const getCartByEventAndUserForUpdate = `-- name: GetCartByEventAndUserForUpdate :one
SELECT id, event_id, platform_user_id, platform_handle, token, status, checkout_url, payment_integration_id, external_order_id, payment_status, paid_at, notify_status, notify_error, notified_at, created_at, expires_at, session_id, checkout_id, checkout_expires_at, customer_email, payment_method, customer_name, customer_document, customer_phone, shipping_address, customer_id, shipping_service_id, shipping_service_name, shipping_carrier, shipping_cost_cents, shipping_cost_real_cents, shipping_deadline_days, shipping_quoted_at, shipping_provider, last_shipping_quote_options, last_shipping_quote_at, card_brand, card_last_four, card_installments, card_authorization_code, initial_snapshot_taken_at, initial_subtotal_cents, short_id FROM carts WHERE event_id = $1 AND platform_user_id = $2 FOR UPDATE
`

type GetCartByEventAndUserForUpdateParams struct {
	EventID        pgtype.UUID `json:"event_id"`
	PlatformUserID string      `json:"platform_user_id"`
}

// Lock the cart row for concurrent safety
func (q *Queries) GetCartByEventAndUserForUpdate(ctx context.Context, arg GetCartByEventAndUserForUpdateParams) (Cart, error) {
	row := q.db.QueryRow(ctx, getCartByEventAndUserForUpdate, arg.EventID, arg.PlatformUserID)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.PlatformUserID,
		&i.PlatformHandle,
		&i.Token,
		&i.Status,
		&i.CheckoutUrl,
		&i.PaymentIntegrationID,
		&i.ExternalOrderID,
		&i.PaymentStatus,
		&i.PaidAt,
		&i.NotifyStatus,
		&i.NotifyError,
		&i.NotifiedAt,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.SessionID,
		&i.CheckoutID,
		&i.CheckoutExpiresAt,
		&i.CustomerEmail,
		&i.PaymentMethod,
		&i.CustomerName,
		&i.CustomerDocument,
		&i.CustomerPhone,
		&i.ShippingAddress,
		&i.CustomerID,
		&i.ShippingServiceID,
		&i.ShippingServiceName,
		&i.ShippingCarrier,
		&i.ShippingCostCents,
		&i.ShippingCostRealCents,
		&i.ShippingDeadlineDays,
		&i.ShippingQuotedAt,
		&i.ShippingProvider,
		&i.LastShippingQuoteOptions,
		&i.LastShippingQuoteAt,
		&i.CardBrand,
		&i.CardLastFour,
		&i.CardInstallments,
		&i.CardAuthorizationCode,
		&i.InitialSnapshotTakenAt,
		&i.InitialSubtotalCents,
		&i.ShortID,
	)
	return i, err
}

const getCartByID = `-- name: GetCartByID :one
SELECT id, event_id, platform_user_id, platform_handle, token, status, checkout_url, payment_integration_id, external_order_id, payment_status, paid_at, notify_status, notify_error, notified_at, created_at, expires_at, session_id, checkout_id, checkout_expires_at, customer_email, payment_method, customer_name, customer_document, customer_phone, shipping_address, customer_id, shipping_service_id, shipping_service_name, shipping_carrier, shipping_cost_cents, shipping_cost_real_cents, shipping_deadline_days, shipping_quoted_at, shipping_provider, last_shipping_quote_options, last_shipping_quote_at, card_brand, card_last_four, card_installments, card_authorization_code, initial_snapshot_taken_at, initial_subtotal_cents, short_id FROM carts WHERE id = $1
`

func (q *Queries) GetCartByID(ctx context.Context, id pgtype.UUID) (Cart, error) {
	row := q.db.QueryRow(ctx, getCartByID, id)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.PlatformUserID,
		&i.PlatformHandle,
		&i.Token,
		&i.Status,
		&i.CheckoutUrl,
		&i.PaymentIntegrationID,
		&i.ExternalOrderID,
		&i.PaymentStatus,
		&i.PaidAt,
		&i.NotifyStatus,
		&i.NotifyError,
		&i.NotifiedAt,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.SessionID,
		&i.CheckoutID,
		&i.CheckoutExpiresAt,
		&i.CustomerEmail,
		&i.PaymentMethod,
		&i.CustomerName,
		&i.CustomerDocument,
		&i.CustomerPhone,
		&i.ShippingAddress,
		&i.CustomerID,
		&i.ShippingServiceID,
		&i.ShippingServiceName,
		&i.ShippingCarrier,
		&i.ShippingCostCents,
		&i.ShippingCostRealCents,
		&i.ShippingDeadlineDays,
		&i.ShippingQuotedAt,
		&i.ShippingProvider,
		&i.LastShippingQuoteOptions,
		&i.LastShippingQuoteAt,
		&i.CardBrand,
		&i.CardLastFour,
		&i.CardInstallments,
		&i.CardAuthorizationCode,
		&i.InitialSnapshotTakenAt,
		&i.InitialSubtotalCents,
		&i.ShortID,
	)
	return i, err
}

const getCartByToken = `-- name: GetCartByToken :one
SELECT id, event_id, platform_user_id, platform_handle, token, status, checkout_url, payment_integration_id, external_order_id, payment_status, paid_at, notify_status, notify_error, notified_at, created_at, expires_at, session_id, checkout_id, checkout_expires_at, customer_email, payment_method, customer_name, customer_document, customer_phone, shipping_address, customer_id, shipping_service_id, shipping_service_name, shipping_carrier, shipping_cost_cents, shipping_cost_real_cents, shipping_deadline_days, shipping_quoted_at, shipping_provider, last_shipping_quote_options, last_shipping_quote_at, card_brand, card_last_four, card_installments, card_authorization_code, initial_snapshot_taken_at, initial_subtotal_cents, short_id FROM carts WHERE token = $1
`

func (q *Queries) GetCartByToken(ctx context.Context, token string) (Cart, error) {
	row := q.db.QueryRow(ctx, getCartByToken, token)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.PlatformUserID,
		&i.PlatformHandle,
		&i.Token,
		&i.Status,
		&i.CheckoutUrl,
		&i.PaymentIntegrationID,
		&i.ExternalOrderID,
		&i.PaymentStatus,
		&i.PaidAt,
		&i.NotifyStatus,
		&i.NotifyError,
		&i.NotifiedAt,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.SessionID,
		&i.CheckoutID,
		&i.CheckoutExpiresAt,
		&i.CustomerEmail,
		&i.PaymentMethod,
		&i.CustomerName,
		&i.CustomerDocument,
		&i.CustomerPhone,
		&i.ShippingAddress,
		&i.CustomerID,
		&i.ShippingServiceID,
		&i.ShippingServiceName,
		&i.ShippingCarrier,
		&i.ShippingCostCents,
		&i.ShippingCostRealCents,
		&i.ShippingDeadlineDays,
		&i.ShippingQuotedAt,
		&i.ShippingProvider,
		&i.LastShippingQuoteOptions,
		&i.LastShippingQuoteAt,
		&i.CardBrand,
		&i.CardLastFour,
		&i.CardInstallments,
		&i.CardAuthorizationCode,
		&i.InitialSnapshotTakenAt,
		&i.InitialSubtotalCents,
		&i.ShortID,
	)
	return i, err
}

const getCartByTokenWithDetails = `-- name: GetCartByTokenWithDetails :one

SELECT
    c.id,
    c.event_id,
    c.platform_user_id,
    c.platform_handle,
    c.token,
    c.status,
    c.checkout_url,
    c.checkout_id,
    c.checkout_expires_at,
    c.customer_email,
    c.payment_status,
    c.paid_at,
    c.created_at,
    c.expires_at,
    c.initial_snapshot_taken_at,
    c.initial_subtotal_cents,
    le.title AS event_title,
    le.store_id,
    s.name AS store_name,
    s.logo_url AS store_logo_url,
    s.cart_allow_edit AS allow_edit,
    s.cart_max_quantity_per_item AS max_quantity_per_item
FROM carts c
JOIN live_events le ON le.id = c.event_id
JOIN stores s ON s.id = le.store_id
WHERE c.token = $1
`

type GetCartByTokenWithDetailsRow struct {
	ID                     pgtype.UUID        `json:"id"`
	EventID                pgtype.UUID        `json:"event_id"`
	PlatformUserID         string             `json:"platform_user_id"`
	PlatformHandle         string             `json:"platform_handle"`
	Token                  string             `json:"token"`
	Status                 string             `json:"status"`
	CheckoutUrl            pgtype.Text        `json:"checkout_url"`
	CheckoutID             pgtype.Text        `json:"checkout_id"`
	CheckoutExpiresAt      pgtype.Timestamptz `json:"checkout_expires_at"`
	CustomerEmail          pgtype.Text        `json:"customer_email"`
	PaymentStatus          pgtype.Text        `json:"payment_status"`
	PaidAt                 pgtype.Timestamptz `json:"paid_at"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	ExpiresAt              pgtype.Timestamptz `json:"expires_at"`
	InitialSnapshotTakenAt pgtype.Timestamptz `json:"initial_snapshot_taken_at"`
	InitialSubtotalCents   pgtype.Int8        `json:"initial_subtotal_cents"`
	EventTitle             pgtype.Text        `json:"event_title"`
	StoreID                pgtype.UUID        `json:"store_id"`
	StoreName              string             `json:"store_name"`
	StoreLogoUrl           pgtype.Text        `json:"store_logo_url"`
	AllowEdit              bool               `json:"allow_edit"`
	MaxQuantityPerItem     int32              `json:"max_quantity_per_item"`
}

// =============================================================================
// PUBLIC CHECKOUT - Cart page for customers
// =============================================================================
// Returns cart with event info for public checkout page
func (q *Queries) GetCartByTokenWithDetails(ctx context.Context, token string) (GetCartByTokenWithDetailsRow, error) {
	row := q.db.QueryRow(ctx, getCartByTokenWithDetails, token)
	var i GetCartByTokenWithDetailsRow
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.PlatformUserID,
		&i.PlatformHandle,
		&i.Token,
		&i.Status,
		&i.CheckoutUrl,
		&i.CheckoutID,
		&i.CheckoutExpiresAt,
		&i.CustomerEmail,
		&i.PaymentStatus,
		&i.PaidAt,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.InitialSnapshotTakenAt,
		&i.InitialSubtotalCents,
		&i.EventTitle,
		&i.StoreID,
		&i.StoreName,
		&i.StoreLogoUrl,
		&i.AllowEdit,
		&i.MaxQuantityPerItem,
	)
	return i, err
}

const getCartItem = `-- name: GetCartItem :one
SELECT id, cart_id, product_id, quantity, unit_price, waitlisted_quantity FROM cart_items WHERE id = $1
`

func (q *Queries) GetCartItem(ctx context.Context, id pgtype.UUID) (CartItem, error) {
	row := q.db.QueryRow(ctx, getCartItem, id)
	var i CartItem
	err := row.Scan(
		&i.ID,
		&i.CartID,
		&i.ProductID,
		&i.Quantity,
		&i.UnitPrice,
		&i.WaitlistedQuantity,
	)
	return i, err
}

const getCartTotals = `-- name: GetCartTotals :one
SELECT
    COALESCE(SUM(ci.quantity), 0)::int AS total_items,
    COALESCE(SUM(ci.quantity * ci.unit_price), 0)::bigint AS total_value
FROM cart_items ci
WHERE ci.cart_id = $1
`

type GetCartTotalsRow struct {
	TotalItems int32 `json:"total_items"`
	TotalValue int64 `json:"total_value"`
}

// Returns total items and value for a cart (for notifications)
func (q *Queries) GetCartTotals(ctx context.Context, cartID pgtype.UUID) (GetCartTotalsRow, error) {
	row := q.db.QueryRow(ctx, getCartTotals, cartID)
	var i GetCartTotalsRow
	err := row.Scan(&i.TotalItems, &i.TotalValue)
	return i, err
}

const getEventStats = `-- name: GetEventStats :one

SELECT
    -- Funnel metrics
    COALESCE((SELECT SUM(ls.total_comments) FROM live_sessions ls WHERE ls.event_id = $1), 0)::int AS total_comments,
    COALESCE((SELECT COUNT(*) FROM carts ct WHERE ct.event_id = $1), 0)::int AS total_carts,
    COALESCE((SELECT COUNT(*) FROM carts ct WHERE ct.event_id = $1 AND ct.status IN ('active', 'checkout')), 0)::int AS open_carts,
    COALESCE((SELECT COUNT(*) FROM carts ct WHERE ct.event_id = $1 AND (ct.status = 'checkout' OR ct.checkout_url IS NOT NULL)), 0)::int AS checkout_carts,
    COALESCE((SELECT COUNT(*) FROM carts ct WHERE ct.event_id = $1 AND ct.payment_status = 'paid'), 0)::int AS paid_carts,
    -- Product metrics
    COALESCE((
        SELECT SUM(ci.quantity)
        FROM carts ct
        JOIN cart_items ci ON ci.cart_id = ct.id
        WHERE ct.event_id = $1 AND ct.status != 'expired'
    ), 0)::int AS total_products_sold,
    -- Revenue metrics
    COALESCE((
        SELECT SUM(ci.quantity * ci.unit_price)
        FROM carts ct
        JOIN cart_items ci ON ci.cart_id = ct.id
        WHERE ct.event_id = $1 AND ct.status IN ('active', 'checkout')
    ), 0)::bigint AS projected_revenue,
    COALESCE((
        SELECT SUM(ci.quantity * ci.unit_price)
        FROM carts ct
        JOIN cart_items ci ON ci.cart_id = ct.id
        WHERE ct.event_id = $1 AND ct.payment_status = 'paid'
    ), 0)::bigint AS confirmed_revenue
`

type GetEventStatsRow struct {
	TotalComments     int32 `json:"total_comments"`
	TotalCarts        int32 `json:"total_carts"`
	OpenCarts         int32 `json:"open_carts"`
	CheckoutCarts     int32 `json:"checkout_carts"`
	PaidCarts         int32 `json:"paid_carts"`
	TotalProductsSold int32 `json:"total_products_sold"`
	ProjectedRevenue  int64 `json:"projected_revenue"`
	ConfirmedRevenue  int64 `json:"confirmed_revenue"`
}

// =============================================================================
// EVENT DETAILS - Stats and Cart Listing
// =============================================================================
// Returns stats for an event: comments, carts, revenue, products sold, funnel metrics
func (q *Queries) GetEventStats(ctx context.Context, eventID pgtype.UUID) (GetEventStatsRow, error) {
	row := q.db.QueryRow(ctx, getEventStats, eventID)
	var i GetEventStatsRow
	err := row.Scan(
		&i.TotalComments,
		&i.TotalCarts,
		&i.OpenCarts,
		&i.CheckoutCarts,
		&i.PaidCarts,
		&i.TotalProductsSold,
		&i.ProjectedRevenue,
		&i.ConfirmedRevenue,
	)
	return i, err
}

const getProductQuantityInUserCart = `-- name: GetProductQuantityInUserCart :one
SELECT COALESCE(ci.quantity, 0)::INT AS quantity
FROM carts c
LEFT JOIN cart_items ci ON ci.cart_id = c.id AND ci.product_id = $3
WHERE c.event_id = $1 AND c.platform_user_id = $2
`

type GetProductQuantityInUserCartParams struct {
	EventID        pgtype.UUID `json:"event_id"`
	PlatformUserID string      `json:"platform_user_id"`
	ProductID      pgtype.UUID `json:"product_id"`
}

// Returns the current quantity of a specific product in a user's cart for an event
func (q *Queries) GetProductQuantityInUserCart(ctx context.Context, arg GetProductQuantityInUserCartParams) (int32, error) {
	row := q.db.QueryRow(ctx, getProductQuantityInUserCart, arg.EventID, arg.PlatformUserID, arg.ProductID)
	var quantity int32
	err := row.Scan(&quantity)
	return quantity, err
}

const getSessionStats = `-- name: GetSessionStats :one

SELECT
    COALESCE((SELECT COUNT(*) FROM carts ct WHERE ct.session_id = $1), 0)::int AS total_carts,
    COALESCE((SELECT COUNT(*) FROM carts ct WHERE ct.session_id = $1 AND ct.payment_status = 'paid'), 0)::int AS paid_carts,
    COALESCE((
        SELECT SUM(ci.quantity * ci.unit_price)
        FROM carts ct
        JOIN cart_items ci ON ci.cart_id = ct.id
        WHERE ct.session_id = $1 AND ct.status != 'expired'
    ), 0)::bigint AS total_revenue,
    COALESCE((
        SELECT SUM(ci.quantity * ci.unit_price)
        FROM carts ct
        JOIN cart_items ci ON ci.cart_id = ct.id
        WHERE ct.session_id = $1 AND ct.payment_status = 'paid'
    ), 0)::bigint AS paid_revenue
`

type GetSessionStatsRow struct {
	TotalCarts   int32 `json:"total_carts"`
	PaidCarts    int32 `json:"paid_carts"`
	TotalRevenue int64 `json:"total_revenue"`
	PaidRevenue  int64 `json:"paid_revenue"`
}

// =============================================================================
// SESSION DETAILS - Stats per session
// =============================================================================
// Returns stats for a specific session: carts count and revenue
func (q *Queries) GetSessionStats(ctx context.Context, sessionID pgtype.UUID) (GetSessionStatsRow, error) {
	row := q.db.QueryRow(ctx, getSessionStats, sessionID)
	var i GetSessionStatsRow
	err := row.Scan(
		&i.TotalCarts,
		&i.PaidCarts,
		&i.TotalRevenue,
		&i.PaidRevenue,
	)
	return i, err
}

const getStorePaymentIntegration = `-- name: GetStorePaymentIntegration :one
SELECT i.id, i.store_id, i.type, i.provider, i.status, i.token_expires_at, i.last_synced_at, i.created_at, i.credentials, i.metadata
FROM integrations i
WHERE i.store_id = $1
  AND i.type = 'payment'
  AND i.status = 'active'
LIMIT 1
`

// Gets the active payment integration for a store
func (q *Queries) GetStorePaymentIntegration(ctx context.Context, storeID pgtype.UUID) (Integration, error) {
	row := q.db.QueryRow(ctx, getStorePaymentIntegration, storeID)
	var i Integration
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.Type,
		&i.Provider,
		&i.Status,
		&i.TokenExpiresAt,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.Credentials,
		&i.Metadata,
	)
	return i, err
}

const issueShortIDForEvent = `-- name: IssueShortIDForEvent :one
INSERT INTO store_order_counters (store_id, last_value)
SELECT e.store_id, 1000 FROM live_events e WHERE e.id = $1
ON CONFLICT (store_id) DO UPDATE SET last_value = store_order_counters.last_value + 1
RETURNING last_value
`

// Atomically issues the next short_id for the store that owns the given event.
// On first call for a store, INSERT seeds last_value at 1000 (the chosen
// starting number). On subsequent calls, the ON CONFLICT UPDATE bumps
// last_value by 1 and returns the new value. Either way the RETURNING clause
// gives the caller the short_id it should write into the cart row in the same
// transaction. Accepts event_id so callers don't need to resolve store_id
// themselves.
func (q *Queries) IssueShortIDForEvent(ctx context.Context, id pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, issueShortIDForEvent, id)
	var last_value int32
	err := row.Scan(&last_value)
	return last_value, err
}

const listCartItems = `-- name: ListCartItems :many
SELECT ci.id, ci.cart_id, ci.product_id, ci.quantity, ci.unit_price, ci.waitlisted_quantity, p.name AS product_name, p.image_url AS product_image_url
FROM cart_items ci
JOIN products p ON p.id = ci.product_id
WHERE ci.cart_id = $1
`

type ListCartItemsRow struct {
	ID                 pgtype.UUID `json:"id"`
	CartID             pgtype.UUID `json:"cart_id"`
	ProductID          pgtype.UUID `json:"product_id"`
	Quantity           pgtype.Int4 `json:"quantity"`
	UnitPrice          pgtype.Int8 `json:"unit_price"`
	WaitlistedQuantity int32       `json:"waitlisted_quantity"`
	ProductName        string      `json:"product_name"`
	ProductImageUrl    pgtype.Text `json:"product_image_url"`
}

func (q *Queries) ListCartItems(ctx context.Context, cartID pgtype.UUID) ([]ListCartItemsRow, error) {
	rows, err := q.db.Query(ctx, listCartItems, cartID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCartItemsRow{}
	for rows.Next() {
		var i ListCartItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.CartID,
			&i.ProductID,
			&i.Quantity,
			&i.UnitPrice,
			&i.WaitlistedQuantity,
			&i.ProductName,
			&i.ProductImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCartItemsForCheckout = `-- name: ListCartItemsForCheckout :many
SELECT
    ci.id,
    ci.cart_id,
    ci.product_id,
    ci.quantity,
    ci.unit_price,
    ci.waitlisted_quantity,
    p.name AS product_name,
    p.image_url AS product_image_url,
    p.keyword AS product_keyword,
    p.stock AS product_stock
FROM cart_items ci
JOIN products p ON p.id = ci.product_id
WHERE ci.cart_id = $1
ORDER BY ci.id
`

type ListCartItemsForCheckoutRow struct {
	ID                 pgtype.UUID `json:"id"`
	CartID             pgtype.UUID `json:"cart_id"`
	ProductID          pgtype.UUID `json:"product_id"`
	Quantity           pgtype.Int4 `json:"quantity"`
	UnitPrice          pgtype.Int8 `json:"unit_price"`
	WaitlistedQuantity int32       `json:"waitlisted_quantity"`
	ProductName        string      `json:"product_name"`
	ProductImageUrl    pgtype.Text `json:"product_image_url"`
	ProductKeyword     string      `json:"product_keyword"`
	ProductStock       pgtype.Int4 `json:"product_stock"`
}

// Returns cart items with product details for checkout page.
// product_stock is exposed so the public checkout can disable the "+" button
// when the buyer is about to exceed the available stock for the SKU.
func (q *Queries) ListCartItemsForCheckout(ctx context.Context, cartID pgtype.UUID) ([]ListCartItemsForCheckoutRow, error) {
	rows, err := q.db.Query(ctx, listCartItemsForCheckout, cartID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCartItemsForCheckoutRow{}
	for rows.Next() {
		var i ListCartItemsForCheckoutRow
		if err := rows.Scan(
			&i.ID,
			&i.CartID,
			&i.ProductID,
			&i.Quantity,
			&i.UnitPrice,
			&i.WaitlistedQuantity,
			&i.ProductName,
			&i.ProductImageUrl,
			&i.ProductKeyword,
			&i.ProductStock,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCartsByCustomer = `-- name: ListCartsByCustomer :many
SELECT
    c.id, c.event_id, c.platform_user_id, c.platform_handle, c.token, c.status, c.checkout_url, c.payment_integration_id, c.external_order_id, c.payment_status, c.paid_at, c.notify_status, c.notify_error, c.notified_at, c.created_at, c.expires_at, c.session_id, c.checkout_id, c.checkout_expires_at, c.customer_email, c.payment_method, c.customer_name, c.customer_document, c.customer_phone, c.shipping_address, c.customer_id, c.shipping_service_id, c.shipping_service_name, c.shipping_carrier, c.shipping_cost_cents, c.shipping_cost_real_cents, c.shipping_deadline_days, c.shipping_quoted_at, c.shipping_provider, c.last_shipping_quote_options, c.last_shipping_quote_at, c.card_brand, c.card_last_four, c.card_installments, c.card_authorization_code, c.initial_snapshot_taken_at, c.initial_subtotal_cents, c.short_id,
    COALESCE(SUM(ci.quantity * ci.unit_price), 0)::bigint AS total_value,
    COALESCE(SUM(ci.quantity), 0)::int AS total_items
FROM carts c
LEFT JOIN cart_items ci ON ci.cart_id = c.id
WHERE c.customer_id = $1
GROUP BY c.id
ORDER BY c.created_at DESC
LIMIT $2 OFFSET $3
`

type ListCartsByCustomerParams struct {
	CustomerID pgtype.UUID `json:"customer_id"`
	Limit      int32       `json:"limit"`
	Offset     int32       `json:"offset"`
}

type ListCartsByCustomerRow struct {
	ID                       pgtype.UUID        `json:"id"`
	EventID                  pgtype.UUID        `json:"event_id"`
	PlatformUserID           string             `json:"platform_user_id"`
	PlatformHandle           string             `json:"platform_handle"`
	Token                    string             `json:"token"`
	Status                   string             `json:"status"`
	CheckoutUrl              pgtype.Text        `json:"checkout_url"`
	PaymentIntegrationID     pgtype.UUID        `json:"payment_integration_id"`
	ExternalOrderID          pgtype.Text        `json:"external_order_id"`
	PaymentStatus            pgtype.Text        `json:"payment_status"`
	PaidAt                   pgtype.Timestamptz `json:"paid_at"`
	NotifyStatus             pgtype.Text        `json:"notify_status"`
	NotifyError              pgtype.Text        `json:"notify_error"`
	NotifiedAt               pgtype.Timestamptz `json:"notified_at"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	ExpiresAt                pgtype.Timestamptz `json:"expires_at"`
	SessionID                pgtype.UUID        `json:"session_id"`
	CheckoutID               pgtype.Text        `json:"checkout_id"`
	CheckoutExpiresAt        pgtype.Timestamptz `json:"checkout_expires_at"`
	CustomerEmail            pgtype.Text        `json:"customer_email"`
	PaymentMethod            pgtype.Text        `json:"payment_method"`
	CustomerName             pgtype.Text        `json:"customer_name"`
	CustomerDocument         pgtype.Text        `json:"customer_document"`
	CustomerPhone            pgtype.Text        `json:"customer_phone"`
	ShippingAddress          json.RawMessage    `json:"shipping_address"`
	CustomerID               pgtype.UUID        `json:"customer_id"`
	ShippingServiceID        pgtype.Text        `json:"shipping_service_id"`
	ShippingServiceName      pgtype.Text        `json:"shipping_service_name"`
	ShippingCarrier          pgtype.Text        `json:"shipping_carrier"`
	ShippingCostCents        pgtype.Int8        `json:"shipping_cost_cents"`
	ShippingCostRealCents    pgtype.Int8        `json:"shipping_cost_real_cents"`
	ShippingDeadlineDays     pgtype.Int4        `json:"shipping_deadline_days"`
	ShippingQuotedAt         pgtype.Timestamptz `json:"shipping_quoted_at"`
	ShippingProvider         pgtype.Text        `json:"shipping_provider"`
	LastShippingQuoteOptions json.RawMessage    `json:"last_shipping_quote_options"`
	LastShippingQuoteAt      pgtype.Timestamptz `json:"last_shipping_quote_at"`
	CardBrand                pgtype.Text        `json:"card_brand"`
	CardLastFour             pgtype.Text        `json:"card_last_four"`
	CardInstallments         pgtype.Int4        `json:"card_installments"`
	CardAuthorizationCode    pgtype.Text        `json:"card_authorization_code"`
	InitialSnapshotTakenAt   pgtype.Timestamptz `json:"initial_snapshot_taken_at"`
	InitialSubtotalCents     pgtype.Int8        `json:"initial_subtotal_cents"`
	ShortID                  int32              `json:"short_id"`
	TotalValue               int64              `json:"total_value"`
	TotalItems               int32              `json:"total_items"`
}

// Returns all carts for a specific customer with totals
func (q *Queries) ListCartsByCustomer(ctx context.Context, arg ListCartsByCustomerParams) ([]ListCartsByCustomerRow, error) {
	rows, err := q.db.Query(ctx, listCartsByCustomer, arg.CustomerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCartsByCustomerRow{}
	for rows.Next() {
		var i ListCartsByCustomerRow
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.PlatformUserID,
			&i.PlatformHandle,
			&i.Token,
			&i.Status,
			&i.CheckoutUrl,
			&i.PaymentIntegrationID,
			&i.ExternalOrderID,
			&i.PaymentStatus,
			&i.PaidAt,
			&i.NotifyStatus,
			&i.NotifyError,
			&i.NotifiedAt,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.SessionID,
			&i.CheckoutID,
			&i.CheckoutExpiresAt,
			&i.CustomerEmail,
			&i.PaymentMethod,
			&i.CustomerName,
			&i.CustomerDocument,
			&i.CustomerPhone,
			&i.ShippingAddress,
			&i.CustomerID,
			&i.ShippingServiceID,
			&i.ShippingServiceName,
			&i.ShippingCarrier,
			&i.ShippingCostCents,
			&i.ShippingCostRealCents,
			&i.ShippingDeadlineDays,
			&i.ShippingQuotedAt,
			&i.ShippingProvider,
			&i.LastShippingQuoteOptions,
			&i.LastShippingQuoteAt,
			&i.CardBrand,
			&i.CardLastFour,
			&i.CardInstallments,
			&i.CardAuthorizationCode,
			&i.InitialSnapshotTakenAt,
			&i.InitialSubtotalCents,
			&i.ShortID,
			&i.TotalValue,
			&i.TotalItems,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCartsByEvent = `-- name: ListCartsByEvent :many
SELECT id, event_id, platform_user_id, platform_handle, token, status, checkout_url, payment_integration_id, external_order_id, payment_status, paid_at, notify_status, notify_error, notified_at, created_at, expires_at, session_id, checkout_id, checkout_expires_at, customer_email, payment_method, customer_name, customer_document, customer_phone, shipping_address, customer_id, shipping_service_id, shipping_service_name, shipping_carrier, shipping_cost_cents, shipping_cost_real_cents, shipping_deadline_days, shipping_quoted_at, shipping_provider, last_shipping_quote_options, last_shipping_quote_at, card_brand, card_last_four, card_installments, card_authorization_code, initial_snapshot_taken_at, initial_subtotal_cents, short_id FROM carts WHERE event_id = $1 ORDER BY created_at
`

func (q *Queries) ListCartsByEvent(ctx context.Context, eventID pgtype.UUID) ([]Cart, error) {
	rows, err := q.db.Query(ctx, listCartsByEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Cart{}
	for rows.Next() {
		var i Cart
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.PlatformUserID,
			&i.PlatformHandle,
			&i.Token,
			&i.Status,
			&i.CheckoutUrl,
			&i.PaymentIntegrationID,
			&i.ExternalOrderID,
			&i.PaymentStatus,
			&i.PaidAt,
			&i.NotifyStatus,
			&i.NotifyError,
			&i.NotifiedAt,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.SessionID,
			&i.CheckoutID,
			&i.CheckoutExpiresAt,
			&i.CustomerEmail,
			&i.PaymentMethod,
			&i.CustomerName,
			&i.CustomerDocument,
			&i.CustomerPhone,
			&i.ShippingAddress,
			&i.CustomerID,
			&i.ShippingServiceID,
			&i.ShippingServiceName,
			&i.ShippingCarrier,
			&i.ShippingCostCents,
			&i.ShippingCostRealCents,
			&i.ShippingDeadlineDays,
			&i.ShippingQuotedAt,
			&i.ShippingProvider,
			&i.LastShippingQuoteOptions,
			&i.LastShippingQuoteAt,
			&i.CardBrand,
			&i.CardLastFour,
			&i.CardInstallments,
			&i.CardAuthorizationCode,
			&i.InitialSnapshotTakenAt,
			&i.InitialSubtotalCents,
			&i.ShortID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCartsWithTotalByEvent = `-- name: ListCartsWithTotalByEvent :many
SELECT
    c.id,
    c.event_id,
    c.session_id,
    c.platform_user_id,
    c.platform_handle,
    c.token,
    c.status,
    c.payment_status,
    c.created_at,
    c.expires_at,
    COALESCE(SUM((ci.quantity - ci.waitlisted_quantity) * ci.unit_price), 0)::bigint AS total_value,
    COALESCE(SUM(ci.quantity), 0)::int AS total_items,
    COALESCE(SUM(ci.quantity - ci.waitlisted_quantity), 0)::int AS available_items,
    COALESCE(SUM(ci.waitlisted_quantity), 0)::int AS waitlisted_items
FROM carts c
LEFT JOIN cart_items ci ON ci.cart_id = c.id
WHERE c.event_id = $1
GROUP BY c.id
ORDER BY c.created_at DESC
`

type ListCartsWithTotalByEventRow struct {
	ID              pgtype.UUID        `json:"id"`
	EventID         pgtype.UUID        `json:"event_id"`
	SessionID       pgtype.UUID        `json:"session_id"`
	PlatformUserID  string             `json:"platform_user_id"`
	PlatformHandle  string             `json:"platform_handle"`
	Token           string             `json:"token"`
	Status          string             `json:"status"`
	PaymentStatus   pgtype.Text        `json:"payment_status"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	TotalValue      int64              `json:"total_value"`
	TotalItems      int32              `json:"total_items"`
	AvailableItems  int32              `json:"available_items"`
	WaitlistedItems int32              `json:"waitlisted_items"`
}

// Returns carts for an event with total value and item count (available vs waitlisted)
func (q *Queries) ListCartsWithTotalByEvent(ctx context.Context, eventID pgtype.UUID) ([]ListCartsWithTotalByEventRow, error) {
	rows, err := q.db.Query(ctx, listCartsWithTotalByEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCartsWithTotalByEventRow{}
	for rows.Next() {
		var i ListCartsWithTotalByEventRow
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.SessionID,
			&i.PlatformUserID,
			&i.PlatformHandle,
			&i.Token,
			&i.Status,
			&i.PaymentStatus,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.TotalValue,
			&i.TotalItems,
			&i.AvailableItems,
			&i.WaitlistedItems,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredCarts = `-- name: ListExpiredCarts :many
SELECT c.id, c.event_id, c.platform_user_id, c.platform_handle, c.token, c.status, c.checkout_url, c.payment_integration_id, c.external_order_id, c.payment_status, c.paid_at, c.notify_status, c.notify_error, c.notified_at, c.created_at, c.expires_at, c.session_id, c.checkout_id, c.checkout_expires_at, c.customer_email, c.payment_method, c.customer_name, c.customer_document, c.customer_phone, c.shipping_address, c.customer_id, c.shipping_service_id, c.shipping_service_name, c.shipping_carrier, c.shipping_cost_cents, c.shipping_cost_real_cents, c.shipping_deadline_days, c.shipping_quoted_at, c.shipping_provider, c.last_shipping_quote_options, c.last_shipping_quote_at, c.card_brand, c.card_last_four, c.card_installments, c.card_authorization_code, c.initial_snapshot_taken_at, c.initial_subtotal_cents, c.short_id, le.store_id
FROM carts c
JOIN live_events le ON le.id = c.event_id
WHERE c.status = 'active' AND c.expires_at IS NOT NULL AND c.expires_at < now()
`

type ListExpiredCartsRow struct {
	ID                       pgtype.UUID        `json:"id"`
	EventID                  pgtype.UUID        `json:"event_id"`
	PlatformUserID           string             `json:"platform_user_id"`
	PlatformHandle           string             `json:"platform_handle"`
	Token                    string             `json:"token"`
	Status                   string             `json:"status"`
	CheckoutUrl              pgtype.Text        `json:"checkout_url"`
	PaymentIntegrationID     pgtype.UUID        `json:"payment_integration_id"`
	ExternalOrderID          pgtype.Text        `json:"external_order_id"`
	PaymentStatus            pgtype.Text        `json:"payment_status"`
	PaidAt                   pgtype.Timestamptz `json:"paid_at"`
	NotifyStatus             pgtype.Text        `json:"notify_status"`
	NotifyError              pgtype.Text        `json:"notify_error"`
	NotifiedAt               pgtype.Timestamptz `json:"notified_at"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	ExpiresAt                pgtype.Timestamptz `json:"expires_at"`
	SessionID                pgtype.UUID        `json:"session_id"`
	CheckoutID               pgtype.Text        `json:"checkout_id"`
	CheckoutExpiresAt        pgtype.Timestamptz `json:"checkout_expires_at"`
	CustomerEmail            pgtype.Text        `json:"customer_email"`
	PaymentMethod            pgtype.Text        `json:"payment_method"`
	CustomerName             pgtype.Text        `json:"customer_name"`
	CustomerDocument         pgtype.Text        `json:"customer_document"`
	CustomerPhone            pgtype.Text        `json:"customer_phone"`
	ShippingAddress          json.RawMessage    `json:"shipping_address"`
	CustomerID               pgtype.UUID        `json:"customer_id"`
	ShippingServiceID        pgtype.Text        `json:"shipping_service_id"`
	ShippingServiceName      pgtype.Text        `json:"shipping_service_name"`
	ShippingCarrier          pgtype.Text        `json:"shipping_carrier"`
	ShippingCostCents        pgtype.Int8        `json:"shipping_cost_cents"`
	ShippingCostRealCents    pgtype.Int8        `json:"shipping_cost_real_cents"`
	ShippingDeadlineDays     pgtype.Int4        `json:"shipping_deadline_days"`
	ShippingQuotedAt         pgtype.Timestamptz `json:"shipping_quoted_at"`
	ShippingProvider         pgtype.Text        `json:"shipping_provider"`
	LastShippingQuoteOptions json.RawMessage    `json:"last_shipping_quote_options"`
	LastShippingQuoteAt      pgtype.Timestamptz `json:"last_shipping_quote_at"`
	CardBrand                pgtype.Text        `json:"card_brand"`
	CardLastFour             pgtype.Text        `json:"card_last_four"`
	CardInstallments         pgtype.Int4        `json:"card_installments"`
	CardAuthorizationCode    pgtype.Text        `json:"card_authorization_code"`
	InitialSnapshotTakenAt   pgtype.Timestamptz `json:"initial_snapshot_taken_at"`
	InitialSubtotalCents     pgtype.Int8        `json:"initial_subtotal_cents"`
	ShortID                  int32              `json:"short_id"`
	StoreID                  pgtype.UUID        `json:"store_id"`
}

// Returns carts that have expired (active + past expires_at), with store_id from event
func (q *Queries) ListExpiredCarts(ctx context.Context) ([]ListExpiredCartsRow, error) {
	rows, err := q.db.Query(ctx, listExpiredCarts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExpiredCartsRow{}
	for rows.Next() {
		var i ListExpiredCartsRow
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.PlatformUserID,
			&i.PlatformHandle,
			&i.Token,
			&i.Status,
			&i.CheckoutUrl,
			&i.PaymentIntegrationID,
			&i.ExternalOrderID,
			&i.PaymentStatus,
			&i.PaidAt,
			&i.NotifyStatus,
			&i.NotifyError,
			&i.NotifiedAt,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.SessionID,
			&i.CheckoutID,
			&i.CheckoutExpiresAt,
			&i.CustomerEmail,
			&i.PaymentMethod,
			&i.CustomerName,
			&i.CustomerDocument,
			&i.CustomerPhone,
			&i.ShippingAddress,
			&i.CustomerID,
			&i.ShippingServiceID,
			&i.ShippingServiceName,
			&i.ShippingCarrier,
			&i.ShippingCostCents,
			&i.ShippingCostRealCents,
			&i.ShippingDeadlineDays,
			&i.ShippingQuotedAt,
			&i.ShippingProvider,
			&i.LastShippingQuoteOptions,
			&i.LastShippingQuoteAt,
			&i.CardBrand,
			&i.CardLastFour,
			&i.CardInstallments,
			&i.CardAuthorizationCode,
			&i.InitialSnapshotTakenAt,
			&i.InitialSubtotalCents,
			&i.ShortID,
			&i.StoreID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredCartsByEventAndProduct = `-- name: ListExpiredCartsByEventAndProduct :many
SELECT DISTINCT c.id, c.event_id, c.platform_user_id, c.platform_handle, c.token, c.status, c.checkout_url, c.payment_integration_id, c.external_order_id, c.payment_status, c.paid_at, c.notify_status, c.notify_error, c.notified_at, c.created_at, c.expires_at, c.session_id, c.checkout_id, c.checkout_expires_at, c.customer_email, c.payment_method, c.customer_name, c.customer_document, c.customer_phone, c.shipping_address, c.customer_id, c.shipping_service_id, c.shipping_service_name, c.shipping_carrier, c.shipping_cost_cents, c.shipping_cost_real_cents, c.shipping_deadline_days, c.shipping_quoted_at, c.shipping_provider, c.last_shipping_quote_options, c.last_shipping_quote_at, c.card_brand, c.card_last_four, c.card_installments, c.card_authorization_code, c.initial_snapshot_taken_at, c.initial_subtotal_cents, c.short_id, le.store_id
FROM carts c
JOIN live_events le ON le.id = c.event_id
JOIN cart_items ci ON ci.cart_id = c.id
WHERE c.event_id = $1
  AND c.status = 'active'
  AND c.expires_at IS NOT NULL
  AND c.expires_at < now()
  AND ci.product_id = $2
  AND ci.quantity > ci.waitlisted_quantity
`

type ListExpiredCartsByEventAndProductParams struct {
	EventID   pgtype.UUID `json:"event_id"`
	ProductID pgtype.UUID `json:"product_id"`
}

type ListExpiredCartsByEventAndProductRow struct {
	ID                       pgtype.UUID        `json:"id"`
	EventID                  pgtype.UUID        `json:"event_id"`
	PlatformUserID           string             `json:"platform_user_id"`
	PlatformHandle           string             `json:"platform_handle"`
	Token                    string             `json:"token"`
	Status                   string             `json:"status"`
	CheckoutUrl              pgtype.Text        `json:"checkout_url"`
	PaymentIntegrationID     pgtype.UUID        `json:"payment_integration_id"`
	ExternalOrderID          pgtype.Text        `json:"external_order_id"`
	PaymentStatus            pgtype.Text        `json:"payment_status"`
	PaidAt                   pgtype.Timestamptz `json:"paid_at"`
	NotifyStatus             pgtype.Text        `json:"notify_status"`
	NotifyError              pgtype.Text        `json:"notify_error"`
	NotifiedAt               pgtype.Timestamptz `json:"notified_at"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	ExpiresAt                pgtype.Timestamptz `json:"expires_at"`
	SessionID                pgtype.UUID        `json:"session_id"`
	CheckoutID               pgtype.Text        `json:"checkout_id"`
	CheckoutExpiresAt        pgtype.Timestamptz `json:"checkout_expires_at"`
	CustomerEmail            pgtype.Text        `json:"customer_email"`
	PaymentMethod            pgtype.Text        `json:"payment_method"`
	CustomerName             pgtype.Text        `json:"customer_name"`
	CustomerDocument         pgtype.Text        `json:"customer_document"`
	CustomerPhone            pgtype.Text        `json:"customer_phone"`
	ShippingAddress          json.RawMessage    `json:"shipping_address"`
	CustomerID               pgtype.UUID        `json:"customer_id"`
	ShippingServiceID        pgtype.Text        `json:"shipping_service_id"`
	ShippingServiceName      pgtype.Text        `json:"shipping_service_name"`
	ShippingCarrier          pgtype.Text        `json:"shipping_carrier"`
	ShippingCostCents        pgtype.Int8        `json:"shipping_cost_cents"`
	ShippingCostRealCents    pgtype.Int8        `json:"shipping_cost_real_cents"`
	ShippingDeadlineDays     pgtype.Int4        `json:"shipping_deadline_days"`
	ShippingQuotedAt         pgtype.Timestamptz `json:"shipping_quoted_at"`
	ShippingProvider         pgtype.Text        `json:"shipping_provider"`
	LastShippingQuoteOptions json.RawMessage    `json:"last_shipping_quote_options"`
	LastShippingQuoteAt      pgtype.Timestamptz `json:"last_shipping_quote_at"`
	CardBrand                pgtype.Text        `json:"card_brand"`
	CardLastFour             pgtype.Text        `json:"card_last_four"`
	CardInstallments         pgtype.Int4        `json:"card_installments"`
	CardAuthorizationCode    pgtype.Text        `json:"card_authorization_code"`
	InitialSnapshotTakenAt   pgtype.Timestamptz `json:"initial_snapshot_taken_at"`
	InitialSubtotalCents     pgtype.Int8        `json:"initial_subtotal_cents"`
	ShortID                  int32              `json:"short_id"`
	StoreID                  pgtype.UUID        `json:"store_id"`
}

// Returns expired carts for a specific event that contain a specific product (with available qty)
func (q *Queries) ListExpiredCartsByEventAndProduct(ctx context.Context, arg ListExpiredCartsByEventAndProductParams) ([]ListExpiredCartsByEventAndProductRow, error) {
	rows, err := q.db.Query(ctx, listExpiredCartsByEventAndProduct, arg.EventID, arg.ProductID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExpiredCartsByEventAndProductRow{}
	for rows.Next() {
		var i ListExpiredCartsByEventAndProductRow
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.PlatformUserID,
			&i.PlatformHandle,
			&i.Token,
			&i.Status,
			&i.CheckoutUrl,
			&i.PaymentIntegrationID,
			&i.ExternalOrderID,
			&i.PaymentStatus,
			&i.PaidAt,
			&i.NotifyStatus,
			&i.NotifyError,
			&i.NotifiedAt,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.SessionID,
			&i.CheckoutID,
			&i.CheckoutExpiresAt,
			&i.CustomerEmail,
			&i.PaymentMethod,
			&i.CustomerName,
			&i.CustomerDocument,
			&i.CustomerPhone,
			&i.ShippingAddress,
			&i.CustomerID,
			&i.ShippingServiceID,
			&i.ShippingServiceName,
			&i.ShippingCarrier,
			&i.ShippingCostCents,
			&i.ShippingCostRealCents,
			&i.ShippingDeadlineDays,
			&i.ShippingQuotedAt,
			&i.ShippingProvider,
			&i.LastShippingQuoteOptions,
			&i.LastShippingQuoteAt,
			&i.CardBrand,
			&i.CardLastFour,
			&i.CardInstallments,
			&i.CardAuthorizationCode,
			&i.InitialSnapshotTakenAt,
			&i.InitialSubtotalCents,
			&i.ShortID,
			&i.StoreID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNonWaitlistedCartItems = `-- name: ListNonWaitlistedCartItems :many
SELECT ci.id, ci.cart_id, ci.product_id,
       (ci.quantity - ci.waitlisted_quantity) AS quantity,
       ci.unit_price, ci.waitlisted_quantity,
       p.name AS product_name, p.external_id AS product_external_id,
       p.keyword AS product_keyword, p.image_url AS product_image_url
FROM cart_items ci
JOIN products p ON p.id = ci.product_id
WHERE ci.cart_id = $1 AND ci.quantity > ci.waitlisted_quantity
`

type ListNonWaitlistedCartItemsRow struct {
	ID                 pgtype.UUID `json:"id"`
	CartID             pgtype.UUID `json:"cart_id"`
	ProductID          pgtype.UUID `json:"product_id"`
	Quantity           int32       `json:"quantity"`
	UnitPrice          pgtype.Int8 `json:"unit_price"`
	WaitlistedQuantity int32       `json:"waitlisted_quantity"`
	ProductName        string      `json:"product_name"`
	ProductExternalID  pgtype.Text `json:"product_external_id"`
	ProductKeyword     string      `json:"product_keyword"`
	ProductImageUrl    pgtype.Text `json:"product_image_url"`
}

// Returns cart items that have available (non-waitlisted) quantity, with product external_id for ERP sync
// Returns available_quantity = quantity - waitlisted_quantity
func (q *Queries) ListNonWaitlistedCartItems(ctx context.Context, cartID pgtype.UUID) ([]ListNonWaitlistedCartItemsRow, error) {
	rows, err := q.db.Query(ctx, listNonWaitlistedCartItems, cartID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNonWaitlistedCartItemsRow{}
	for rows.Next() {
		var i ListNonWaitlistedCartItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.CartID,
			&i.ProductID,
			&i.Quantity,
			&i.UnitPrice,
			&i.WaitlistedQuantity,
			&i.ProductName,
			&i.ProductExternalID,
			&i.ProductKeyword,
			&i.ProductImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsByEvent = `-- name: ListProductsByEvent :many
SELECT
    p.id,
    p.name,
    p.image_url,
    p.keyword,
    COALESCE(SUM(ci.quantity), 0)::int AS total_quantity,
    COALESCE(SUM(ci.quantity * ci.unit_price), 0)::bigint AS total_revenue
FROM cart_items ci
JOIN carts c ON c.id = ci.cart_id
JOIN products p ON p.id = ci.product_id
WHERE c.event_id = $1 AND c.status != 'expired'
GROUP BY p.id, p.name, p.image_url, p.keyword
ORDER BY total_quantity DESC
`

type ListProductsByEventRow struct {
	ID            pgtype.UUID `json:"id"`
	Name          string      `json:"name"`
	ImageUrl      pgtype.Text `json:"image_url"`
	Keyword       string      `json:"keyword"`
	TotalQuantity int32       `json:"total_quantity"`
	TotalRevenue  int64       `json:"total_revenue"`
}

// Returns products sold in an event with quantity and revenue
func (q *Queries) ListProductsByEvent(ctx context.Context, eventID pgtype.UUID) ([]ListProductsByEventRow, error) {
	rows, err := q.db.Query(ctx, listProductsByEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProductsByEventRow{}
	for rows.Next() {
		var i ListProductsByEventRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ImageUrl,
			&i.Keyword,
			&i.TotalQuantity,
			&i.TotalRevenue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCartCheckoutInfo = `-- name: UpdateCartCheckoutInfo :one
UPDATE carts
SET checkout_url = $2, checkout_id = $3, checkout_expires_at = $4
WHERE id = $1
RETURNING id, event_id, platform_user_id, platform_handle, token, status, checkout_url, payment_integration_id, external_order_id, payment_status, paid_at, notify_status, notify_error, notified_at, created_at, expires_at, session_id, checkout_id, checkout_expires_at, customer_email, payment_method, customer_name, customer_document, customer_phone, shipping_address, customer_id, shipping_service_id, shipping_service_name, shipping_carrier, shipping_cost_cents, shipping_cost_real_cents, shipping_deadline_days, shipping_quoted_at, shipping_provider, last_shipping_quote_options, last_shipping_quote_at, card_brand, card_last_four, card_installments, card_authorization_code, initial_snapshot_taken_at, initial_subtotal_cents, short_id
`

type UpdateCartCheckoutInfoParams struct {
	ID                pgtype.UUID        `json:"id"`
	CheckoutUrl       pgtype.Text        `json:"checkout_url"`
	CheckoutID        pgtype.Text        `json:"checkout_id"`
	CheckoutExpiresAt pgtype.Timestamptz `json:"checkout_expires_at"`
}

// Updates checkout URL and ID after generating payment link
func (q *Queries) UpdateCartCheckoutInfo(ctx context.Context, arg UpdateCartCheckoutInfoParams) (Cart, error) {
	row := q.db.QueryRow(ctx, updateCartCheckoutInfo,
		arg.ID,
		arg.CheckoutUrl,
		arg.CheckoutID,
		arg.CheckoutExpiresAt,
	)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.PlatformUserID,
		&i.PlatformHandle,
		&i.Token,
		&i.Status,
		&i.CheckoutUrl,
		&i.PaymentIntegrationID,
		&i.ExternalOrderID,
		&i.PaymentStatus,
		&i.PaidAt,
		&i.NotifyStatus,
		&i.NotifyError,
		&i.NotifiedAt,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.SessionID,
		&i.CheckoutID,
		&i.CheckoutExpiresAt,
		&i.CustomerEmail,
		&i.PaymentMethod,
		&i.CustomerName,
		&i.CustomerDocument,
		&i.CustomerPhone,
		&i.ShippingAddress,
		&i.CustomerID,
		&i.ShippingServiceID,
		&i.ShippingServiceName,
		&i.ShippingCarrier,
		&i.ShippingCostCents,
		&i.ShippingCostRealCents,
		&i.ShippingDeadlineDays,
		&i.ShippingQuotedAt,
		&i.ShippingProvider,
		&i.LastShippingQuoteOptions,
		&i.LastShippingQuoteAt,
		&i.CardBrand,
		&i.CardLastFour,
		&i.CardInstallments,
		&i.CardAuthorizationCode,
		&i.InitialSnapshotTakenAt,
		&i.InitialSubtotalCents,
		&i.ShortID,
	)
	return i, err
}

const updateCartCustomerCheckout = `-- name: UpdateCartCustomerCheckout :one
UPDATE carts
SET customer_email    = $2,
    customer_name     = $3,
    customer_document = $4,
    customer_phone    = $5,
    shipping_address  = $6
WHERE id = $1
RETURNING id, event_id, platform_user_id, platform_handle, token, status, checkout_url, payment_integration_id, external_order_id, payment_status, paid_at, notify_status, notify_error, notified_at, created_at, expires_at, session_id, checkout_id, checkout_expires_at, customer_email, payment_method, customer_name, customer_document, customer_phone, shipping_address, customer_id, shipping_service_id, shipping_service_name, shipping_carrier, shipping_cost_cents, shipping_cost_real_cents, shipping_deadline_days, shipping_quoted_at, shipping_provider, last_shipping_quote_options, last_shipping_quote_at, card_brand, card_last_four, card_installments, card_authorization_code, initial_snapshot_taken_at, initial_subtotal_cents, short_id
`

type UpdateCartCustomerCheckoutParams struct {
	ID               pgtype.UUID     `json:"id"`
	CustomerEmail    pgtype.Text     `json:"customer_email"`
	CustomerName     pgtype.Text     `json:"customer_name"`
	CustomerDocument pgtype.Text     `json:"customer_document"`
	CustomerPhone    pgtype.Text     `json:"customer_phone"`
	ShippingAddress  json.RawMessage `json:"shipping_address"`
}

// Persists full customer + shipping data entered in the checkout form.
// Called right before a card/pix payment request so the webhook handler
// (and ERP order creation on paid) has complete info regardless of provider.
func (q *Queries) UpdateCartCustomerCheckout(ctx context.Context, arg UpdateCartCustomerCheckoutParams) (Cart, error) {
	row := q.db.QueryRow(ctx, updateCartCustomerCheckout,
		arg.ID,
		arg.CustomerEmail,
		arg.CustomerName,
		arg.CustomerDocument,
		arg.CustomerPhone,
		arg.ShippingAddress,
	)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.PlatformUserID,
		&i.PlatformHandle,
		&i.Token,
		&i.Status,
		&i.CheckoutUrl,
		&i.PaymentIntegrationID,
		&i.ExternalOrderID,
		&i.PaymentStatus,
		&i.PaidAt,
		&i.NotifyStatus,
		&i.NotifyError,
		&i.NotifiedAt,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.SessionID,
		&i.CheckoutID,
		&i.CheckoutExpiresAt,
		&i.CustomerEmail,
		&i.PaymentMethod,
		&i.CustomerName,
		&i.CustomerDocument,
		&i.CustomerPhone,
		&i.ShippingAddress,
		&i.CustomerID,
		&i.ShippingServiceID,
		&i.ShippingServiceName,
		&i.ShippingCarrier,
		&i.ShippingCostCents,
		&i.ShippingCostRealCents,
		&i.ShippingDeadlineDays,
		&i.ShippingQuotedAt,
		&i.ShippingProvider,
		&i.LastShippingQuoteOptions,
		&i.LastShippingQuoteAt,
		&i.CardBrand,
		&i.CardLastFour,
		&i.CardInstallments,
		&i.CardAuthorizationCode,
		&i.InitialSnapshotTakenAt,
		&i.InitialSubtotalCents,
		&i.ShortID,
	)
	return i, err
}

const updateCartCustomerEmail = `-- name: UpdateCartCustomerEmail :one
UPDATE carts
SET customer_email = $2
WHERE token = $1
RETURNING id, event_id, platform_user_id, platform_handle, token, status, checkout_url, payment_integration_id, external_order_id, payment_status, paid_at, notify_status, notify_error, notified_at, created_at, expires_at, session_id, checkout_id, checkout_expires_at, customer_email, payment_method, customer_name, customer_document, customer_phone, shipping_address, customer_id, shipping_service_id, shipping_service_name, shipping_carrier, shipping_cost_cents, shipping_cost_real_cents, shipping_deadline_days, shipping_quoted_at, shipping_provider, last_shipping_quote_options, last_shipping_quote_at, card_brand, card_last_four, card_installments, card_authorization_code, initial_snapshot_taken_at, initial_subtotal_cents, short_id
`

type UpdateCartCustomerEmailParams struct {
	Token         string      `json:"token"`
	CustomerEmail pgtype.Text `json:"customer_email"`
}

func (q *Queries) UpdateCartCustomerEmail(ctx context.Context, arg UpdateCartCustomerEmailParams) (Cart, error) {
	row := q.db.QueryRow(ctx, updateCartCustomerEmail, arg.Token, arg.CustomerEmail)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.PlatformUserID,
		&i.PlatformHandle,
		&i.Token,
		&i.Status,
		&i.CheckoutUrl,
		&i.PaymentIntegrationID,
		&i.ExternalOrderID,
		&i.PaymentStatus,
		&i.PaidAt,
		&i.NotifyStatus,
		&i.NotifyError,
		&i.NotifiedAt,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.SessionID,
		&i.CheckoutID,
		&i.CheckoutExpiresAt,
		&i.CustomerEmail,
		&i.PaymentMethod,
		&i.CustomerName,
		&i.CustomerDocument,
		&i.CustomerPhone,
		&i.ShippingAddress,
		&i.CustomerID,
		&i.ShippingServiceID,
		&i.ShippingServiceName,
		&i.ShippingCarrier,
		&i.ShippingCostCents,
		&i.ShippingCostRealCents,
		&i.ShippingDeadlineDays,
		&i.ShippingQuotedAt,
		&i.ShippingProvider,
		&i.LastShippingQuoteOptions,
		&i.LastShippingQuoteAt,
		&i.CardBrand,
		&i.CardLastFour,
		&i.CardInstallments,
		&i.CardAuthorizationCode,
		&i.InitialSnapshotTakenAt,
		&i.InitialSubtotalCents,
		&i.ShortID,
	)
	return i, err
}

const updateCartCustomerID = `-- name: UpdateCartCustomerID :exec
UPDATE carts SET customer_id = $2 WHERE id = $1
`

type UpdateCartCustomerIDParams struct {
	ID         pgtype.UUID `json:"id"`
	CustomerID pgtype.UUID `json:"customer_id"`
}

func (q *Queries) UpdateCartCustomerID(ctx context.Context, arg UpdateCartCustomerIDParams) error {
	_, err := q.db.Exec(ctx, updateCartCustomerID, arg.ID, arg.CustomerID)
	return err
}

const updateCartExternalOrderID = `-- name: UpdateCartExternalOrderID :exec

UPDATE carts SET external_order_id = $2 WHERE id = $1
`

type UpdateCartExternalOrderIDParams struct {
	ID              pgtype.UUID `json:"id"`
	ExternalOrderID pgtype.Text `json:"external_order_id"`
}

// =============================================================================
// ERP SYNC & EXPIRATION
// =============================================================================
func (q *Queries) UpdateCartExternalOrderID(ctx context.Context, arg UpdateCartExternalOrderIDParams) error {
	_, err := q.db.Exec(ctx, updateCartExternalOrderID, arg.ID, arg.ExternalOrderID)
	return err
}

const updateCartItem = `-- name: UpdateCartItem :one
UPDATE cart_items
SET quantity = $2
WHERE id = $1
RETURNING id, cart_id, product_id, quantity, unit_price, waitlisted_quantity
`

type UpdateCartItemParams struct {
	ID       pgtype.UUID `json:"id"`
	Quantity pgtype.Int4 `json:"quantity"`
}

func (q *Queries) UpdateCartItem(ctx context.Context, arg UpdateCartItemParams) (CartItem, error) {
	row := q.db.QueryRow(ctx, updateCartItem, arg.ID, arg.Quantity)
	var i CartItem
	err := row.Scan(
		&i.ID,
		&i.CartID,
		&i.ProductID,
		&i.Quantity,
		&i.UnitPrice,
		&i.WaitlistedQuantity,
	)
	return i, err
}

const updateCartItemWaitlistedQuantity = `-- name: UpdateCartItemWaitlistedQuantity :exec
UPDATE cart_items SET waitlisted_quantity = $3 WHERE cart_id = $1 AND product_id = $2
`

type UpdateCartItemWaitlistedQuantityParams struct {
	CartID             pgtype.UUID `json:"cart_id"`
	ProductID          pgtype.UUID `json:"product_id"`
	WaitlistedQuantity int32       `json:"waitlisted_quantity"`
}

func (q *Queries) UpdateCartItemWaitlistedQuantity(ctx context.Context, arg UpdateCartItemWaitlistedQuantityParams) error {
	_, err := q.db.Exec(ctx, updateCartItemWaitlistedQuantity, arg.CartID, arg.ProductID, arg.WaitlistedQuantity)
	return err
}

const updateCartNotifyStatus = `-- name: UpdateCartNotifyStatus :one
UPDATE carts
SET notify_status = $2, notify_error = $3, notified_at = $4
WHERE id = $1
RETURNING id, event_id, platform_user_id, platform_handle, token, status, checkout_url, payment_integration_id, external_order_id, payment_status, paid_at, notify_status, notify_error, notified_at, created_at, expires_at, session_id, checkout_id, checkout_expires_at, customer_email, payment_method, customer_name, customer_document, customer_phone, shipping_address, customer_id, shipping_service_id, shipping_service_name, shipping_carrier, shipping_cost_cents, shipping_cost_real_cents, shipping_deadline_days, shipping_quoted_at, shipping_provider, last_shipping_quote_options, last_shipping_quote_at, card_brand, card_last_four, card_installments, card_authorization_code, initial_snapshot_taken_at, initial_subtotal_cents, short_id
`

type UpdateCartNotifyStatusParams struct {
	ID           pgtype.UUID        `json:"id"`
	NotifyStatus pgtype.Text        `json:"notify_status"`
	NotifyError  pgtype.Text        `json:"notify_error"`
	NotifiedAt   pgtype.Timestamptz `json:"notified_at"`
}

func (q *Queries) UpdateCartNotifyStatus(ctx context.Context, arg UpdateCartNotifyStatusParams) (Cart, error) {
	row := q.db.QueryRow(ctx, updateCartNotifyStatus,
		arg.ID,
		arg.NotifyStatus,
		arg.NotifyError,
		arg.NotifiedAt,
	)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.PlatformUserID,
		&i.PlatformHandle,
		&i.Token,
		&i.Status,
		&i.CheckoutUrl,
		&i.PaymentIntegrationID,
		&i.ExternalOrderID,
		&i.PaymentStatus,
		&i.PaidAt,
		&i.NotifyStatus,
		&i.NotifyError,
		&i.NotifiedAt,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.SessionID,
		&i.CheckoutID,
		&i.CheckoutExpiresAt,
		&i.CustomerEmail,
		&i.PaymentMethod,
		&i.CustomerName,
		&i.CustomerDocument,
		&i.CustomerPhone,
		&i.ShippingAddress,
		&i.CustomerID,
		&i.ShippingServiceID,
		&i.ShippingServiceName,
		&i.ShippingCarrier,
		&i.ShippingCostCents,
		&i.ShippingCostRealCents,
		&i.ShippingDeadlineDays,
		&i.ShippingQuotedAt,
		&i.ShippingProvider,
		&i.LastShippingQuoteOptions,
		&i.LastShippingQuoteAt,
		&i.CardBrand,
		&i.CardLastFour,
		&i.CardInstallments,
		&i.CardAuthorizationCode,
		&i.InitialSnapshotTakenAt,
		&i.InitialSubtotalCents,
		&i.ShortID,
	)
	return i, err
}

const updateCartPayment = `-- name: UpdateCartPayment :one
UPDATE carts
SET payment_status = $2, checkout_id = $3, paid_at = $4, payment_method = $5
WHERE id = $1
RETURNING id, event_id, platform_user_id, platform_handle, token, status, checkout_url, payment_integration_id, external_order_id, payment_status, paid_at, notify_status, notify_error, notified_at, created_at, expires_at, session_id, checkout_id, checkout_expires_at, customer_email, payment_method, customer_name, customer_document, customer_phone, shipping_address, customer_id, shipping_service_id, shipping_service_name, shipping_carrier, shipping_cost_cents, shipping_cost_real_cents, shipping_deadline_days, shipping_quoted_at, shipping_provider, last_shipping_quote_options, last_shipping_quote_at, card_brand, card_last_four, card_installments, card_authorization_code, initial_snapshot_taken_at, initial_subtotal_cents, short_id
`

type UpdateCartPaymentParams struct {
	ID            pgtype.UUID        `json:"id"`
	PaymentStatus pgtype.Text        `json:"payment_status"`
	CheckoutID    pgtype.Text        `json:"checkout_id"`
	PaidAt        pgtype.Timestamptz `json:"paid_at"`
	PaymentMethod pgtype.Text        `json:"payment_method"`
}

// $3 = payment-provider ID (MP/Pagar.me). Goes to checkout_id, not
// external_order_id — the latter is reserved for the ERP (Tiny) order ID
// and is the idempotency key for finalizeCartERPOrder.
func (q *Queries) UpdateCartPayment(ctx context.Context, arg UpdateCartPaymentParams) (Cart, error) {
	row := q.db.QueryRow(ctx, updateCartPayment,
		arg.ID,
		arg.PaymentStatus,
		arg.CheckoutID,
		arg.PaidAt,
		arg.PaymentMethod,
	)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.PlatformUserID,
		&i.PlatformHandle,
		&i.Token,
		&i.Status,
		&i.CheckoutUrl,
		&i.PaymentIntegrationID,
		&i.ExternalOrderID,
		&i.PaymentStatus,
		&i.PaidAt,
		&i.NotifyStatus,
		&i.NotifyError,
		&i.NotifiedAt,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.SessionID,
		&i.CheckoutID,
		&i.CheckoutExpiresAt,
		&i.CustomerEmail,
		&i.PaymentMethod,
		&i.CustomerName,
		&i.CustomerDocument,
		&i.CustomerPhone,
		&i.ShippingAddress,
		&i.CustomerID,
		&i.ShippingServiceID,
		&i.ShippingServiceName,
		&i.ShippingCarrier,
		&i.ShippingCostCents,
		&i.ShippingCostRealCents,
		&i.ShippingDeadlineDays,
		&i.ShippingQuotedAt,
		&i.ShippingProvider,
		&i.LastShippingQuoteOptions,
		&i.LastShippingQuoteAt,
		&i.CardBrand,
		&i.CardLastFour,
		&i.CardInstallments,
		&i.CardAuthorizationCode,
		&i.InitialSnapshotTakenAt,
		&i.InitialSubtotalCents,
		&i.ShortID,
	)
	return i, err
}

const updateCartPaymentByCheckoutID = `-- name: UpdateCartPaymentByCheckoutID :one
UPDATE carts
SET payment_status = $2, paid_at = $3
WHERE checkout_id = $1
RETURNING id, event_id, platform_user_id, platform_handle, token, status, checkout_url, payment_integration_id, external_order_id, payment_status, paid_at, notify_status, notify_error, notified_at, created_at, expires_at, session_id, checkout_id, checkout_expires_at, customer_email, payment_method, customer_name, customer_document, customer_phone, shipping_address, customer_id, shipping_service_id, shipping_service_name, shipping_carrier, shipping_cost_cents, shipping_cost_real_cents, shipping_deadline_days, shipping_quoted_at, shipping_provider, last_shipping_quote_options, last_shipping_quote_at, card_brand, card_last_four, card_installments, card_authorization_code, initial_snapshot_taken_at, initial_subtotal_cents, short_id
`

type UpdateCartPaymentByCheckoutIDParams struct {
	CheckoutID    pgtype.Text        `json:"checkout_id"`
	PaymentStatus pgtype.Text        `json:"payment_status"`
	PaidAt        pgtype.Timestamptz `json:"paid_at"`
}

// Updates payment status when webhook confirms payment
func (q *Queries) UpdateCartPaymentByCheckoutID(ctx context.Context, arg UpdateCartPaymentByCheckoutIDParams) (Cart, error) {
	row := q.db.QueryRow(ctx, updateCartPaymentByCheckoutID, arg.CheckoutID, arg.PaymentStatus, arg.PaidAt)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.PlatformUserID,
		&i.PlatformHandle,
		&i.Token,
		&i.Status,
		&i.CheckoutUrl,
		&i.PaymentIntegrationID,
		&i.ExternalOrderID,
		&i.PaymentStatus,
		&i.PaidAt,
		&i.NotifyStatus,
		&i.NotifyError,
		&i.NotifiedAt,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.SessionID,
		&i.CheckoutID,
		&i.CheckoutExpiresAt,
		&i.CustomerEmail,
		&i.PaymentMethod,
		&i.CustomerName,
		&i.CustomerDocument,
		&i.CustomerPhone,
		&i.ShippingAddress,
		&i.CustomerID,
		&i.ShippingServiceID,
		&i.ShippingServiceName,
		&i.ShippingCarrier,
		&i.ShippingCostCents,
		&i.ShippingCostRealCents,
		&i.ShippingDeadlineDays,
		&i.ShippingQuotedAt,
		&i.ShippingProvider,
		&i.LastShippingQuoteOptions,
		&i.LastShippingQuoteAt,
		&i.CardBrand,
		&i.CardLastFour,
		&i.CardInstallments,
		&i.CardAuthorizationCode,
		&i.InitialSnapshotTakenAt,
		&i.InitialSubtotalCents,
		&i.ShortID,
	)
	return i, err
}

const updateCartPaymentStatus = `-- name: UpdateCartPaymentStatus :one
UPDATE carts
SET payment_status = $2, checkout_id = $3, paid_at = $4
WHERE id = $1
RETURNING id, event_id, platform_user_id, platform_handle, token, status, checkout_url, payment_integration_id, external_order_id, payment_status, paid_at, notify_status, notify_error, notified_at, created_at, expires_at, session_id, checkout_id, checkout_expires_at, customer_email, payment_method, customer_name, customer_document, customer_phone, shipping_address, customer_id, shipping_service_id, shipping_service_name, shipping_carrier, shipping_cost_cents, shipping_cost_real_cents, shipping_deadline_days, shipping_quoted_at, shipping_provider, last_shipping_quote_options, last_shipping_quote_at, card_brand, card_last_four, card_installments, card_authorization_code, initial_snapshot_taken_at, initial_subtotal_cents, short_id
`

type UpdateCartPaymentStatusParams struct {
	ID            pgtype.UUID        `json:"id"`
	PaymentStatus pgtype.Text        `json:"payment_status"`
	CheckoutID    pgtype.Text        `json:"checkout_id"`
	PaidAt        pgtype.Timestamptz `json:"paid_at"`
}

// Updates payment status directly by cart ID (for transparent checkout)
// Uses checkout_id to store the payment ID from the provider
func (q *Queries) UpdateCartPaymentStatus(ctx context.Context, arg UpdateCartPaymentStatusParams) (Cart, error) {
	row := q.db.QueryRow(ctx, updateCartPaymentStatus,
		arg.ID,
		arg.PaymentStatus,
		arg.CheckoutID,
		arg.PaidAt,
	)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.PlatformUserID,
		&i.PlatformHandle,
		&i.Token,
		&i.Status,
		&i.CheckoutUrl,
		&i.PaymentIntegrationID,
		&i.ExternalOrderID,
		&i.PaymentStatus,
		&i.PaidAt,
		&i.NotifyStatus,
		&i.NotifyError,
		&i.NotifiedAt,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.SessionID,
		&i.CheckoutID,
		&i.CheckoutExpiresAt,
		&i.CustomerEmail,
		&i.PaymentMethod,
		&i.CustomerName,
		&i.CustomerDocument,
		&i.CustomerPhone,
		&i.ShippingAddress,
		&i.CustomerID,
		&i.ShippingServiceID,
		&i.ShippingServiceName,
		&i.ShippingCarrier,
		&i.ShippingCostCents,
		&i.ShippingCostRealCents,
		&i.ShippingDeadlineDays,
		&i.ShippingQuotedAt,
		&i.ShippingProvider,
		&i.LastShippingQuoteOptions,
		&i.LastShippingQuoteAt,
		&i.CardBrand,
		&i.CardLastFour,
		&i.CardInstallments,
		&i.CardAuthorizationCode,
		&i.InitialSnapshotTakenAt,
		&i.InitialSubtotalCents,
		&i.ShortID,
	)
	return i, err
}

const updateCartStatus = `-- name: UpdateCartStatus :one
UPDATE carts SET status = $2 WHERE id = $1 RETURNING id, event_id, platform_user_id, platform_handle, token, status, checkout_url, payment_integration_id, external_order_id, payment_status, paid_at, notify_status, notify_error, notified_at, created_at, expires_at, session_id, checkout_id, checkout_expires_at, customer_email, payment_method, customer_name, customer_document, customer_phone, shipping_address, customer_id, shipping_service_id, shipping_service_name, shipping_carrier, shipping_cost_cents, shipping_cost_real_cents, shipping_deadline_days, shipping_quoted_at, shipping_provider, last_shipping_quote_options, last_shipping_quote_at, card_brand, card_last_four, card_installments, card_authorization_code, initial_snapshot_taken_at, initial_subtotal_cents, short_id
`

type UpdateCartStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateCartStatus(ctx context.Context, arg UpdateCartStatusParams) (Cart, error) {
	row := q.db.QueryRow(ctx, updateCartStatus, arg.ID, arg.Status)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.PlatformUserID,
		&i.PlatformHandle,
		&i.Token,
		&i.Status,
		&i.CheckoutUrl,
		&i.PaymentIntegrationID,
		&i.ExternalOrderID,
		&i.PaymentStatus,
		&i.PaidAt,
		&i.NotifyStatus,
		&i.NotifyError,
		&i.NotifiedAt,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.SessionID,
		&i.CheckoutID,
		&i.CheckoutExpiresAt,
		&i.CustomerEmail,
		&i.PaymentMethod,
		&i.CustomerName,
		&i.CustomerDocument,
		&i.CustomerPhone,
		&i.ShippingAddress,
		&i.CustomerID,
		&i.ShippingServiceID,
		&i.ShippingServiceName,
		&i.ShippingCarrier,
		&i.ShippingCostCents,
		&i.ShippingCostRealCents,
		&i.ShippingDeadlineDays,
		&i.ShippingQuotedAt,
		&i.ShippingProvider,
		&i.LastShippingQuoteOptions,
		&i.LastShippingQuoteAt,
		&i.CardBrand,
		&i.CardLastFour,
		&i.CardInstallments,
		&i.CardAuthorizationCode,
		&i.InitialSnapshotTakenAt,
		&i.InitialSubtotalCents,
		&i.ShortID,
	)
	return i, err
}

const upsertCartItem = `-- name: UpsertCartItem :one
INSERT INTO cart_items (cart_id, product_id, quantity, unit_price, waitlisted_quantity)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (cart_id, product_id)
DO UPDATE SET quantity = cart_items.quantity + EXCLUDED.quantity,
             waitlisted_quantity = cart_items.waitlisted_quantity + EXCLUDED.waitlisted_quantity
RETURNING id, cart_id, product_id, quantity, unit_price, waitlisted_quantity
`

type UpsertCartItemParams struct {
	CartID             pgtype.UUID `json:"cart_id"`
	ProductID          pgtype.UUID `json:"product_id"`
	Quantity           pgtype.Int4 `json:"quantity"`
	UnitPrice          pgtype.Int8 `json:"unit_price"`
	WaitlistedQuantity int32       `json:"waitlisted_quantity"`
}

// Adds quantity to existing cart item or creates new one
// waitlisted_quantity is added to existing (not replaced)
func (q *Queries) UpsertCartItem(ctx context.Context, arg UpsertCartItemParams) (CartItem, error) {
	row := q.db.QueryRow(ctx, upsertCartItem,
		arg.CartID,
		arg.ProductID,
		arg.Quantity,
		arg.UnitPrice,
		arg.WaitlistedQuantity,
	)
	var i CartItem
	err := row.Scan(
		&i.ID,
		&i.CartID,
		&i.ProductID,
		&i.Quantity,
		&i.UnitPrice,
		&i.WaitlistedQuantity,
	)
	return i, err
}
