// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: catalog.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addCatalogProduct = `-- name: AddCatalogProduct :exec
INSERT INTO catalog_products (catalog_id, product_id, position)
VALUES ($1, $2, $3)
ON CONFLICT (catalog_id, product_id) DO UPDATE SET position = EXCLUDED.position
`

type AddCatalogProductParams struct {
	CatalogID pgtype.UUID `json:"catalog_id"`
	ProductID pgtype.UUID `json:"product_id"`
	Position  int32       `json:"position"`
}

func (q *Queries) AddCatalogProduct(ctx context.Context, arg AddCatalogProductParams) error {
	_, err := q.db.Exec(ctx, addCatalogProduct, arg.CatalogID, arg.ProductID, arg.Position)
	return err
}

const clearCatalogProducts = `-- name: ClearCatalogProducts :exec
DELETE FROM catalog_products WHERE catalog_id = $1
`

func (q *Queries) ClearCatalogProducts(ctx context.Context, catalogID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearCatalogProducts, catalogID)
	return err
}

const createCatalog = `-- name: CreateCatalog :one
INSERT INTO catalogs (store_id, name)
VALUES ($1, $2)
RETURNING id, store_id, name, created_at, updated_at
`

type CreateCatalogParams struct {
	StoreID pgtype.UUID `json:"store_id"`
	Name    string      `json:"name"`
}

func (q *Queries) CreateCatalog(ctx context.Context, arg CreateCatalogParams) (Catalog, error) {
	row := q.db.QueryRow(ctx, createCatalog, arg.StoreID, arg.Name)
	var i Catalog
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCatalog = `-- name: DeleteCatalog :execrows
DELETE FROM catalogs WHERE id = $1 AND store_id = $2
`

type DeleteCatalogParams struct {
	ID      pgtype.UUID `json:"id"`
	StoreID pgtype.UUID `json:"store_id"`
}

func (q *Queries) DeleteCatalog(ctx context.Context, arg DeleteCatalogParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCatalog, arg.ID, arg.StoreID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCatalogByEventPublic = `-- name: GetCatalogByEventPublic :one
SELECT c.id, c.store_id, c.name, c.created_at, c.updated_at
FROM live_events e
JOIN catalogs c ON c.id = e.catalog_id
WHERE e.id = $1
`

// Public (buyer-facing) lookup: the catalog for an event, no store scoping.
func (q *Queries) GetCatalogByEventPublic(ctx context.Context, id pgtype.UUID) (Catalog, error) {
	row := q.db.QueryRow(ctx, getCatalogByEventPublic, id)
	var i Catalog
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCatalogByID = `-- name: GetCatalogByID :one
SELECT id, store_id, name, created_at, updated_at FROM catalogs WHERE id = $1 AND store_id = $2
`

type GetCatalogByIDParams struct {
	ID      pgtype.UUID `json:"id"`
	StoreID pgtype.UUID `json:"store_id"`
}

func (q *Queries) GetCatalogByID(ctx context.Context, arg GetCatalogByIDParams) (Catalog, error) {
	row := q.db.QueryRow(ctx, getCatalogByID, arg.ID, arg.StoreID)
	var i Catalog
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLiveEventCatalog = `-- name: GetLiveEventCatalog :one
SELECT c.id, c.store_id, c.name, c.created_at, c.updated_at
FROM live_events e
JOIN catalogs c ON c.id = e.catalog_id
WHERE e.id = $1 AND e.store_id = $2
`

type GetLiveEventCatalogParams struct {
	ID      pgtype.UUID `json:"id"`
	StoreID pgtype.UUID `json:"store_id"`
}

// The catalog currently associated with an event (store-scoped). Errors if none.
func (q *Queries) GetLiveEventCatalog(ctx context.Context, arg GetLiveEventCatalogParams) (Catalog, error) {
	row := q.db.QueryRow(ctx, getLiveEventCatalog, arg.ID, arg.StoreID)
	var i Catalog
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCatalogProducts = `-- name: ListCatalogProducts :many
SELECT p.id, p.name, p.keyword, p.price, p.image_url, p.stock, p.active, cp.position
FROM catalog_products cp
JOIN products p ON p.id = cp.product_id
JOIN catalogs c ON c.id = cp.catalog_id
WHERE cp.catalog_id = $1 AND c.store_id = $2
ORDER BY cp.position ASC, p.name ASC
`

type ListCatalogProductsParams struct {
	CatalogID pgtype.UUID `json:"catalog_id"`
	StoreID   pgtype.UUID `json:"store_id"`
}

type ListCatalogProductsRow struct {
	ID       pgtype.UUID `json:"id"`
	Name     string      `json:"name"`
	Keyword  string      `json:"keyword"`
	Price    pgtype.Int8 `json:"price"`
	ImageUrl pgtype.Text `json:"image_url"`
	Stock    pgtype.Int4 `json:"stock"`
	Active   pgtype.Bool `json:"active"`
	Position int32       `json:"position"`
}

// Products of a catalog, in display order. Scoped by store_id for safety.
func (q *Queries) ListCatalogProducts(ctx context.Context, arg ListCatalogProductsParams) ([]ListCatalogProductsRow, error) {
	rows, err := q.db.Query(ctx, listCatalogProducts, arg.CatalogID, arg.StoreID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCatalogProductsRow{}
	for rows.Next() {
		var i ListCatalogProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Keyword,
			&i.Price,
			&i.ImageUrl,
			&i.Stock,
			&i.Active,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCatalogProductsByEventPublic = `-- name: ListCatalogProductsByEventPublic :many
SELECT p.id, p.name, p.keyword, p.price, p.image_url, p.stock, cp.position
FROM live_events e
JOIN catalog_products cp ON cp.catalog_id = e.catalog_id
JOIN products p ON p.id = cp.product_id
WHERE e.id = $1 AND p.active = true
ORDER BY cp.position ASC, p.name ASC
`

type ListCatalogProductsByEventPublicRow struct {
	ID       pgtype.UUID `json:"id"`
	Name     string      `json:"name"`
	Keyword  string      `json:"keyword"`
	Price    pgtype.Int8 `json:"price"`
	ImageUrl pgtype.Text `json:"image_url"`
	Stock    pgtype.Int4 `json:"stock"`
	Position int32       `json:"position"`
}

// Public (buyer-facing) products of the event's catalog, in display order.
// Only active products are returned to buyers.
func (q *Queries) ListCatalogProductsByEventPublic(ctx context.Context, id pgtype.UUID) ([]ListCatalogProductsByEventPublicRow, error) {
	rows, err := q.db.Query(ctx, listCatalogProductsByEventPublic, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCatalogProductsByEventPublicRow{}
	for rows.Next() {
		var i ListCatalogProductsByEventPublicRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Keyword,
			&i.Price,
			&i.ImageUrl,
			&i.Stock,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCatalogsByStore = `-- name: ListCatalogsByStore :many
SELECT c.id, c.store_id, c.name, c.created_at, c.updated_at, COUNT(cp.product_id) AS product_count
FROM catalogs c
LEFT JOIN catalog_products cp ON cp.catalog_id = c.id
WHERE c.store_id = $1
GROUP BY c.id
ORDER BY c.created_at DESC
`

type ListCatalogsByStoreRow struct {
	ID           pgtype.UUID        `json:"id"`
	StoreID      pgtype.UUID        `json:"store_id"`
	Name         string             `json:"name"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	ProductCount int64              `json:"product_count"`
}

func (q *Queries) ListCatalogsByStore(ctx context.Context, storeID pgtype.UUID) ([]ListCatalogsByStoreRow, error) {
	rows, err := q.db.Query(ctx, listCatalogsByStore, storeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCatalogsByStoreRow{}
	for rows.Next() {
		var i ListCatalogsByStoreRow
		if err := rows.Scan(
			&i.ID,
			&i.StoreID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProductCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setLiveEventCatalog = `-- name: SetLiveEventCatalog :execrows
UPDATE live_events
SET catalog_id = $1, updated_at = now()
WHERE id = $2 AND store_id = $3
`

type SetLiveEventCatalogParams struct {
	CatalogID pgtype.UUID `json:"catalog_id"`
	ID        pgtype.UUID `json:"id"`
	StoreID   pgtype.UUID `json:"store_id"`
}

// Associate (or clear, when $1 is NULL) a catalog with an event. Store-scoped.
func (q *Queries) SetLiveEventCatalog(ctx context.Context, arg SetLiveEventCatalogParams) (int64, error) {
	result, err := q.db.Exec(ctx, setLiveEventCatalog, arg.CatalogID, arg.ID, arg.StoreID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateCatalog = `-- name: UpdateCatalog :one
UPDATE catalogs
SET name = $3, updated_at = now()
WHERE id = $1 AND store_id = $2
RETURNING id, store_id, name, created_at, updated_at
`

type UpdateCatalogParams struct {
	ID      pgtype.UUID `json:"id"`
	StoreID pgtype.UUID `json:"store_id"`
	Name    string      `json:"name"`
}

func (q *Queries) UpdateCatalog(ctx context.Context, arg UpdateCatalogParams) (Catalog, error) {
	row := q.db.QueryRow(ctx, updateCatalog, arg.ID, arg.StoreID, arg.Name)
	var i Catalog
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
