// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: erp_stock_movement.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimERPStockMovement = `-- name: ClaimERPStockMovement :one
UPDATE erp_stock_movements
SET status = 'resolving', last_attempt_at = now(), updated_at = now()
WHERE id = $1
  AND status = $2::varchar
  AND ($2::varchar <> 'pending' OR created_at < now() - interval '2 minutes')
  AND ($2::varchar <> 'resolving' OR last_attempt_at < now() - interval '5 minutes')
RETURNING id, store_id, cart_id, event_id, product_id, external_product_id, direction, quantity, unit_price_cents, idempotency_key, status, erp_movement_id, attempts, last_error, last_attempt_at, created_at, updated_at, reservation_id
`

type ClaimERPStockMovementParams struct {
	ID         pgtype.UUID `json:"id"`
	FromStatus string      `json:"from_status"`
}

// Reivindica a linha (CAS: só se ela estiver no estado esperado) — mesmo
// desenho do claim-first da reversão de reservas: dois resolvers (o agendado e
// o inline do pagamento) podem mirar a mesma linha, e quem não reivindicou não
// age. Os guards de idade impedem reivindicar trabalho que ainda está em voo:
// 'pending' recente pertence à goroutine que fez a chamada; 'resolving' recente
// pertence a outro resolver. Envelhecidos são de processos mortos.
func (q *Queries) ClaimERPStockMovement(ctx context.Context, arg ClaimERPStockMovementParams) (ErpStockMovement, error) {
	row := q.db.QueryRow(ctx, claimERPStockMovement, arg.ID, arg.FromStatus)
	var i ErpStockMovement
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.CartID,
		&i.EventID,
		&i.ProductID,
		&i.ExternalProductID,
		&i.Direction,
		&i.Quantity,
		&i.UnitPriceCents,
		&i.IdempotencyKey,
		&i.Status,
		&i.ErpMovementID,
		&i.Attempts,
		&i.LastError,
		&i.LastAttemptAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReservationID,
	)
	return i, err
}

const createERPStockMovement = `-- name: CreateERPStockMovement :one
INSERT INTO erp_stock_movements (
    store_id, cart_id, event_id, product_id, external_product_id,
    direction, quantity, unit_price_cents, reservation_id
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, store_id, cart_id, event_id, product_id, external_product_id, direction, quantity, unit_price_cents, idempotency_key, status, erp_movement_id, attempts, last_error, last_attempt_at, created_at, updated_at, reservation_id
`

type CreateERPStockMovementParams struct {
	StoreID           pgtype.UUID `json:"store_id"`
	CartID            pgtype.UUID `json:"cart_id"`
	EventID           pgtype.UUID `json:"event_id"`
	ProductID         pgtype.UUID `json:"product_id"`
	ExternalProductID string      `json:"external_product_id"`
	Direction         string      `json:"direction"`
	Quantity          int32       `json:"quantity"`
	UnitPriceCents    int64       `json:"unit_price_cents"`
	ReservationID     pgtype.UUID `json:"reservation_id"`
}

// A intenção, gravada ANTES da chamada ao ERP. Ver a migration 000132.
func (q *Queries) CreateERPStockMovement(ctx context.Context, arg CreateERPStockMovementParams) (ErpStockMovement, error) {
	row := q.db.QueryRow(ctx, createERPStockMovement,
		arg.StoreID,
		arg.CartID,
		arg.EventID,
		arg.ProductID,
		arg.ExternalProductID,
		arg.Direction,
		arg.Quantity,
		arg.UnitPriceCents,
		arg.ReservationID,
	)
	var i ErpStockMovement
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.CartID,
		&i.EventID,
		&i.ProductID,
		&i.ExternalProductID,
		&i.Direction,
		&i.Quantity,
		&i.UnitPriceCents,
		&i.IdempotencyKey,
		&i.Status,
		&i.ErpMovementID,
		&i.Attempts,
		&i.LastError,
		&i.LastAttemptAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReservationID,
	)
	return i, err
}

const getERPStockMovement = `-- name: GetERPStockMovement :one
SELECT id, store_id, cart_id, event_id, product_id, external_product_id, direction, quantity, unit_price_cents, idempotency_key, status, erp_movement_id, attempts, last_error, last_attempt_at, created_at, updated_at, reservation_id FROM erp_stock_movements WHERE id = $1
`

func (q *Queries) GetERPStockMovement(ctx context.Context, id pgtype.UUID) (ErpStockMovement, error) {
	row := q.db.QueryRow(ctx, getERPStockMovement, id)
	var i ErpStockMovement
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.CartID,
		&i.EventID,
		&i.ProductID,
		&i.ExternalProductID,
		&i.Direction,
		&i.Quantity,
		&i.UnitPriceCents,
		&i.IdempotencyKey,
		&i.Status,
		&i.ErpMovementID,
		&i.Attempts,
		&i.LastError,
		&i.LastAttemptAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReservationID,
	)
	return i, err
}

const listUnresolvedERPStockMovements = `-- name: ListUnresolvedERPStockMovements :many
SELECT id, store_id, cart_id, event_id, product_id, external_product_id, direction, quantity, unit_price_cents, idempotency_key, status, erp_movement_id, attempts, last_error, last_attempt_at, created_at, updated_at, reservation_id FROM erp_stock_movements
WHERE status IN ('pending', 'failed', 'unconfirmed', 'resolving')
  AND created_at < now() - interval '1 minute'
ORDER BY created_at ASC
LIMIT $1
`

// Visibilidade: o que está parado, para log/painel/alerta.
func (q *Queries) ListUnresolvedERPStockMovements(ctx context.Context, limit int32) ([]ErpStockMovement, error) {
	rows, err := q.db.Query(ctx, listUnresolvedERPStockMovements, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ErpStockMovement{}
	for rows.Next() {
		var i ErpStockMovement
		if err := rows.Scan(
			&i.ID,
			&i.StoreID,
			&i.CartID,
			&i.EventID,
			&i.ProductID,
			&i.ExternalProductID,
			&i.Direction,
			&i.Quantity,
			&i.UnitPriceCents,
			&i.IdempotencyKey,
			&i.Status,
			&i.ErpMovementID,
			&i.Attempts,
			&i.LastError,
			&i.LastAttemptAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReservationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnresolvedERPStockMovementsByCart = `-- name: ListUnresolvedERPStockMovementsByCart :many
SELECT id, store_id, cart_id, event_id, product_id, external_product_id, direction, quantity, unit_price_cents, idempotency_key, status, erp_movement_id, attempts, last_error, last_attempt_at, created_at, updated_at, reservation_id FROM erp_stock_movements
WHERE cart_id = $1 AND status IN ('pending', 'failed', 'unconfirmed', 'resolving')
ORDER BY created_at ASC
`

// O gate da finalização: nada de pedido pago enquanto houver movimento em
// dúvida para o carrinho. 'pending' recente conta — pode ser chamada em voo.
func (q *Queries) ListUnresolvedERPStockMovementsByCart(ctx context.Context, cartID pgtype.UUID) ([]ErpStockMovement, error) {
	rows, err := q.db.Query(ctx, listUnresolvedERPStockMovementsByCart, cartID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ErpStockMovement{}
	for rows.Next() {
		var i ErpStockMovement
		if err := rows.Scan(
			&i.ID,
			&i.StoreID,
			&i.CartID,
			&i.EventID,
			&i.ProductID,
			&i.ExternalProductID,
			&i.Direction,
			&i.Quantity,
			&i.UnitPriceCents,
			&i.IdempotencyKey,
			&i.Status,
			&i.ErpMovementID,
			&i.Attempts,
			&i.LastError,
			&i.LastAttemptAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReservationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markERPStockMovementConfirmed = `-- name: MarkERPStockMovementConfirmed :exec
UPDATE erp_stock_movements
SET status = 'confirmed', erp_movement_id = $2, last_error = NULL, updated_at = now()
WHERE id = $1
`

type MarkERPStockMovementConfirmedParams struct {
	ID            pgtype.UUID `json:"id"`
	ErpMovementID pgtype.Text `json:"erp_movement_id"`
}

func (q *Queries) MarkERPStockMovementConfirmed(ctx context.Context, arg MarkERPStockMovementConfirmedParams) error {
	_, err := q.db.Exec(ctx, markERPStockMovementConfirmed, arg.ID, arg.ErpMovementID)
	return err
}

const markERPStockMovementOutcome = `-- name: MarkERPStockMovementOutcome :exec
UPDATE erp_stock_movements
SET status = $2, last_error = $3, attempts = attempts + 1,
    last_attempt_at = now(), updated_at = now()
WHERE id = $1
`

type MarkERPStockMovementOutcomeParams struct {
	ID        pgtype.UUID `json:"id"`
	Status    string      `json:"status"`
	LastError pgtype.Text `json:"last_error"`
}

// failed | unconfirmed, com o erro que levou até lá. attempts conta as
// tentativas de EXECUÇÃO (a inline e as do resolver), para o teto de desistir.
func (q *Queries) MarkERPStockMovementOutcome(ctx context.Context, arg MarkERPStockMovementOutcomeParams) error {
	_, err := q.db.Exec(ctx, markERPStockMovementOutcome, arg.ID, arg.Status, arg.LastError)
	return err
}
