// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: event_upsell.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveEventUpsells = `-- name: CountActiveEventUpsells :one
SELECT COUNT(*)::int
FROM event_upsells eu
JOIN products p ON p.id = eu.product_id
WHERE eu.event_id = $1 AND eu.active = true AND p.active = true AND p.stock > 0
`

func (q *Queries) CountActiveEventUpsells(ctx context.Context, eventID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countActiveEventUpsells, eventID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countEventUpsells = `-- name: CountEventUpsells :one
SELECT COUNT(*)::int FROM event_upsells WHERE event_id = $1
`

func (q *Queries) CountEventUpsells(ctx context.Context, eventID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countEventUpsells, eventID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createEventUpsell = `-- name: CreateEventUpsell :one

INSERT INTO event_upsells (event_id, product_id, discount_percent, message_template, display_order, active)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, event_id, product_id, discount_percent, message_template, display_order, active, created_at, updated_at
`

type CreateEventUpsellParams struct {
	EventID         pgtype.UUID `json:"event_id"`
	ProductID       pgtype.UUID `json:"product_id"`
	DiscountPercent int32       `json:"discount_percent"`
	MessageTemplate pgtype.Text `json:"message_template"`
	DisplayOrder    int32       `json:"display_order"`
	Active          bool        `json:"active"`
}

// =============================================================================
// EVENT UPSELLS
// =============================================================================
func (q *Queries) CreateEventUpsell(ctx context.Context, arg CreateEventUpsellParams) (EventUpsell, error) {
	row := q.db.QueryRow(ctx, createEventUpsell,
		arg.EventID,
		arg.ProductID,
		arg.DiscountPercent,
		arg.MessageTemplate,
		arg.DisplayOrder,
		arg.Active,
	)
	var i EventUpsell
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.ProductID,
		&i.DiscountPercent,
		&i.MessageTemplate,
		&i.DisplayOrder,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAllEventUpsells = `-- name: DeleteAllEventUpsells :exec
DELETE FROM event_upsells WHERE event_id = $1
`

func (q *Queries) DeleteAllEventUpsells(ctx context.Context, eventID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAllEventUpsells, eventID)
	return err
}

const deleteEventUpsell = `-- name: DeleteEventUpsell :exec
DELETE FROM event_upsells WHERE id = $1 AND event_id = $2
`

type DeleteEventUpsellParams struct {
	ID      pgtype.UUID `json:"id"`
	EventID pgtype.UUID `json:"event_id"`
}

func (q *Queries) DeleteEventUpsell(ctx context.Context, arg DeleteEventUpsellParams) error {
	_, err := q.db.Exec(ctx, deleteEventUpsell, arg.ID, arg.EventID)
	return err
}

const deleteEventUpsellByProductID = `-- name: DeleteEventUpsellByProductID :exec
DELETE FROM event_upsells WHERE event_id = $1 AND product_id = $2
`

type DeleteEventUpsellByProductIDParams struct {
	EventID   pgtype.UUID `json:"event_id"`
	ProductID pgtype.UUID `json:"product_id"`
}

func (q *Queries) DeleteEventUpsellByProductID(ctx context.Context, arg DeleteEventUpsellByProductIDParams) error {
	_, err := q.db.Exec(ctx, deleteEventUpsellByProductID, arg.EventID, arg.ProductID)
	return err
}

const getEventUpsellByID = `-- name: GetEventUpsellByID :one
SELECT
    eu.id, eu.event_id, eu.product_id, eu.discount_percent, eu.message_template, eu.display_order, eu.active, eu.created_at, eu.updated_at,
    p.name AS product_name,
    p.keyword AS product_keyword,
    p.price AS original_price,
    p.image_url AS product_image_url,
    p.stock AS product_stock,
    p.active AS product_active
FROM event_upsells eu
JOIN products p ON p.id = eu.product_id
WHERE eu.id = $1
`

type GetEventUpsellByIDRow struct {
	ID              pgtype.UUID        `json:"id"`
	EventID         pgtype.UUID        `json:"event_id"`
	ProductID       pgtype.UUID        `json:"product_id"`
	DiscountPercent int32              `json:"discount_percent"`
	MessageTemplate pgtype.Text        `json:"message_template"`
	DisplayOrder    int32              `json:"display_order"`
	Active          bool               `json:"active"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	ProductName     string             `json:"product_name"`
	ProductKeyword  string             `json:"product_keyword"`
	OriginalPrice   pgtype.Int8        `json:"original_price"`
	ProductImageUrl pgtype.Text        `json:"product_image_url"`
	ProductStock    pgtype.Int4        `json:"product_stock"`
	ProductActive   pgtype.Bool        `json:"product_active"`
}

func (q *Queries) GetEventUpsellByID(ctx context.Context, id pgtype.UUID) (GetEventUpsellByIDRow, error) {
	row := q.db.QueryRow(ctx, getEventUpsellByID, id)
	var i GetEventUpsellByIDRow
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.ProductID,
		&i.DiscountPercent,
		&i.MessageTemplate,
		&i.DisplayOrder,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProductName,
		&i.ProductKeyword,
		&i.OriginalPrice,
		&i.ProductImageUrl,
		&i.ProductStock,
		&i.ProductActive,
	)
	return i, err
}

const getUpsellDiscountedPrice = `-- name: GetUpsellDiscountedPrice :one
SELECT
    eu.discount_percent,
    p.price AS original_price,
    (p.price * (100 - eu.discount_percent) / 100)::bigint AS discounted_price
FROM event_upsells eu
JOIN products p ON p.id = eu.product_id
WHERE eu.id = $1
`

type GetUpsellDiscountedPriceRow struct {
	DiscountPercent int32       `json:"discount_percent"`
	OriginalPrice   pgtype.Int8 `json:"original_price"`
	DiscountedPrice int64       `json:"discounted_price"`
}

// Calculate discounted price for a specific upsell
func (q *Queries) GetUpsellDiscountedPrice(ctx context.Context, id pgtype.UUID) (GetUpsellDiscountedPriceRow, error) {
	row := q.db.QueryRow(ctx, getUpsellDiscountedPrice, id)
	var i GetUpsellDiscountedPriceRow
	err := row.Scan(&i.DiscountPercent, &i.OriginalPrice, &i.DiscountedPrice)
	return i, err
}

const isProductInEventUpsells = `-- name: IsProductInEventUpsells :one
SELECT EXISTS (SELECT 1 FROM event_upsells WHERE event_id = $1 AND product_id = $2) AS is_upsell
`

type IsProductInEventUpsellsParams struct {
	EventID   pgtype.UUID `json:"event_id"`
	ProductID pgtype.UUID `json:"product_id"`
}

// Check if product is already an upsell for this event
func (q *Queries) IsProductInEventUpsells(ctx context.Context, arg IsProductInEventUpsellsParams) (bool, error) {
	row := q.db.QueryRow(ctx, isProductInEventUpsells, arg.EventID, arg.ProductID)
	var is_upsell bool
	err := row.Scan(&is_upsell)
	return is_upsell, err
}

const listActiveEventUpsells = `-- name: ListActiveEventUpsells :many
SELECT
    eu.id, eu.event_id, eu.product_id, eu.discount_percent, eu.message_template, eu.display_order, eu.active, eu.created_at, eu.updated_at,
    p.name AS product_name,
    p.keyword AS product_keyword,
    p.price AS original_price,
    p.image_url AS product_image_url,
    p.stock AS product_stock,
    (p.price * (100 - eu.discount_percent) / 100)::bigint AS discounted_price
FROM event_upsells eu
JOIN products p ON p.id = eu.product_id
WHERE eu.event_id = $1
    AND eu.active = true
    AND p.active = true
    AND p.stock > 0
ORDER BY eu.display_order ASC
`

type ListActiveEventUpsellsRow struct {
	ID              pgtype.UUID        `json:"id"`
	EventID         pgtype.UUID        `json:"event_id"`
	ProductID       pgtype.UUID        `json:"product_id"`
	DiscountPercent int32              `json:"discount_percent"`
	MessageTemplate pgtype.Text        `json:"message_template"`
	DisplayOrder    int32              `json:"display_order"`
	Active          bool               `json:"active"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	ProductName     string             `json:"product_name"`
	ProductKeyword  string             `json:"product_keyword"`
	OriginalPrice   pgtype.Int8        `json:"original_price"`
	ProductImageUrl pgtype.Text        `json:"product_image_url"`
	ProductStock    pgtype.Int4        `json:"product_stock"`
	DiscountedPrice int64              `json:"discounted_price"`
}

// Get active upsells with available stock
func (q *Queries) ListActiveEventUpsells(ctx context.Context, eventID pgtype.UUID) ([]ListActiveEventUpsellsRow, error) {
	rows, err := q.db.Query(ctx, listActiveEventUpsells, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveEventUpsellsRow{}
	for rows.Next() {
		var i ListActiveEventUpsellsRow
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.ProductID,
			&i.DiscountPercent,
			&i.MessageTemplate,
			&i.DisplayOrder,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProductName,
			&i.ProductKeyword,
			&i.OriginalPrice,
			&i.ProductImageUrl,
			&i.ProductStock,
			&i.DiscountedPrice,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventUpsells = `-- name: ListEventUpsells :many
SELECT
    eu.id, eu.event_id, eu.product_id, eu.discount_percent, eu.message_template, eu.display_order, eu.active, eu.created_at, eu.updated_at,
    p.name AS product_name,
    p.keyword AS product_keyword,
    p.price AS original_price,
    p.image_url AS product_image_url,
    p.stock AS product_stock,
    p.active AS product_active
FROM event_upsells eu
JOIN products p ON p.id = eu.product_id
WHERE eu.event_id = $1
ORDER BY eu.display_order ASC, eu.created_at ASC
`

type ListEventUpsellsRow struct {
	ID              pgtype.UUID        `json:"id"`
	EventID         pgtype.UUID        `json:"event_id"`
	ProductID       pgtype.UUID        `json:"product_id"`
	DiscountPercent int32              `json:"discount_percent"`
	MessageTemplate pgtype.Text        `json:"message_template"`
	DisplayOrder    int32              `json:"display_order"`
	Active          bool               `json:"active"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	ProductName     string             `json:"product_name"`
	ProductKeyword  string             `json:"product_keyword"`
	OriginalPrice   pgtype.Int8        `json:"original_price"`
	ProductImageUrl pgtype.Text        `json:"product_image_url"`
	ProductStock    pgtype.Int4        `json:"product_stock"`
	ProductActive   pgtype.Bool        `json:"product_active"`
}

func (q *Queries) ListEventUpsells(ctx context.Context, eventID pgtype.UUID) ([]ListEventUpsellsRow, error) {
	rows, err := q.db.Query(ctx, listEventUpsells, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEventUpsellsRow{}
	for rows.Next() {
		var i ListEventUpsellsRow
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.ProductID,
			&i.DiscountPercent,
			&i.MessageTemplate,
			&i.DisplayOrder,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProductName,
			&i.ProductKeyword,
			&i.OriginalPrice,
			&i.ProductImageUrl,
			&i.ProductStock,
			&i.ProductActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEventUpsell = `-- name: UpdateEventUpsell :one
UPDATE event_upsells
SET
    discount_percent = $3,
    message_template = $4,
    display_order = $5,
    active = $6,
    updated_at = now()
WHERE id = $1 AND event_id = $2
RETURNING id, event_id, product_id, discount_percent, message_template, display_order, active, created_at, updated_at
`

type UpdateEventUpsellParams struct {
	ID              pgtype.UUID `json:"id"`
	EventID         pgtype.UUID `json:"event_id"`
	DiscountPercent int32       `json:"discount_percent"`
	MessageTemplate pgtype.Text `json:"message_template"`
	DisplayOrder    int32       `json:"display_order"`
	Active          bool        `json:"active"`
}

func (q *Queries) UpdateEventUpsell(ctx context.Context, arg UpdateEventUpsellParams) (EventUpsell, error) {
	row := q.db.QueryRow(ctx, updateEventUpsell,
		arg.ID,
		arg.EventID,
		arg.DiscountPercent,
		arg.MessageTemplate,
		arg.DisplayOrder,
		arg.Active,
	)
	var i EventUpsell
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.ProductID,
		&i.DiscountPercent,
		&i.MessageTemplate,
		&i.DisplayOrder,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
