// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: integration.sql

package sqlc

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeOAuthState = `-- name: ConsumeOAuthState :one
DELETE FROM oauth_states
WHERE state = $1 AND expires_at > now()
RETURNING state, store_id, provider, code_verifier, created_at, expires_at
`

// ConsumeOAuthState valida e APAGA o state numa operação só.
//
// Diferente do par GetOAuthState + DeleteOAuthState, que são duas queries e
// deixam uma janela entre a leitura e o apagamento. Para o Bling isso não é
// preciosismo: a doc avisa que reusar um authorization code ainda válido faz o
// usuário ter "o seu acesso revogado por medidas de segurança". Um duplo clique
// no callback com o par não-atômico passaria os dois pela validação.
func (q *Queries) ConsumeOAuthState(ctx context.Context, state string) (OauthState, error) {
	row := q.db.QueryRow(ctx, consumeOAuthState, state)
	var i OauthState
	err := row.Scan(
		&i.State,
		&i.StoreID,
		&i.Provider,
		&i.CodeVerifier,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const countIntegrationLogs = `-- name: CountIntegrationLogs :one
SELECT COUNT(*) FROM integration_logs WHERE integration_id = $1
`

func (q *Queries) CountIntegrationLogs(ctx context.Context, integrationID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countIntegrationLogs, integrationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createIdempotencyKey = `-- name: CreateIdempotencyKey :one
INSERT INTO idempotency_keys (idempotency_key, store_id, integration_id, operation, request_hash, status)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, idempotency_key, store_id, integration_id, operation, request_hash, response_payload, status, created_at, expires_at
`

type CreateIdempotencyKeyParams struct {
	IdempotencyKey string      `json:"idempotency_key"`
	StoreID        pgtype.UUID `json:"store_id"`
	IntegrationID  pgtype.UUID `json:"integration_id"`
	Operation      string      `json:"operation"`
	RequestHash    pgtype.Text `json:"request_hash"`
	Status         string      `json:"status"`
}

func (q *Queries) CreateIdempotencyKey(ctx context.Context, arg CreateIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, createIdempotencyKey,
		arg.IdempotencyKey,
		arg.StoreID,
		arg.IntegrationID,
		arg.Operation,
		arg.RequestHash,
		arg.Status,
	)
	var i IdempotencyKey
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.StoreID,
		&i.IntegrationID,
		&i.Operation,
		&i.RequestHash,
		&i.ResponsePayload,
		&i.Status,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const createIntegration = `-- name: CreateIntegration :one

INSERT INTO integrations (store_id, type, provider, status, credentials, token_expires_at, metadata)
VALUES ($1, $2, $3, $4, $5, $6, COALESCE(NULLIF($7::text, '')::jsonb, '{}'::jsonb))
RETURNING id, store_id, type, provider, status, token_expires_at, last_synced_at, created_at, credentials, metadata, priority, erp_account_id
`

type CreateIntegrationParams struct {
	StoreID        pgtype.UUID        `json:"store_id"`
	Type           string             `json:"type"`
	Provider       string             `json:"provider"`
	Status         string             `json:"status"`
	Credentials    []byte             `json:"credentials"`
	TokenExpiresAt pgtype.Timestamptz `json:"token_expires_at"`
	Column7        string             `json:"column_7"`
}

// =============================================================================
// INTEGRATIONS
// =============================================================================
func (q *Queries) CreateIntegration(ctx context.Context, arg CreateIntegrationParams) (Integration, error) {
	row := q.db.QueryRow(ctx, createIntegration,
		arg.StoreID,
		arg.Type,
		arg.Provider,
		arg.Status,
		arg.Credentials,
		arg.TokenExpiresAt,
		arg.Column7,
	)
	var i Integration
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.Type,
		&i.Provider,
		&i.Status,
		&i.TokenExpiresAt,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.Credentials,
		&i.Metadata,
		&i.Priority,
		&i.ErpAccountID,
	)
	return i, err
}

const createIntegrationLog = `-- name: CreateIntegrationLog :one

INSERT INTO integration_logs (integration_id, entity_type, entity_id, direction, status, request_payload, response_payload, error_message)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, integration_id, entity_type, entity_id, direction, status, request_payload, response_payload, error_message, created_at
`

type CreateIntegrationLogParams struct {
	IntegrationID   pgtype.UUID     `json:"integration_id"`
	EntityType      pgtype.Text     `json:"entity_type"`
	EntityID        pgtype.UUID     `json:"entity_id"`
	Direction       pgtype.Text     `json:"direction"`
	Status          pgtype.Text     `json:"status"`
	RequestPayload  json.RawMessage `json:"request_payload"`
	ResponsePayload json.RawMessage `json:"response_payload"`
	ErrorMessage    pgtype.Text     `json:"error_message"`
}

// =============================================================================
// INTEGRATION LOGS
// =============================================================================
func (q *Queries) CreateIntegrationLog(ctx context.Context, arg CreateIntegrationLogParams) (IntegrationLog, error) {
	row := q.db.QueryRow(ctx, createIntegrationLog,
		arg.IntegrationID,
		arg.EntityType,
		arg.EntityID,
		arg.Direction,
		arg.Status,
		arg.RequestPayload,
		arg.ResponsePayload,
		arg.ErrorMessage,
	)
	var i IntegrationLog
	err := row.Scan(
		&i.ID,
		&i.IntegrationID,
		&i.EntityType,
		&i.EntityID,
		&i.Direction,
		&i.Status,
		&i.RequestPayload,
		&i.ResponsePayload,
		&i.ErrorMessage,
		&i.CreatedAt,
	)
	return i, err
}

const createOAuthState = `-- name: CreateOAuthState :exec


INSERT INTO oauth_states (state, store_id, provider, code_verifier)
VALUES ($1, $2, $3, $4)
`

type CreateOAuthStateParams struct {
	State        string      `json:"state"`
	StoreID      pgtype.UUID `json:"store_id"`
	Provider     string      `json:"provider"`
	CodeVerifier string      `json:"code_verifier"`
}

// (Queries de subscriptions migraram para db/queries/subscription.sql na
// remodelagem do billing via Stripe — PRD 007, migration 000076.)
// =============================================================================
// OAUTH STATES (PKCE)
// =============================================================================
func (q *Queries) CreateOAuthState(ctx context.Context, arg CreateOAuthStateParams) error {
	_, err := q.db.Exec(ctx, createOAuthState,
		arg.State,
		arg.StoreID,
		arg.Provider,
		arg.CodeVerifier,
	)
	return err
}

const createWebhookEvent = `-- name: CreateWebhookEvent :one

INSERT INTO webhook_events (integration_id, provider, event_type, event_id, payload, signature_valid)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, integration_id, provider, event_type, event_id, payload, signature_valid, processed, processed_at, error_message, created_at
`

type CreateWebhookEventParams struct {
	IntegrationID  pgtype.UUID     `json:"integration_id"`
	Provider       string          `json:"provider"`
	EventType      string          `json:"event_type"`
	EventID        pgtype.Text     `json:"event_id"`
	Payload        json.RawMessage `json:"payload"`
	SignatureValid pgtype.Bool     `json:"signature_valid"`
}

// =============================================================================
// WEBHOOK EVENTS
// =============================================================================
func (q *Queries) CreateWebhookEvent(ctx context.Context, arg CreateWebhookEventParams) (WebhookEvent, error) {
	row := q.db.QueryRow(ctx, createWebhookEvent,
		arg.IntegrationID,
		arg.Provider,
		arg.EventType,
		arg.EventID,
		arg.Payload,
		arg.SignatureValid,
	)
	var i WebhookEvent
	err := row.Scan(
		&i.ID,
		&i.IntegrationID,
		&i.Provider,
		&i.EventType,
		&i.EventID,
		&i.Payload,
		&i.SignatureValid,
		&i.Processed,
		&i.ProcessedAt,
		&i.ErrorMessage,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredIdempotencyKeys = `-- name: DeleteExpiredIdempotencyKeys :exec
DELETE FROM idempotency_keys WHERE expires_at < now()
`

func (q *Queries) DeleteExpiredIdempotencyKeys(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredIdempotencyKeys)
	return err
}

const deleteExpiredOAuthStates = `-- name: DeleteExpiredOAuthStates :exec
DELETE FROM oauth_states WHERE expires_at < now()
`

func (q *Queries) DeleteExpiredOAuthStates(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredOAuthStates)
	return err
}

const deleteIntegration = `-- name: DeleteIntegration :exec
DELETE FROM integrations WHERE id = $1 AND store_id = $2
`

type DeleteIntegrationParams struct {
	ID      pgtype.UUID `json:"id"`
	StoreID pgtype.UUID `json:"store_id"`
}

func (q *Queries) DeleteIntegration(ctx context.Context, arg DeleteIntegrationParams) error {
	_, err := q.db.Exec(ctx, deleteIntegration, arg.ID, arg.StoreID)
	return err
}

const deleteOAuthState = `-- name: DeleteOAuthState :exec
DELETE FROM oauth_states WHERE state = $1
`

func (q *Queries) DeleteOAuthState(ctx context.Context, state string) error {
	_, err := q.db.Exec(ctx, deleteOAuthState, state)
	return err
}

const getActiveERPByAccount = `-- name: GetActiveERPByAccount :one
SELECT id, store_id, type, provider, status, token_expires_at, last_synced_at, created_at, credentials, metadata, priority, erp_account_id FROM integrations
WHERE type = 'erp' AND provider = $1 AND erp_account_id = $2 AND status = 'active'
LIMIT 1
`

type GetActiveERPByAccountParams struct {
	Provider     string      `json:"provider"`
	ErpAccountID pgtype.Text `json:"erp_account_id"`
}

// GetActiveERPByAccount resolve a LOJA a partir da conta do ERP. É como o
// webhook do Bling, que chega numa URL única para todas as lojas, descobre de
// quem é o evento: o `companyId` do envelope casa com integrations.erp_account_id.
//
// Usa o índice parcial idx_integrations_erp_account.
func (q *Queries) GetActiveERPByAccount(ctx context.Context, arg GetActiveERPByAccountParams) (Integration, error) {
	row := q.db.QueryRow(ctx, getActiveERPByAccount, arg.Provider, arg.ErpAccountID)
	var i Integration
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.Type,
		&i.Provider,
		&i.Status,
		&i.TokenExpiresAt,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.Credentials,
		&i.Metadata,
		&i.Priority,
		&i.ErpAccountID,
	)
	return i, err
}

const getActiveERPIntegration = `-- name: GetActiveERPIntegration :one
SELECT id, store_id, type, provider, status, token_expires_at, last_synced_at, created_at, credentials, metadata, priority, erp_account_id FROM integrations
WHERE store_id = $1 AND type = 'erp' AND status = 'active'
ORDER BY created_at ASC, id ASC
LIMIT 1
`

// GetActiveERPIntegration resolve o ERP ATIVO da loja pela LINHA, sem o literal
// do provider. É seguro devolver :one porque o índice parcial
// uniq_integrations_store_one_erp (migration 000061) garante no máximo uma
// integração de ERP por loja — a regra de negócio "ou Tiny ou Bling, nunca os
// dois" é do banco, não da convenção de quem escreve a query.
//
// Existe para substituir os call sites que perguntavam por provider='tiny'
// literal: com Bling conectado, aqueles devolviam not-found e QUATRO deles
// tratavam isso como "loja sem ERP", devolvendo nil em silêncio — a live rodava
// inteira sem criar um pedido e sem uma linha de log.
func (q *Queries) GetActiveERPIntegration(ctx context.Context, storeID pgtype.UUID) (Integration, error) {
	row := q.db.QueryRow(ctx, getActiveERPIntegration, storeID)
	var i Integration
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.Type,
		&i.Provider,
		&i.Status,
		&i.TokenExpiresAt,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.Credentials,
		&i.Metadata,
		&i.Priority,
		&i.ErpAccountID,
	)
	return i, err
}

const getActiveIntegrationByProvider = `-- name: GetActiveIntegrationByProvider :one
SELECT id, store_id, type, provider, status, token_expires_at, last_synced_at, created_at, credentials, metadata, priority, erp_account_id FROM integrations
WHERE store_id = $1 AND type = $2 AND provider = $3 AND status = 'active'
LIMIT 1
`

type GetActiveIntegrationByProviderParams struct {
	StoreID  pgtype.UUID `json:"store_id"`
	Type     string      `json:"type"`
	Provider string      `json:"provider"`
}

func (q *Queries) GetActiveIntegrationByProvider(ctx context.Context, arg GetActiveIntegrationByProviderParams) (Integration, error) {
	row := q.db.QueryRow(ctx, getActiveIntegrationByProvider, arg.StoreID, arg.Type, arg.Provider)
	var i Integration
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.Type,
		&i.Provider,
		&i.Status,
		&i.TokenExpiresAt,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.Credentials,
		&i.Metadata,
		&i.Priority,
		&i.ErpAccountID,
	)
	return i, err
}

const getIdempotencyByHash = `-- name: GetIdempotencyByHash :one
SELECT id, idempotency_key, store_id, integration_id, operation, request_hash, response_payload, status, created_at, expires_at FROM idempotency_keys
WHERE store_id = $1 AND request_hash = $2 AND created_at > $3 AND status = 'completed'
ORDER BY created_at DESC
LIMIT 1
`

type GetIdempotencyByHashParams struct {
	StoreID     pgtype.UUID        `json:"store_id"`
	RequestHash pgtype.Text        `json:"request_hash"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetIdempotencyByHash(ctx context.Context, arg GetIdempotencyByHashParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, getIdempotencyByHash, arg.StoreID, arg.RequestHash, arg.CreatedAt)
	var i IdempotencyKey
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.StoreID,
		&i.IntegrationID,
		&i.Operation,
		&i.RequestHash,
		&i.ResponsePayload,
		&i.Status,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getIdempotencyByKey = `-- name: GetIdempotencyByKey :one

SELECT id, idempotency_key, store_id, integration_id, operation, request_hash, response_payload, status, created_at, expires_at FROM idempotency_keys
WHERE store_id = $1 AND idempotency_key = $2 AND expires_at > now()
`

type GetIdempotencyByKeyParams struct {
	StoreID        pgtype.UUID `json:"store_id"`
	IdempotencyKey string      `json:"idempotency_key"`
}

// =============================================================================
// IDEMPOTENCY KEYS
// =============================================================================
func (q *Queries) GetIdempotencyByKey(ctx context.Context, arg GetIdempotencyByKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, getIdempotencyByKey, arg.StoreID, arg.IdempotencyKey)
	var i IdempotencyKey
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.StoreID,
		&i.IntegrationID,
		&i.Operation,
		&i.RequestHash,
		&i.ResponsePayload,
		&i.Status,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getIntegrationByID = `-- name: GetIntegrationByID :one
SELECT id, store_id, type, provider, status, token_expires_at, last_synced_at, created_at, credentials, metadata, priority, erp_account_id FROM integrations WHERE id = $1 AND store_id = $2
`

type GetIntegrationByIDParams struct {
	ID      pgtype.UUID `json:"id"`
	StoreID pgtype.UUID `json:"store_id"`
}

func (q *Queries) GetIntegrationByID(ctx context.Context, arg GetIntegrationByIDParams) (Integration, error) {
	row := q.db.QueryRow(ctx, getIntegrationByID, arg.ID, arg.StoreID)
	var i Integration
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.Type,
		&i.Provider,
		&i.Status,
		&i.TokenExpiresAt,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.Credentials,
		&i.Metadata,
		&i.Priority,
		&i.ErpAccountID,
	)
	return i, err
}

const getIntegrationByIDOnly = `-- name: GetIntegrationByIDOnly :one
SELECT id, store_id, type, provider, status, token_expires_at, last_synced_at, created_at, credentials, metadata, priority, erp_account_id FROM integrations WHERE id = $1
`

func (q *Queries) GetIntegrationByIDOnly(ctx context.Context, id pgtype.UUID) (Integration, error) {
	row := q.db.QueryRow(ctx, getIntegrationByIDOnly, id)
	var i Integration
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.Type,
		&i.Provider,
		&i.Status,
		&i.TokenExpiresAt,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.Credentials,
		&i.Metadata,
		&i.Priority,
		&i.ErpAccountID,
	)
	return i, err
}

const getIntegrationByProvider = `-- name: GetIntegrationByProvider :one
SELECT id, store_id, type, provider, status, token_expires_at, last_synced_at, created_at, credentials, metadata, priority, erp_account_id FROM integrations
WHERE store_id = $1 AND type = $2 AND provider = $3 AND status IN ('active', 'pending_auth')
ORDER BY created_at DESC
LIMIT 1
`

type GetIntegrationByProviderParams struct {
	StoreID  pgtype.UUID `json:"store_id"`
	Type     string      `json:"type"`
	Provider string      `json:"provider"`
}

func (q *Queries) GetIntegrationByProvider(ctx context.Context, arg GetIntegrationByProviderParams) (Integration, error) {
	row := q.db.QueryRow(ctx, getIntegrationByProvider, arg.StoreID, arg.Type, arg.Provider)
	var i Integration
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.Type,
		&i.Provider,
		&i.Status,
		&i.TokenExpiresAt,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.Credentials,
		&i.Metadata,
		&i.Priority,
		&i.ErpAccountID,
	)
	return i, err
}

const getOAuthState = `-- name: GetOAuthState :one
SELECT state, store_id, provider, code_verifier, created_at, expires_at FROM oauth_states
WHERE state = $1 AND expires_at > now()
`

func (q *Queries) GetOAuthState(ctx context.Context, state string) (OauthState, error) {
	row := q.db.QueryRow(ctx, getOAuthState, state)
	var i OauthState
	err := row.Scan(
		&i.State,
		&i.StoreID,
		&i.Provider,
		&i.CodeVerifier,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getWebhookEventByEventID = `-- name: GetWebhookEventByEventID :one
SELECT id, integration_id, provider, event_type, event_id, payload, signature_valid, processed, processed_at, error_message, created_at FROM webhook_events
WHERE integration_id = $1 AND event_id = $2
`

type GetWebhookEventByEventIDParams struct {
	IntegrationID pgtype.UUID `json:"integration_id"`
	EventID       pgtype.Text `json:"event_id"`
}

func (q *Queries) GetWebhookEventByEventID(ctx context.Context, arg GetWebhookEventByEventIDParams) (WebhookEvent, error) {
	row := q.db.QueryRow(ctx, getWebhookEventByEventID, arg.IntegrationID, arg.EventID)
	var i WebhookEvent
	err := row.Scan(
		&i.ID,
		&i.IntegrationID,
		&i.Provider,
		&i.EventType,
		&i.EventID,
		&i.Payload,
		&i.SignatureValid,
		&i.Processed,
		&i.ProcessedAt,
		&i.ErrorMessage,
		&i.CreatedAt,
	)
	return i, err
}

const healIntegrationFromError = `-- name: HealIntegrationFromError :execrows
UPDATE integrations
SET status = 'active'
WHERE id = $1 AND status = 'error'
`

// Devolve a integração de 'error' para 'active' quando uma chamada volta a dar
// certo. Condicional de propósito: só toca a linha que ESTÁ em 'error', então
// não pisa em 'pending_auth' (autorização em andamento) nem em 'disconnected'
// (o lojista desligou de propósito).
//
// Existe porque 'error' não tinha saída automática. Um HTTP 429 — que é
// transitório por definição — marcava a integração como quebrada e nada nunca
// revertia: o botão de sincronizar sumia do painel e só reconectar à mão
// resolvia. Aconteceu em 09/08/2026 e deixou o ERP parado por três dias.
//
// Não mexe em last_synced_at: quem acabou de rodar a operação é que carimba isso.
func (q *Queries) HealIntegrationFromError(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, healIntegrationFromError, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listIntegrationLogs = `-- name: ListIntegrationLogs :many
SELECT id, integration_id, entity_type, entity_id, direction, status, request_payload, response_payload, error_message, created_at FROM integration_logs
WHERE integration_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListIntegrationLogsParams struct {
	IntegrationID pgtype.UUID `json:"integration_id"`
	Limit         int32       `json:"limit"`
	Offset        int32       `json:"offset"`
}

func (q *Queries) ListIntegrationLogs(ctx context.Context, arg ListIntegrationLogsParams) ([]IntegrationLog, error) {
	rows, err := q.db.Query(ctx, listIntegrationLogs, arg.IntegrationID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IntegrationLog{}
	for rows.Next() {
		var i IntegrationLog
		if err := rows.Scan(
			&i.ID,
			&i.IntegrationID,
			&i.EntityType,
			&i.EntityID,
			&i.Direction,
			&i.Status,
			&i.RequestPayload,
			&i.ResponsePayload,
			&i.ErrorMessage,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIntegrationsByStore = `-- name: ListIntegrationsByStore :many
SELECT id, store_id, type, provider, status, token_expires_at, last_synced_at, created_at, credentials, metadata, priority, erp_account_id FROM integrations WHERE store_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListIntegrationsByStore(ctx context.Context, storeID pgtype.UUID) ([]Integration, error) {
	rows, err := q.db.Query(ctx, listIntegrationsByStore, storeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Integration{}
	for rows.Next() {
		var i Integration
		if err := rows.Scan(
			&i.ID,
			&i.StoreID,
			&i.Type,
			&i.Provider,
			&i.Status,
			&i.TokenExpiresAt,
			&i.LastSyncedAt,
			&i.CreatedAt,
			&i.Credentials,
			&i.Metadata,
			&i.Priority,
			&i.ErpAccountID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIntegrationsByType = `-- name: ListIntegrationsByType :many
SELECT id, store_id, type, provider, status, token_expires_at, last_synced_at, created_at, credentials, metadata, priority, erp_account_id FROM integrations
WHERE store_id = $1 AND type = $2 AND status = 'active'
ORDER BY created_at DESC
`

type ListIntegrationsByTypeParams struct {
	StoreID pgtype.UUID `json:"store_id"`
	Type    string      `json:"type"`
}

func (q *Queries) ListIntegrationsByType(ctx context.Context, arg ListIntegrationsByTypeParams) ([]Integration, error) {
	rows, err := q.db.Query(ctx, listIntegrationsByType, arg.StoreID, arg.Type)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Integration{}
	for rows.Next() {
		var i Integration
		if err := rows.Scan(
			&i.ID,
			&i.StoreID,
			&i.Type,
			&i.Provider,
			&i.Status,
			&i.TokenExpiresAt,
			&i.LastSyncedAt,
			&i.CreatedAt,
			&i.Credentials,
			&i.Metadata,
			&i.Priority,
			&i.ErpAccountID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIntegrationsWithExpiringTokens = `-- name: ListIntegrationsWithExpiringTokens :many
SELECT id, store_id, type, provider, status, token_expires_at, last_synced_at, created_at, credentials, metadata, priority, erp_account_id FROM integrations
WHERE status = 'active'
  AND token_expires_at IS NOT NULL
  AND token_expires_at <= $1
  -- ⚠ Acrescentar provider aqui é a mudança de UMA PALAVRA que pode derrubar a
  -- frota inteira. O Bling bloqueia o IP por 60 MINUTOS depois de 20 chamadas a
  -- /oauth/token em 60 s, e o IP é o NAT compartilhado do Railway — durante o
  -- bloqueio ninguém renova E ninguém consegue conectar.
  --
  -- Por isso 'bling' só entrou junto com o espaçamento no worker
  -- (TokenRefreshWorker.refreshExpiringTokens). Nunca acrescente um provider
  -- aqui sem conferir que o worker respeita o teto de chamadas dele.
  AND provider IN ('tiny', 'mercado_pago', 'instagram', 'bling')
ORDER BY token_expires_at ASC
LIMIT 100
`

// Lists active integrations with OAuth tokens expiring within the given duration.
// Used by background token refresh worker.
func (q *Queries) ListIntegrationsWithExpiringTokens(ctx context.Context, tokenExpiresAt pgtype.Timestamptz) ([]Integration, error) {
	rows, err := q.db.Query(ctx, listIntegrationsWithExpiringTokens, tokenExpiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Integration{}
	for rows.Next() {
		var i Integration
		if err := rows.Scan(
			&i.ID,
			&i.StoreID,
			&i.Type,
			&i.Provider,
			&i.Status,
			&i.TokenExpiresAt,
			&i.LastSyncedAt,
			&i.CreatedAt,
			&i.Credentials,
			&i.Metadata,
			&i.Priority,
			&i.ErpAccountID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTinyIntegrationsWithStaleStockWebhook = `-- name: ListTinyIntegrationsWithStaleStockWebhook :many
SELECT i.id, i.store_id, MAX(we.created_at)::timestamptz AS last_stock_event_at
FROM integrations i
LEFT JOIN webhook_events we
       ON we.integration_id = i.id AND we.event_type = 'estoque'
WHERE i.type = 'erp' AND i.provider = 'tiny' AND i.status = 'active'
  AND i.created_at < now() - make_interval(hours => $1::int)
  AND COALESCE((i.metadata->>'stock_webhook_alerted_at')::timestamptz, 'epoch'::timestamptz)
      < now() - interval '24 hours'
GROUP BY i.id, i.store_id
HAVING COALESCE(MAX(we.created_at), 'epoch'::timestamptz)
       < now() - make_interval(hours => $1::int)
`

type ListTinyIntegrationsWithStaleStockWebhookRow struct {
	ID               pgtype.UUID        `json:"id"`
	StoreID          pgtype.UUID        `json:"store_id"`
	LastStockEventAt pgtype.Timestamptz `json:"last_stock_event_at"`
}

// Health-check de ENTREGA de webhook (aprendizado de 11/07: o Tiny remove o
// cadastro da URL após falhas consecutivas e para de entregar em silêncio).
// Lista integrações Tiny ativas, criadas há mais de @stale_hours, sem NENHUM
// webhook de estoque nesse período e ainda não alertadas nas últimas 24h
// (dedupe via metadata->>'stock_webhook_alerted_at').
func (q *Queries) ListTinyIntegrationsWithStaleStockWebhook(ctx context.Context, staleHours int32) ([]ListTinyIntegrationsWithStaleStockWebhookRow, error) {
	rows, err := q.db.Query(ctx, listTinyIntegrationsWithStaleStockWebhook, staleHours)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTinyIntegrationsWithStaleStockWebhookRow{}
	for rows.Next() {
		var i ListTinyIntegrationsWithStaleStockWebhookRow
		if err := rows.Scan(&i.ID, &i.StoreID, &i.LastStockEventAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnprocessedWebhooks = `-- name: ListUnprocessedWebhooks :many
SELECT id, integration_id, provider, event_type, event_id, payload, signature_valid, processed, processed_at, error_message, created_at FROM webhook_events
WHERE integration_id = $1 AND processed = false
ORDER BY created_at ASC
LIMIT $2
`

type ListUnprocessedWebhooksParams struct {
	IntegrationID pgtype.UUID `json:"integration_id"`
	Limit         int32       `json:"limit"`
}

func (q *Queries) ListUnprocessedWebhooks(ctx context.Context, arg ListUnprocessedWebhooksParams) ([]WebhookEvent, error) {
	rows, err := q.db.Query(ctx, listUnprocessedWebhooks, arg.IntegrationID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookEvent{}
	for rows.Next() {
		var i WebhookEvent
		if err := rows.Scan(
			&i.ID,
			&i.IntegrationID,
			&i.Provider,
			&i.EventType,
			&i.EventID,
			&i.Payload,
			&i.SignatureValid,
			&i.Processed,
			&i.ProcessedAt,
			&i.ErrorMessage,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhookEvents = `-- name: ListWebhookEvents :many
SELECT id, integration_id, provider, event_type, event_id, payload, signature_valid, processed, processed_at, error_message, created_at FROM webhook_events
WHERE integration_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListWebhookEventsParams struct {
	IntegrationID pgtype.UUID `json:"integration_id"`
	Limit         int32       `json:"limit"`
	Offset        int32       `json:"offset"`
}

func (q *Queries) ListWebhookEvents(ctx context.Context, arg ListWebhookEventsParams) ([]WebhookEvent, error) {
	rows, err := q.db.Query(ctx, listWebhookEvents, arg.IntegrationID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookEvent{}
	for rows.Next() {
		var i WebhookEvent
		if err := rows.Scan(
			&i.ID,
			&i.IntegrationID,
			&i.Provider,
			&i.EventType,
			&i.EventID,
			&i.Payload,
			&i.SignatureValid,
			&i.Processed,
			&i.ProcessedAt,
			&i.ErrorMessage,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markWebhookFailed = `-- name: MarkWebhookFailed :exec
UPDATE webhook_events
SET processed = true, processed_at = now(), error_message = $2
WHERE id = $1
`

type MarkWebhookFailedParams struct {
	ID           pgtype.UUID `json:"id"`
	ErrorMessage pgtype.Text `json:"error_message"`
}

func (q *Queries) MarkWebhookFailed(ctx context.Context, arg MarkWebhookFailedParams) error {
	_, err := q.db.Exec(ctx, markWebhookFailed, arg.ID, arg.ErrorMessage)
	return err
}

const markWebhookProcessed = `-- name: MarkWebhookProcessed :exec
UPDATE webhook_events
SET processed = true, processed_at = now()
WHERE id = $1
`

func (q *Queries) MarkWebhookProcessed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markWebhookProcessed, id)
	return err
}

const reclaimIdempotencyKey = `-- name: ReclaimIdempotencyKey :execrows
UPDATE idempotency_keys
SET status = 'pending', response_payload = NULL,
    expires_at = now() + interval '24 hours'
WHERE id = $1
  AND (status = 'failed'
       OR (status = 'pending' AND created_at < now() - interval '5 minutes'))
`

// Toma posse (CAS) de uma tentativa anterior: 'failed', ou 'pending' velha o
// bastante para a tentativa dona ter morrido no meio (janela casa com
// stalePendingAfter em lib/idempotency). 0 linhas = outra tentativa chegou
// antes; o chamador vira ErrInFlight, nunca execução dupla.
func (q *Queries) ReclaimIdempotencyKey(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, reclaimIdempotencyKey, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setIntegrationERPAccount = `-- name: SetIntegrationERPAccount :exec
UPDATE integrations
SET erp_account_id = $2
WHERE id = $1
`

type SetIntegrationERPAccountParams struct {
	ID           pgtype.UUID `json:"id"`
	ErpAccountID pgtype.Text `json:"erp_account_id"`
}

// SetIntegrationERPAccount grava a identidade da conta do ERP no fim do OAuth.
func (q *Queries) SetIntegrationERPAccount(ctx context.Context, arg SetIntegrationERPAccountParams) error {
	_, err := q.db.Exec(ctx, setIntegrationERPAccount, arg.ID, arg.ErpAccountID)
	return err
}

const stampIntegrationStockWebhookAlert = `-- name: StampIntegrationStockWebhookAlert :exec
UPDATE integrations
SET metadata = COALESCE(metadata, '{}'::jsonb)
    || jsonb_build_object('stock_webhook_alerted_at', to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'))
WHERE id = $1
`

// Dedupe do alerta acima: carimba o momento no metadata (merge, não replace).
func (q *Queries) StampIntegrationStockWebhookAlert(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, stampIntegrationStockWebhookAlert, id)
	return err
}

const updateIdempotencyKey = `-- name: UpdateIdempotencyKey :exec
UPDATE idempotency_keys
SET response_payload = $2, status = $3
WHERE id = $1
`

type UpdateIdempotencyKeyParams struct {
	ID              pgtype.UUID     `json:"id"`
	ResponsePayload json.RawMessage `json:"response_payload"`
	Status          string          `json:"status"`
}

func (q *Queries) UpdateIdempotencyKey(ctx context.Context, arg UpdateIdempotencyKeyParams) error {
	_, err := q.db.Exec(ctx, updateIdempotencyKey, arg.ID, arg.ResponsePayload, arg.Status)
	return err
}

const updateIntegrationCredentials = `-- name: UpdateIntegrationCredentials :exec
UPDATE integrations
SET credentials = $2, token_expires_at = $3, status = 'active', last_synced_at = now()
WHERE id = $1
`

type UpdateIntegrationCredentialsParams struct {
	ID             pgtype.UUID        `json:"id"`
	Credentials    []byte             `json:"credentials"`
	TokenExpiresAt pgtype.Timestamptz `json:"token_expires_at"`
}

func (q *Queries) UpdateIntegrationCredentials(ctx context.Context, arg UpdateIntegrationCredentialsParams) error {
	_, err := q.db.Exec(ctx, updateIntegrationCredentials, arg.ID, arg.Credentials, arg.TokenExpiresAt)
	return err
}

const updateIntegrationMetadata = `-- name: UpdateIntegrationMetadata :exec
UPDATE integrations
SET metadata = $2
WHERE id = $1
`

type UpdateIntegrationMetadataParams struct {
	ID       pgtype.UUID     `json:"id"`
	Metadata json.RawMessage `json:"metadata"`
}

func (q *Queries) UpdateIntegrationMetadata(ctx context.Context, arg UpdateIntegrationMetadataParams) error {
	_, err := q.db.Exec(ctx, updateIntegrationMetadata, arg.ID, arg.Metadata)
	return err
}

const updateIntegrationPriority = `-- name: UpdateIntegrationPriority :exec
UPDATE integrations
SET priority = $3
WHERE id = $1 AND store_id = $2
`

type UpdateIntegrationPriorityParams struct {
	ID       pgtype.UUID `json:"id"`
	StoreID  pgtype.UUID `json:"store_id"`
	Priority int32       `json:"priority"`
}

// Sets the priority of a single integration for an explicit store. Lower
// number = higher priority in the checkout selection ordering.
func (q *Queries) UpdateIntegrationPriority(ctx context.Context, arg UpdateIntegrationPriorityParams) error {
	_, err := q.db.Exec(ctx, updateIntegrationPriority, arg.ID, arg.StoreID, arg.Priority)
	return err
}

const updateIntegrationStatus = `-- name: UpdateIntegrationStatus :exec
UPDATE integrations
SET status = $2, last_synced_at = now()
WHERE id = $1
`

type UpdateIntegrationStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateIntegrationStatus(ctx context.Context, arg UpdateIntegrationStatusParams) error {
	_, err := q.db.Exec(ctx, updateIntegrationStatus, arg.ID, arg.Status)
	return err
}
