// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: live.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addPlatformToSession = `-- name: AddPlatformToSession :one

INSERT INTO live_session_platforms (session_id, platform, platform_live_id)
VALUES ($1, $2, $3)
RETURNING id, session_id, platform, platform_live_id, added_at
`

type AddPlatformToSessionParams struct {
	SessionID      pgtype.UUID `json:"session_id"`
	Platform       string      `json:"platform"`
	PlatformLiveID string      `json:"platform_live_id"`
}

// =============================================================================
// LIVE SESSION PLATFORMS (multiple platform IDs per session)
// =============================================================================
func (q *Queries) AddPlatformToSession(ctx context.Context, arg AddPlatformToSessionParams) (LiveSessionPlatform, error) {
	row := q.db.QueryRow(ctx, addPlatformToSession, arg.SessionID, arg.Platform, arg.PlatformLiveID)
	var i LiveSessionPlatform
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Platform,
		&i.PlatformLiveID,
		&i.AddedAt,
	)
	return i, err
}

const cancelDetectedOrder = `-- name: CancelDetectedOrder :exec
UPDATE detected_orders
SET cancelled = true
WHERE session_id = $1 AND platform_user_id = $2 AND product_id = $3
`

type CancelDetectedOrderParams struct {
	SessionID      pgtype.UUID `json:"session_id"`
	PlatformUserID string      `json:"platform_user_id"`
	ProductID      pgtype.UUID `json:"product_id"`
}

func (q *Queries) CancelDetectedOrder(ctx context.Context, arg CancelDetectedOrderParams) error {
	_, err := q.db.Exec(ctx, cancelDetectedOrder, arg.SessionID, arg.PlatformUserID, arg.ProductID)
	return err
}

const countPlatformsBySession = `-- name: CountPlatformsBySession :one
SELECT COUNT(*)::int FROM live_session_platforms WHERE session_id = $1
`

func (q *Queries) CountPlatformsBySession(ctx context.Context, sessionID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countPlatformsBySession, sessionID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createLiveSession = `-- name: CreateLiveSession :one
INSERT INTO live_sessions (store_id, title, platform, platform_live_id, status)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, store_id, platform, platform_live_id, status, started_at, ended_at, total_comments, total_orders, title, created_at, updated_at
`

type CreateLiveSessionParams struct {
	StoreID        pgtype.UUID `json:"store_id"`
	Title          pgtype.Text `json:"title"`
	Platform       string      `json:"platform"`
	PlatformLiveID pgtype.Text `json:"platform_live_id"`
	Status         string      `json:"status"`
}

func (q *Queries) CreateLiveSession(ctx context.Context, arg CreateLiveSessionParams) (LiveSession, error) {
	row := q.db.QueryRow(ctx, createLiveSession,
		arg.StoreID,
		arg.Title,
		arg.Platform,
		arg.PlatformLiveID,
		arg.Status,
	)
	var i LiveSession
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.Platform,
		&i.PlatformLiveID,
		&i.Status,
		&i.StartedAt,
		&i.EndedAt,
		&i.TotalComments,
		&i.TotalOrders,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const endLiveSession = `-- name: EndLiveSession :one
UPDATE live_sessions
SET status = 'ended', ended_at = now(), updated_at = now()
WHERE id = $1 AND store_id = $2
RETURNING id, store_id, platform, platform_live_id, status, started_at, ended_at, total_comments, total_orders, title, created_at, updated_at
`

type EndLiveSessionParams struct {
	ID      pgtype.UUID `json:"id"`
	StoreID pgtype.UUID `json:"store_id"`
}

func (q *Queries) EndLiveSession(ctx context.Context, arg EndLiveSessionParams) (LiveSession, error) {
	row := q.db.QueryRow(ctx, endLiveSession, arg.ID, arg.StoreID)
	var i LiveSession
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.Platform,
		&i.PlatformLiveID,
		&i.Status,
		&i.StartedAt,
		&i.EndedAt,
		&i.TotalComments,
		&i.TotalOrders,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveLiveSession = `-- name: GetActiveLiveSession :one
SELECT id, store_id, platform, platform_live_id, status, started_at, ended_at, total_comments, total_orders, title, created_at, updated_at FROM live_sessions
WHERE store_id = $1 AND platform_live_id = $2 AND status = 'active'
`

type GetActiveLiveSessionParams struct {
	StoreID        pgtype.UUID `json:"store_id"`
	PlatformLiveID pgtype.Text `json:"platform_live_id"`
}

func (q *Queries) GetActiveLiveSession(ctx context.Context, arg GetActiveLiveSessionParams) (LiveSession, error) {
	row := q.db.QueryRow(ctx, getActiveLiveSession, arg.StoreID, arg.PlatformLiveID)
	var i LiveSession
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.Platform,
		&i.PlatformLiveID,
		&i.Status,
		&i.StartedAt,
		&i.EndedAt,
		&i.TotalComments,
		&i.TotalOrders,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLiveSessionByID = `-- name: GetLiveSessionByID :one
SELECT id, store_id, platform, platform_live_id, status, started_at, ended_at, total_comments, total_orders, title, created_at, updated_at FROM live_sessions WHERE id = $1 AND store_id = $2
`

type GetLiveSessionByIDParams struct {
	ID      pgtype.UUID `json:"id"`
	StoreID pgtype.UUID `json:"store_id"`
}

func (q *Queries) GetLiveSessionByID(ctx context.Context, arg GetLiveSessionByIDParams) (LiveSession, error) {
	row := q.db.QueryRow(ctx, getLiveSessionByID, arg.ID, arg.StoreID)
	var i LiveSession
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.Platform,
		&i.PlatformLiveID,
		&i.Status,
		&i.StartedAt,
		&i.EndedAt,
		&i.TotalComments,
		&i.TotalOrders,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLiveSessionByPlatformLiveID = `-- name: GetLiveSessionByPlatformLiveID :one
SELECT id, store_id, platform, platform_live_id, status, started_at, ended_at, total_comments, total_orders, title, created_at, updated_at FROM live_sessions
WHERE platform_live_id = $1 AND status IN ('active', 'live')
ORDER BY created_at DESC
LIMIT 1
`

// Busca live session pelo platform_live_id (usado por webhooks Instagram que não têm contexto de store)
func (q *Queries) GetLiveSessionByPlatformLiveID(ctx context.Context, platformLiveID pgtype.Text) (LiveSession, error) {
	row := q.db.QueryRow(ctx, getLiveSessionByPlatformLiveID, platformLiveID)
	var i LiveSession
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.Platform,
		&i.PlatformLiveID,
		&i.Status,
		&i.StartedAt,
		&i.EndedAt,
		&i.TotalComments,
		&i.TotalOrders,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSessionByPlatformLiveID = `-- name: GetSessionByPlatformLiveID :one
SELECT ls.id, ls.store_id, ls.platform, ls.platform_live_id, ls.status, ls.started_at, ls.ended_at, ls.total_comments, ls.total_orders, ls.title, ls.created_at, ls.updated_at
FROM live_sessions ls
JOIN live_session_platforms lsp ON lsp.session_id = ls.id
WHERE lsp.platform_live_id = $1 AND ls.status IN ('active', 'live')
ORDER BY ls.created_at DESC
LIMIT 1
`

// Find active live session by any associated platform_live_id
func (q *Queries) GetSessionByPlatformLiveID(ctx context.Context, platformLiveID string) (LiveSession, error) {
	row := q.db.QueryRow(ctx, getSessionByPlatformLiveID, platformLiveID)
	var i LiveSession
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.Platform,
		&i.PlatformLiveID,
		&i.Status,
		&i.StartedAt,
		&i.EndedAt,
		&i.TotalComments,
		&i.TotalOrders,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementLiveSessionComments = `-- name: IncrementLiveSessionComments :exec
UPDATE live_sessions
SET total_comments = total_comments + 1, updated_at = now()
WHERE id = $1
`

func (q *Queries) IncrementLiveSessionComments(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, incrementLiveSessionComments, id)
	return err
}

const incrementLiveSessionOrders = `-- name: IncrementLiveSessionOrders :exec
UPDATE live_sessions
SET total_orders = total_orders + 1, updated_at = now()
WHERE id = $1
`

func (q *Queries) IncrementLiveSessionOrders(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, incrementLiveSessionOrders, id)
	return err
}

const insertDetectedOrderWithoutProduct = `-- name: InsertDetectedOrderWithoutProduct :one
INSERT INTO detected_orders (session_id, platform_user_id, platform_handle, comment_text, quantity)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (session_id, platform_user_id) WHERE product_id IS NULL
DO UPDATE SET quantity = detected_orders.quantity + EXCLUDED.quantity, comment_text = EXCLUDED.comment_text
RETURNING id, session_id, cart_id, platform_user_id, platform_handle, comment_text, product_id, quantity, cancelled, detected_at
`

type InsertDetectedOrderWithoutProductParams struct {
	SessionID      pgtype.UUID `json:"session_id"`
	PlatformUserID string      `json:"platform_user_id"`
	PlatformHandle string      `json:"platform_handle"`
	CommentText    pgtype.Text `json:"comment_text"`
	Quantity       pgtype.Int4 `json:"quantity"`
}

// Used for Instagram live comments where product_id is unknown
// Updates quantity if an order already exists for this user in this session
func (q *Queries) InsertDetectedOrderWithoutProduct(ctx context.Context, arg InsertDetectedOrderWithoutProductParams) (DetectedOrder, error) {
	row := q.db.QueryRow(ctx, insertDetectedOrderWithoutProduct,
		arg.SessionID,
		arg.PlatformUserID,
		arg.PlatformHandle,
		arg.CommentText,
		arg.Quantity,
	)
	var i DetectedOrder
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.CartID,
		&i.PlatformUserID,
		&i.PlatformHandle,
		&i.CommentText,
		&i.ProductID,
		&i.Quantity,
		&i.Cancelled,
		&i.DetectedAt,
	)
	return i, err
}

const listDetectedOrdersBySession = `-- name: ListDetectedOrdersBySession :many
SELECT id, session_id, cart_id, platform_user_id, platform_handle, comment_text, product_id, quantity, cancelled, detected_at FROM detected_orders
WHERE session_id = $1 AND cancelled = false
ORDER BY detected_at
`

func (q *Queries) ListDetectedOrdersBySession(ctx context.Context, sessionID pgtype.UUID) ([]DetectedOrder, error) {
	rows, err := q.db.Query(ctx, listDetectedOrdersBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DetectedOrder{}
	for rows.Next() {
		var i DetectedOrder
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.CartID,
			&i.PlatformUserID,
			&i.PlatformHandle,
			&i.CommentText,
			&i.ProductID,
			&i.Quantity,
			&i.Cancelled,
			&i.DetectedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDetectedOrdersByUser = `-- name: ListDetectedOrdersByUser :many
SELECT d.id, d.session_id, d.cart_id, d.platform_user_id, d.platform_handle, d.comment_text, d.product_id, d.quantity, d.cancelled, d.detected_at, p.name AS product_name, p.price AS product_price
FROM detected_orders d
JOIN products p ON p.id = d.product_id
WHERE d.session_id = $1 AND d.platform_user_id = $2 AND d.cancelled = false
`

type ListDetectedOrdersByUserParams struct {
	SessionID      pgtype.UUID `json:"session_id"`
	PlatformUserID string      `json:"platform_user_id"`
}

type ListDetectedOrdersByUserRow struct {
	ID             pgtype.UUID        `json:"id"`
	SessionID      pgtype.UUID        `json:"session_id"`
	CartID         pgtype.UUID        `json:"cart_id"`
	PlatformUserID string             `json:"platform_user_id"`
	PlatformHandle string             `json:"platform_handle"`
	CommentText    pgtype.Text        `json:"comment_text"`
	ProductID      pgtype.UUID        `json:"product_id"`
	Quantity       pgtype.Int4        `json:"quantity"`
	Cancelled      pgtype.Bool        `json:"cancelled"`
	DetectedAt     pgtype.Timestamptz `json:"detected_at"`
	ProductName    string             `json:"product_name"`
	ProductPrice   pgtype.Int8        `json:"product_price"`
}

func (q *Queries) ListDetectedOrdersByUser(ctx context.Context, arg ListDetectedOrdersByUserParams) ([]ListDetectedOrdersByUserRow, error) {
	rows, err := q.db.Query(ctx, listDetectedOrdersByUser, arg.SessionID, arg.PlatformUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDetectedOrdersByUserRow{}
	for rows.Next() {
		var i ListDetectedOrdersByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.CartID,
			&i.PlatformUserID,
			&i.PlatformHandle,
			&i.CommentText,
			&i.ProductID,
			&i.Quantity,
			&i.Cancelled,
			&i.DetectedAt,
			&i.ProductName,
			&i.ProductPrice,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDistinctUsersBySession = `-- name: ListDistinctUsersBySession :many
SELECT DISTINCT platform_user_id, platform_handle
FROM detected_orders
WHERE session_id = $1 AND cancelled = false
`

type ListDistinctUsersBySessionRow struct {
	PlatformUserID string `json:"platform_user_id"`
	PlatformHandle string `json:"platform_handle"`
}

func (q *Queries) ListDistinctUsersBySession(ctx context.Context, sessionID pgtype.UUID) ([]ListDistinctUsersBySessionRow, error) {
	rows, err := q.db.Query(ctx, listDistinctUsersBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDistinctUsersBySessionRow{}
	for rows.Next() {
		var i ListDistinctUsersBySessionRow
		if err := rows.Scan(&i.PlatformUserID, &i.PlatformHandle); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLiveSessionsByStore = `-- name: ListLiveSessionsByStore :many
SELECT id, store_id, platform, platform_live_id, status, started_at, ended_at, total_comments, total_orders, title, created_at, updated_at FROM live_sessions WHERE store_id = $1 ORDER BY started_at DESC
`

func (q *Queries) ListLiveSessionsByStore(ctx context.Context, storeID pgtype.UUID) ([]LiveSession, error) {
	rows, err := q.db.Query(ctx, listLiveSessionsByStore, storeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LiveSession{}
	for rows.Next() {
		var i LiveSession
		if err := rows.Scan(
			&i.ID,
			&i.StoreID,
			&i.Platform,
			&i.PlatformLiveID,
			&i.Status,
			&i.StartedAt,
			&i.EndedAt,
			&i.TotalComments,
			&i.TotalOrders,
			&i.Title,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlatformsBySession = `-- name: ListPlatformsBySession :many
SELECT id, session_id, platform, platform_live_id, added_at FROM live_session_platforms
WHERE session_id = $1
ORDER BY added_at
`

func (q *Queries) ListPlatformsBySession(ctx context.Context, sessionID pgtype.UUID) ([]LiveSessionPlatform, error) {
	rows, err := q.db.Query(ctx, listPlatformsBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LiveSessionPlatform{}
	for rows.Next() {
		var i LiveSessionPlatform
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Platform,
			&i.PlatformLiveID,
			&i.AddedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removePlatformFromSession = `-- name: RemovePlatformFromSession :exec
DELETE FROM live_session_platforms
WHERE session_id = $1 AND platform_live_id = $2
`

type RemovePlatformFromSessionParams struct {
	SessionID      pgtype.UUID `json:"session_id"`
	PlatformLiveID string      `json:"platform_live_id"`
}

func (q *Queries) RemovePlatformFromSession(ctx context.Context, arg RemovePlatformFromSessionParams) error {
	_, err := q.db.Exec(ctx, removePlatformFromSession, arg.SessionID, arg.PlatformLiveID)
	return err
}

const startLiveSession = `-- name: StartLiveSession :one
UPDATE live_sessions
SET status = 'live', started_at = now(), updated_at = now()
WHERE id = $1 AND store_id = $2
RETURNING id, store_id, platform, platform_live_id, status, started_at, ended_at, total_comments, total_orders, title, created_at, updated_at
`

type StartLiveSessionParams struct {
	ID      pgtype.UUID `json:"id"`
	StoreID pgtype.UUID `json:"store_id"`
}

func (q *Queries) StartLiveSession(ctx context.Context, arg StartLiveSessionParams) (LiveSession, error) {
	row := q.db.QueryRow(ctx, startLiveSession, arg.ID, arg.StoreID)
	var i LiveSession
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.Platform,
		&i.PlatformLiveID,
		&i.Status,
		&i.StartedAt,
		&i.EndedAt,
		&i.TotalComments,
		&i.TotalOrders,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDetectedOrderCartID = `-- name: UpdateDetectedOrderCartID :exec
UPDATE detected_orders SET cart_id = $2
WHERE session_id = $1 AND platform_user_id = $3 AND cancelled = false
`

type UpdateDetectedOrderCartIDParams struct {
	SessionID      pgtype.UUID `json:"session_id"`
	CartID         pgtype.UUID `json:"cart_id"`
	PlatformUserID string      `json:"platform_user_id"`
}

func (q *Queries) UpdateDetectedOrderCartID(ctx context.Context, arg UpdateDetectedOrderCartIDParams) error {
	_, err := q.db.Exec(ctx, updateDetectedOrderCartID, arg.SessionID, arg.CartID, arg.PlatformUserID)
	return err
}

const updateLiveSession = `-- name: UpdateLiveSession :one
UPDATE live_sessions
SET title = $3, platform = $4, platform_live_id = $5, updated_at = now()
WHERE id = $1 AND store_id = $2
RETURNING id, store_id, platform, platform_live_id, status, started_at, ended_at, total_comments, total_orders, title, created_at, updated_at
`

type UpdateLiveSessionParams struct {
	ID             pgtype.UUID `json:"id"`
	StoreID        pgtype.UUID `json:"store_id"`
	Title          pgtype.Text `json:"title"`
	Platform       string      `json:"platform"`
	PlatformLiveID pgtype.Text `json:"platform_live_id"`
}

func (q *Queries) UpdateLiveSession(ctx context.Context, arg UpdateLiveSessionParams) (LiveSession, error) {
	row := q.db.QueryRow(ctx, updateLiveSession,
		arg.ID,
		arg.StoreID,
		arg.Title,
		arg.Platform,
		arg.PlatformLiveID,
	)
	var i LiveSession
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.Platform,
		&i.PlatformLiveID,
		&i.Status,
		&i.StartedAt,
		&i.EndedAt,
		&i.TotalComments,
		&i.TotalOrders,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertDetectedOrder = `-- name: UpsertDetectedOrder :one
INSERT INTO detected_orders (session_id, platform_user_id, platform_handle, comment_text, product_id, quantity)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (session_id, platform_user_id, product_id)
DO UPDATE SET quantity = detected_orders.quantity + EXCLUDED.quantity, comment_text = EXCLUDED.comment_text
RETURNING id, session_id, cart_id, platform_user_id, platform_handle, comment_text, product_id, quantity, cancelled, detected_at
`

type UpsertDetectedOrderParams struct {
	SessionID      pgtype.UUID `json:"session_id"`
	PlatformUserID string      `json:"platform_user_id"`
	PlatformHandle string      `json:"platform_handle"`
	CommentText    pgtype.Text `json:"comment_text"`
	ProductID      pgtype.UUID `json:"product_id"`
	Quantity       pgtype.Int4 `json:"quantity"`
}

// Used when product_id is known (for upsert behavior)
func (q *Queries) UpsertDetectedOrder(ctx context.Context, arg UpsertDetectedOrderParams) (DetectedOrder, error) {
	row := q.db.QueryRow(ctx, upsertDetectedOrder,
		arg.SessionID,
		arg.PlatformUserID,
		arg.PlatformHandle,
		arg.CommentText,
		arg.ProductID,
		arg.Quantity,
	)
	var i DetectedOrder
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.CartID,
		&i.PlatformUserID,
		&i.PlatformHandle,
		&i.CommentText,
		&i.ProductID,
		&i.Quantity,
		&i.Cancelled,
		&i.DetectedAt,
	)
	return i, err
}
