// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

type Cart struct {
	ID             pgtype.UUID `json:"id"`
	EventID        pgtype.UUID `json:"event_id"`
	PlatformUserID string      `json:"platform_user_id"`
	PlatformHandle string      `json:"platform_handle"`
	Token          string      `json:"token"`
	// Cart status: active (live ongoing, checkout allowed), checkout (live ended), expired, paid
	Status               string             `json:"status"`
	CheckoutUrl          pgtype.Text        `json:"checkout_url"`
	PaymentIntegrationID pgtype.UUID        `json:"payment_integration_id"`
	ExternalOrderID      pgtype.Text        `json:"external_order_id"`
	PaymentStatus        pgtype.Text        `json:"payment_status"`
	PaidAt               pgtype.Timestamptz `json:"paid_at"`
	NotifyStatus         pgtype.Text        `json:"notify_status"`
	NotifyError          pgtype.Text        `json:"notify_error"`
	NotifiedAt           pgtype.Timestamptz `json:"notified_at"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	ExpiresAt            pgtype.Timestamptz `json:"expires_at"`
	// Session where this cart was created. NULL if created outside a session or session was deleted.
	SessionID         pgtype.UUID        `json:"session_id"`
	CheckoutID        pgtype.Text        `json:"checkout_id"`
	CheckoutExpiresAt pgtype.Timestamptz `json:"checkout_expires_at"`
	CustomerEmail     pgtype.Text        `json:"customer_email"`
	PaymentMethod     pgtype.Text        `json:"payment_method"`
	CustomerName      pgtype.Text        `json:"customer_name"`
	CustomerDocument  pgtype.Text        `json:"customer_document"`
	CustomerPhone     pgtype.Text        `json:"customer_phone"`
	ShippingAddress   json.RawMessage    `json:"shipping_address"`
	CustomerID        pgtype.UUID        `json:"customer_id"`
	// Opaque service id returned by the shipping provider (int-as-string for ME, ObjectId/UUID for others)
	ShippingServiceID pgtype.Text `json:"shipping_service_id"`
	// Human name of the service, e.g. PAC, SEDEX, Jadlog .Package
	ShippingServiceName pgtype.Text `json:"shipping_service_name"`
	// Carrier behind the service: Correios, Jadlog, Loggi, etc.
	ShippingCarrier pgtype.Text `json:"shipping_carrier"`
	// What we charge the customer for shipping (zero for free-shipping events)
	ShippingCostCents pgtype.Int8 `json:"shipping_cost_cents"`
	// Actual shipping quote value - what the shipment will cost the merchant
	ShippingCostRealCents pgtype.Int8 `json:"shipping_cost_real_cents"`
	// Estimated maximum delivery time in business days
	ShippingDeadlineDays pgtype.Int4 `json:"shipping_deadline_days"`
	// When the quote was last refreshed. Quotes expire and must be recomputed after ~1h
	ShippingQuotedAt pgtype.Timestamptz `json:"shipping_quoted_at"`
	// Name of the shipping integration that owns this selection: melhor_envio | smartenvios | ...
	ShippingProvider pgtype.Text `json:"shipping_provider"`
	// Snapshot of the options array from the most recent QuoteShipping response — exact shape the public API returned to the customer.
	LastShippingQuoteOptions json.RawMessage `json:"last_shipping_quote_options"`
	// When the snapshot above was generated. Selections older than the cache TTL should force a re-quote on the client.
	LastShippingQuoteAt   pgtype.Timestamptz `json:"last_shipping_quote_at"`
	CardBrand             pgtype.Text        `json:"card_brand"`
	CardLastFour          pgtype.Text        `json:"card_last_four"`
	CardInstallments      pgtype.Int4        `json:"card_installments"`
	CardAuthorizationCode pgtype.Text        `json:"card_authorization_code"`
	// When the initial cart snapshot was frozen (NULL = no checkout view yet).
	InitialSnapshotTakenAt pgtype.Timestamptz `json:"initial_snapshot_taken_at"`
	// Cached subtotal of cart_initial_items in cents.
	InitialSubtotalCents pgtype.Int8 `json:"initial_subtotal_cents"`
	ShortID              int32       `json:"short_id"`
	CouponID             pgtype.UUID `json:"coupon_id"`
	CouponCode           pgtype.Text `json:"coupon_code"`
	CouponDiscountCents  int64       `json:"coupon_discount_cents"`
}

// Immutable per-cart baseline of items present when the buyer first opened checkout.
type CartInitialItem struct {
	CartID    pgtype.UUID `json:"cart_id"`
	ProductID pgtype.UUID `json:"product_id"`
	Quantity  int32       `json:"quantity"`
	UnitPrice int64       `json:"unit_price"`
}

type CartItem struct {
	ID                 pgtype.UUID `json:"id"`
	CartID             pgtype.UUID `json:"cart_id"`
	ProductID          pgtype.UUID `json:"product_id"`
	Quantity           pgtype.Int4 `json:"quantity"`
	UnitPrice          pgtype.Int8 `json:"unit_price"`
	WaitlistedQuantity int32       `json:"waitlisted_quantity"`
}

// Append-only log of cart item mutations during checkout (buyer or merchant driven).
type CartMutation struct {
	ID             pgtype.UUID        `json:"id"`
	CartID         pgtype.UUID        `json:"cart_id"`
	ProductID      pgtype.UUID        `json:"product_id"`
	MutationType   string             `json:"mutation_type"`
	QuantityBefore int32              `json:"quantity_before"`
	QuantityAfter  int32              `json:"quantity_after"`
	UnitPrice      int64              `json:"unit_price"`
	Source         string             `json:"source"`
	ErpMovementID  pgtype.Text        `json:"erp_movement_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Coupon struct {
	ID               pgtype.UUID        `json:"id"`
	EventID          pgtype.UUID        `json:"event_id"`
	Code             string             `json:"code"`
	Type             string             `json:"type"`
	ValueCents       int64              `json:"value_cents"`
	PercentBps       int32              `json:"percent_bps"`
	MaxUses          pgtype.Int4        `json:"max_uses"`
	UsedCount        int32              `json:"used_count"`
	MinPurchaseCents int64              `json:"min_purchase_cents"`
	ValidFrom        pgtype.Timestamptz `json:"valid_from"`
	ValidUntil       pgtype.Timestamptz `json:"valid_until"`
	Active           bool               `json:"active"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type CouponRedemption struct {
	ID                pgtype.UUID        `json:"id"`
	CouponID          pgtype.UUID        `json:"coupon_id"`
	CartID            pgtype.UUID        `json:"cart_id"`
	Status            string             `json:"status"`
	AppliedValueCents int64              `json:"applied_value_cents"`
	ReservedAt        pgtype.Timestamptz `json:"reserved_at"`
	ConfirmedAt       pgtype.Timestamptz `json:"confirmed_at"`
}

type Customer struct {
	ID             pgtype.UUID        `json:"id"`
	StoreID        pgtype.UUID        `json:"store_id"`
	PlatformUserID string             `json:"platform_user_id"`
	PlatformHandle string             `json:"platform_handle"`
	Email          pgtype.Text        `json:"email"`
	Phone          pgtype.Text        `json:"phone"`
	FirstOrderAt   pgtype.Timestamptz `json:"first_order_at"`
	LastOrderAt    pgtype.Timestamptz `json:"last_order_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type ErpContact struct {
	ID                pgtype.UUID        `json:"id"`
	StoreID           pgtype.UUID        `json:"store_id"`
	IntegrationID     pgtype.UUID        `json:"integration_id"`
	PlatformUserID    string             `json:"platform_user_id"`
	PlatformHandle    string             `json:"platform_handle"`
	ExternalContactID string             `json:"external_contact_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

// Product whitelist for events. If empty, all store products are available.
type EventProduct struct {
	ID        pgtype.UUID `json:"id"`
	EventID   pgtype.UUID `json:"event_id"`
	ProductID pgtype.UUID `json:"product_id"`
	// Override price for this event in cents (NULL = use product default)
	SpecialPrice pgtype.Int4 `json:"special_price"`
	// Max quantity per cart for this product in this event
	MaxQuantity  pgtype.Int4 `json:"max_quantity"`
	DisplayOrder int32       `json:"display_order"`
	// Highlighted product in live mode UI
	Featured  bool               `json:"featured"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// Global upsell offers for events, shown after any cart addition.
type EventUpsell struct {
	ID        pgtype.UUID `json:"id"`
	EventID   pgtype.UUID `json:"event_id"`
	ProductID pgtype.UUID `json:"product_id"`
	// Discount percentage (0-100)
	DiscountPercent int32 `json:"discount_percent"`
	// Template with placeholders: {product}, {discount}, {price}
	MessageTemplate pgtype.Text        `json:"message_template"`
	DisplayOrder    int32              `json:"display_order"`
	Active          bool               `json:"active"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

// Global ideas channel posts. Status changes are dev-only via SQL; trigger notifies author.
type Idea struct {
	ID           pgtype.UUID        `json:"id"`
	Number       int64              `json:"number"`
	Title        string             `json:"title"`
	Description  string             `json:"description"`
	Category     string             `json:"category"`
	Status       string             `json:"status"`
	AuthorUserID pgtype.UUID        `json:"author_user_id"`
	VoteCount    int32              `json:"vote_count"`
	CommentCount int32              `json:"comment_count"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type IdeaComment struct {
	ID              pgtype.UUID        `json:"id"`
	IdeaID          pgtype.UUID        `json:"idea_id"`
	ParentCommentID pgtype.UUID        `json:"parent_comment_id"`
	AuthorUserID    pgtype.UUID        `json:"author_user_id"`
	Body            string             `json:"body"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type IdeaVote struct {
	IdeaID    pgtype.UUID        `json:"idea_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type IdempotencyKey struct {
	ID              pgtype.UUID        `json:"id"`
	IdempotencyKey  string             `json:"idempotency_key"`
	StoreID         pgtype.UUID        `json:"store_id"`
	IntegrationID   pgtype.UUID        `json:"integration_id"`
	Operation       string             `json:"operation"`
	RequestHash     pgtype.Text        `json:"request_hash"`
	ResponsePayload json.RawMessage    `json:"response_payload"`
	Status          string             `json:"status"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
}

type Integration struct {
	ID             pgtype.UUID        `json:"id"`
	StoreID        pgtype.UUID        `json:"store_id"`
	Type           string             `json:"type"`
	Provider       string             `json:"provider"`
	Status         string             `json:"status"`
	TokenExpiresAt pgtype.Timestamptz `json:"token_expires_at"`
	LastSyncedAt   pgtype.Timestamptz `json:"last_synced_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	Credentials    []byte             `json:"credentials"`
	Metadata       json.RawMessage    `json:"metadata"`
}

type IntegrationLog struct {
	ID              pgtype.UUID        `json:"id"`
	IntegrationID   pgtype.UUID        `json:"integration_id"`
	EntityType      pgtype.Text        `json:"entity_type"`
	EntityID        pgtype.UUID        `json:"entity_id"`
	Direction       pgtype.Text        `json:"direction"`
	Status          pgtype.Text        `json:"status"`
	RequestPayload  json.RawMessage    `json:"request_payload"`
	ResponsePayload json.RawMessage    `json:"response_payload"`
	ErrorMessage    pgtype.Text        `json:"error_message"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type LiveComment struct {
	ID                pgtype.UUID        `json:"id"`
	SessionID         pgtype.UUID        `json:"session_id"`
	EventID           pgtype.UUID        `json:"event_id"`
	Platform          string             `json:"platform"`
	PlatformCommentID string             `json:"platform_comment_id"`
	PlatformUserID    string             `json:"platform_user_id"`
	PlatformHandle    string             `json:"platform_handle"`
	Text              string             `json:"text"`
	HasPurchaseIntent pgtype.Bool        `json:"has_purchase_intent"`
	MatchedProductID  pgtype.UUID        `json:"matched_product_id"`
	MatchedQuantity   pgtype.Int4        `json:"matched_quantity"`
	Result            pgtype.Text        `json:"result"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

// Container for live sessions. Carts are tied to events, not sessions.
type LiveEvent struct {
	ID      pgtype.UUID `json:"id"`
	StoreID pgtype.UUID `json:"store_id"`
	Title   pgtype.Text `json:"title"`
	// active = event ongoing, ended = checkout finalized
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	TotalOrders int32              `json:"total_orders"`
	// single = one live, auto-end; multi = multiple sessions, manual end
	Type string `json:"type"`
	// If true, cart stops accepting items when event ends
	CloseCartOnEventEnd bool `json:"close_cart_on_event_end"`
	// Override cart expiration (NULL = use store setting)
	CartExpirationMinutes pgtype.Int4 `json:"cart_expiration_minutes"`
	// Override max quantity per item (NULL = use store setting)
	CartMaxQuantityPerItem pgtype.Int4 `json:"cart_max_quantity_per_item"`
	// Override send_on_live_end (NULL = use store setting)
	SendOnLiveEnd pgtype.Bool `json:"send_on_live_end"`
	// Current highlighted product - used as fallback when user comments without keyword
	CurrentActiveProductID pgtype.UUID `json:"current_active_product_id"`
	// When true, comments are stored but not processed into carts
	ProcessingPaused bool `json:"processing_paused"`
	// When the event is scheduled to start (NULL = not scheduled)
	ScheduledAt pgtype.Timestamptz `json:"scheduled_at"`
	// Internal notes about the event
	Description pgtype.Text `json:"description"`
	// When true, charge the customer R$0 shipping regardless of the quoted price (real cost is still recorded on the cart)
	FreeShipping bool `json:"free_shipping"`
}

type LiveSession struct {
	ID            pgtype.UUID        `json:"id"`
	Status        string             `json:"status"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	EndedAt       pgtype.Timestamptz `json:"ended_at"`
	TotalComments pgtype.Int4        `json:"total_comments"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	EventID       pgtype.UUID        `json:"event_id"`
}

type LiveSessionPlatform struct {
	ID             pgtype.UUID        `json:"id"`
	SessionID      pgtype.UUID        `json:"session_id"`
	Platform       string             `json:"platform"`
	PlatformLiveID string             `json:"platform_live_id"`
	AddedAt        pgtype.Timestamptz `json:"added_at"`
}

type Membership struct {
	ID        pgtype.UUID        `json:"id"`
	StoreID   pgtype.UUID        `json:"store_id"`
	Role      string             `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	Status    string             `json:"status"`
	InvitedBy pgtype.UUID        `json:"invited_by"`
	InvitedAt pgtype.Timestamptz `json:"invited_at"`
	UserID    pgtype.UUID        `json:"user_id"`
}

// In-app dashboard notifications. Distinct from notification_logs (outbound to buyers).
type Notification struct {
	ID          pgtype.UUID        `json:"id"`
	RecipientID pgtype.UUID        `json:"recipient_id"`
	ActorID     pgtype.UUID        `json:"actor_id"`
	Type        string             `json:"type"`
	IdeaID      pgtype.UUID        `json:"idea_id"`
	CommentID   pgtype.UUID        `json:"comment_id"`
	Payload     json.RawMessage    `json:"payload"`
	ReadAt      pgtype.Timestamptz `json:"read_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

// Tracks all notification attempts for analytics and preventing duplicates
type NotificationLog struct {
	ID               pgtype.UUID        `json:"id"`
	StoreID          pgtype.UUID        `json:"store_id"`
	EventID          pgtype.UUID        `json:"event_id"`
	CartID           pgtype.UUID        `json:"cart_id"`
	PlatformUserID   string             `json:"platform_user_id"`
	PlatformHandle   pgtype.Text        `json:"platform_handle"`
	NotificationType string             `json:"notification_type"`
	Channel          string             `json:"channel"`
	Status           string             `json:"status"`
	MessageText      pgtype.Text        `json:"message_text"`
	ErrorMessage     pgtype.Text        `json:"error_message"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	SentAt           pgtype.Timestamptz `json:"sent_at"`
}

// Temporary storage for OAuth PKCE code_verifier during authorization flow
type OauthState struct {
	State        string             `json:"state"`
	StoreID      pgtype.UUID        `json:"store_id"`
	Provider     string             `json:"provider"`
	CodeVerifier string             `json:"code_verifier"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
}

type Payment struct {
	ID                pgtype.UUID        `json:"id"`
	CartID            pgtype.UUID        `json:"cart_id"`
	IntegrationID     pgtype.UUID        `json:"integration_id"`
	ExternalPaymentID pgtype.Text        `json:"external_payment_id"`
	Provider          string             `json:"provider"`
	AmountCents       int64              `json:"amount_cents"`
	Currency          pgtype.Text        `json:"currency"`
	Method            pgtype.Text        `json:"method"`
	Status            string             `json:"status"`
	StatusDetail      pgtype.Text        `json:"status_detail"`
	ProviderResponse  json.RawMessage    `json:"provider_response"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	PaidAt            pgtype.Timestamptz `json:"paid_at"`
	IdempotencyKey    pgtype.Text        `json:"idempotency_key"`
}

type Product struct {
	ID             pgtype.UUID        `json:"id"`
	StoreID        pgtype.UUID        `json:"store_id"`
	Name           string             `json:"name"`
	ExternalID     pgtype.Text        `json:"external_id"`
	ExternalSource string             `json:"external_source"`
	Keyword        string             `json:"keyword"`
	Price          pgtype.Int8        `json:"price"`
	ImageUrl       pgtype.Text        `json:"image_url"`
	Stock          pgtype.Int4        `json:"stock"`
	Active         pgtype.Bool        `json:"active"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	// Product weight in grams (packaged individually). Required to quote shipping.
	WeightGrams pgtype.Int4 `json:"weight_grams"`
	// Product height in cm (packaged individually). Required to quote shipping.
	HeightCm pgtype.Int4 `json:"height_cm"`
	// Product width in cm (packaged individually). Required to quote shipping.
	WidthCm pgtype.Int4 `json:"width_cm"`
	// Product length in cm (packaged individually). Required to quote shipping.
	LengthCm pgtype.Int4 `json:"length_cm"`
	// Full SKU used by ERP and shipping labels (distinct from short keyword).
	Sku pgtype.Text `json:"sku"`
	// Shape hint for carriers: box (default), roll (tube), letter (envelope).
	PackageFormat string `json:"package_format"`
	// Declared value for shipping insurance, in cents. Falls back to product price when NULL.
	InsuranceValueCents pgtype.Int8 `json:"insurance_value_cents"`
	// FK to product_groups when this product is a variant; NULL for simple products.
	GroupID pgtype.UUID `json:"group_id"`
}

// Catalog aggregator over `products` (variants). NULL group_id = simple product.
type ProductGroup struct {
	ID             pgtype.UUID        `json:"id"`
	StoreID        pgtype.UUID        `json:"store_id"`
	Name           string             `json:"name"`
	Description    pgtype.Text        `json:"description"`
	ExternalID     pgtype.Text        `json:"external_id"`
	ExternalSource string             `json:"external_source"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

// Per-group gallery (generic photos shared by all variants).
type ProductGroupImage struct {
	ID        pgtype.UUID        `json:"id"`
	GroupID   pgtype.UUID        `json:"group_id"`
	Url       string             `json:"url"`
	Position  int32              `json:"position"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// Per-variant gallery (in addition to products.image_url thumbnail).
type ProductImage struct {
	ID        pgtype.UUID        `json:"id"`
	ProductID pgtype.UUID        `json:"product_id"`
	Url       string             `json:"url"`
	Position  int32              `json:"position"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// Variation dimensions of a group (e.g. Color, Size).
type ProductOption struct {
	ID       pgtype.UUID `json:"id"`
	GroupID  pgtype.UUID `json:"group_id"`
	Name     string      `json:"name"`
	Position int32       `json:"position"`
}

// Allowed values for a given option (e.g. Red, Blue / S, M, L).
type ProductOptionValue struct {
	ID       pgtype.UUID `json:"id"`
	OptionID pgtype.UUID `json:"option_id"`
	Value    string      `json:"value"`
	Position int32       `json:"position"`
}

// Junction: which option values define each variant. Uniqueness of the value combination per group is enforced in service layer.
type ProductVariantOption struct {
	ProductID     pgtype.UUID `json:"product_id"`
	OptionValueID pgtype.UUID `json:"option_value_id"`
}

// Provider-agnostic freight orders linked to carts. One row per shipment created at a carrier.
type Shipment struct {
	ID                  pgtype.UUID        `json:"id"`
	OrderID             pgtype.UUID        `json:"order_id"`
	StoreID             pgtype.UUID        `json:"store_id"`
	Provider            string             `json:"provider"`
	ProviderOrderID     string             `json:"provider_order_id"`
	ProviderOrderNumber pgtype.Text        `json:"provider_order_number"`
	TrackingCode        pgtype.Text        `json:"tracking_code"`
	PublicTrackingUrl   pgtype.Text        `json:"public_tracking_url"`
	InvoiceKey          pgtype.Text        `json:"invoice_key"`
	InvoiceKind         pgtype.Text        `json:"invoice_kind"`
	InvoiceID           pgtype.Text        `json:"invoice_id"`
	LabelUrl            pgtype.Text        `json:"label_url"`
	Status              string             `json:"status"`
	StatusRawCode       pgtype.Int4        `json:"status_raw_code"`
	StatusRawName       pgtype.Text        `json:"status_raw_name"`
	ProviderMeta        json.RawMessage    `json:"provider_meta"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

// Append-only timeline of tracking events per shipment. Source = poll (pull) | webhook (future).
type ShipmentTrackingEvent struct {
	ID          pgtype.UUID        `json:"id"`
	ShipmentID  pgtype.UUID        `json:"shipment_id"`
	Status      string             `json:"status"`
	RawCode     pgtype.Int4        `json:"raw_code"`
	RawName     pgtype.Text        `json:"raw_name"`
	Observation pgtype.Text        `json:"observation"`
	EventAt     pgtype.Timestamptz `json:"event_at"`
	ReceivedAt  pgtype.Timestamptz `json:"received_at"`
	Source      string             `json:"source"`
}

type StockReservation struct {
	ID                pgtype.UUID        `json:"id"`
	EventID           pgtype.UUID        `json:"event_id"`
	CartID            pgtype.UUID        `json:"cart_id"`
	ProductID         pgtype.UUID        `json:"product_id"`
	ExternalProductID string             `json:"external_product_id"`
	Quantity          int32              `json:"quantity"`
	ErpMovementID     pgtype.Text        `json:"erp_movement_id"`
	Status            string             `json:"status"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	ReversedAt        pgtype.Timestamptz `json:"reversed_at"`
}

type Store struct {
	ID             pgtype.UUID        `json:"id"`
	Name           string             `json:"name"`
	Slug           string             `json:"slug"`
	Active         pgtype.Bool        `json:"active"`
	WhatsappNumber pgtype.Text        `json:"whatsapp_number"`
	EmailAddress   pgtype.Text        `json:"email_address"`
	SmsNumber      pgtype.Text        `json:"sms_number"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	// Whether the cart system is enabled for this store
	CartEnabled bool `json:"cart_enabled"`
	// Minutes before cart expires (0 = no expiration)
	CartExpirationMinutes int32 `json:"cart_expiration_minutes"`
	// Reserve stock when item is added to cart
	CartReserveStock bool `json:"cart_reserve_stock"`
	// Max different items per cart (0 = unlimited)
	CartMaxItems int32 `json:"cart_max_items"`
	// Max quantity of same item (0 = unlimited)
	CartMaxQuantityPerItem int32              `json:"cart_max_quantity_per_item"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	// Store description/bio for public display
	Description pgtype.Text `json:"description"`
	// Store external website URL
	Website pgtype.Text `json:"website"`
	// Store logo image URL
	LogoUrl pgtype.Text `json:"logo_url"`
	// Store street address
	AddressStreet pgtype.Text `json:"address_street"`
	// Store city
	AddressCity pgtype.Text `json:"address_city"`
	// Store state/province
	AddressState pgtype.Text `json:"address_state"`
	// Store postal/ZIP code
	AddressZip pgtype.Text `json:"address_zip"`
	// Store country
	AddressCountry pgtype.Text `json:"address_country"`
	// When true, automatically sends checkout links when live ends.
	SendOnLiveEnd bool `json:"send_on_live_end"`
	// Allow customers to edit cart (remove items, change quantity) on checkout page
	CartAllowEdit       bool            `json:"cart_allow_edit"`
	CheckoutSendMethods json.RawMessage `json:"checkout_send_methods"`
	// JSON settings for automatic notifications: templates, triggers, cooldown
	NotificationSettings json.RawMessage `json:"notification_settings"`
	// Minimum interval between automatic messages in seconds
	CartMessageCooldownSeconds int32 `json:"cart_message_cooldown_seconds"`
	// Send reminder message before cart expires
	CartSendExpirationReminder bool `json:"cart_send_expiration_reminder"`
	// Minutes before expiration to send reminder
	CartExpirationReminderMinutes int32 `json:"cart_expiration_reminder_minutes"`
	// When true, sends message every time customer adds item. When false, only sends at end of live.
	CartRealTime bool `json:"cart_real_time"`
	// Store CNPJ (Brazilian tax ID) - format: XX.XXX.XXX/XXXX-XX
	Cnpj pgtype.Text `json:"cnpj"`
	// Street number of the shipping origin address
	AddressNumber pgtype.Text `json:"address_number"`
	// Optional address complement (suite, floor, etc.) of the shipping origin
	AddressComplement pgtype.Text `json:"address_complement"`
	// Neighborhood/bairro of the shipping origin address
	AddressDistrict pgtype.Text `json:"address_district"`
	// Inscricao estadual of the store (optional, may be ISENTO)
	AddressStateRegister pgtype.Text `json:"address_state_register"`
	// Weight in grams of the consolidating package (empty box, bubble wrap) added once per shipment
	DefaultPackageWeightGrams int32 `json:"default_package_weight_grams"`
	// Default package format for shipping: box, roll or letter
	DefaultPackageFormat string `json:"default_package_format"`
	// Default package height (cm) for ERP imports that only carry weight. Combined with default_width_cm and default_length_cm.
	DefaultHeightCm pgtype.Int4 `json:"default_height_cm"`
	// Default package width (cm) for ERP imports that only carry weight.
	DefaultWidthCm pgtype.Int4 `json:"default_width_cm"`
	// Default package length (cm) for ERP imports that only carry weight.
	DefaultLengthCm pgtype.Int4 `json:"default_length_cm"`
}

type StoreInvitation struct {
	ID         pgtype.UUID        `json:"id"`
	StoreID    pgtype.UUID        `json:"store_id"`
	Email      string             `json:"email"`
	Role       string             `json:"role"`
	Token      string             `json:"token"`
	InvitedBy  pgtype.UUID        `json:"invited_by"`
	Status     string             `json:"status"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	AcceptedAt pgtype.Timestamptz `json:"accepted_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type StoreOrderCounter struct {
	StoreID   pgtype.UUID `json:"store_id"`
	LastValue int32       `json:"last_value"`
}

type Subscription struct {
	ID                     pgtype.UUID        `json:"id"`
	StoreID                pgtype.UUID        `json:"store_id"`
	IntegrationID          pgtype.UUID        `json:"integration_id"`
	ExternalSubscriptionID pgtype.Text        `json:"external_subscription_id"`
	Status                 string             `json:"status"`
	CurrentPeriodStart     pgtype.Timestamptz `json:"current_period_start"`
	CurrentPeriodEnd       pgtype.Timestamptz `json:"current_period_end"`
	CancelledAt            pgtype.Timestamptz `json:"cancelled_at"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID        pgtype.UUID        `json:"id"`
	ClerkID   string             `json:"clerk_id"`
	Email     string             `json:"email"`
	Name      pgtype.Text        `json:"name"`
	AvatarUrl pgtype.Text        `json:"avatar_url"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type WaitlistItem struct {
	ID             pgtype.UUID        `json:"id"`
	EventID        pgtype.UUID        `json:"event_id"`
	ProductID      pgtype.UUID        `json:"product_id"`
	PlatformUserID string             `json:"platform_user_id"`
	PlatformHandle string             `json:"platform_handle"`
	Quantity       int32              `json:"quantity"`
	Position       int32              `json:"position"`
	Status         string             `json:"status"`
	NotifiedAt     pgtype.Timestamptz `json:"notified_at"`
	FulfilledAt    pgtype.Timestamptz `json:"fulfilled_at"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type WebhookEvent struct {
	ID             pgtype.UUID        `json:"id"`
	IntegrationID  pgtype.UUID        `json:"integration_id"`
	Provider       string             `json:"provider"`
	EventType      string             `json:"event_type"`
	EventID        pgtype.Text        `json:"event_id"`
	Payload        json.RawMessage    `json:"payload"`
	SignatureValid pgtype.Bool        `json:"signature_valid"`
	Processed      bool               `json:"processed"`
	ProcessedAt    pgtype.Timestamptz `json:"processed_at"`
	ErrorMessage   pgtype.Text        `json:"error_message"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}
