// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notification.sql

package sqlc

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const countNotificationsByStatus = `-- name: CountNotificationsByStatus :one
SELECT
    COUNT(*) FILTER (WHERE status = 'sent')::int AS sent,
    COUNT(*) FILTER (WHERE status = 'failed')::int AS failed,
    COUNT(*) FILTER (WHERE status = 'cooldown')::int AS cooldown_skipped
FROM notification_logs
WHERE store_id = $1 AND created_at > $2
`

type CountNotificationsByStatusParams struct {
	StoreID   pgtype.UUID        `json:"store_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type CountNotificationsByStatusRow struct {
	Sent            int32 `json:"sent"`
	Failed          int32 `json:"failed"`
	CooldownSkipped int32 `json:"cooldown_skipped"`
}

// Count notifications by status for a store
func (q *Queries) CountNotificationsByStatus(ctx context.Context, arg CountNotificationsByStatusParams) (CountNotificationsByStatusRow, error) {
	row := q.db.QueryRow(ctx, countNotificationsByStatus, arg.StoreID, arg.CreatedAt)
	var i CountNotificationsByStatusRow
	err := row.Scan(&i.Sent, &i.Failed, &i.CooldownSkipped)
	return i, err
}

const createEmailNotificationLog = `-- name: CreateEmailNotificationLog :exec
INSERT INTO notification_logs (
    store_id, event_id, cart_id, platform_user_id,
    notification_type, channel, status, message_text,
    error_message, provider_message_id, sent_at
)
VALUES ($1, $2, $3, $4, $5, 'email', $6, $7, $8, $9, $10)
`

type CreateEmailNotificationLogParams struct {
	StoreID           pgtype.UUID        `json:"store_id"`
	EventID           pgtype.UUID        `json:"event_id"`
	CartID            pgtype.UUID        `json:"cart_id"`
	PlatformUserID    string             `json:"platform_user_id"`
	NotificationType  string             `json:"notification_type"`
	Status            string             `json:"status"`
	MessageText       pgtype.Text        `json:"message_text"`
	ErrorMessage      pgtype.Text        `json:"error_message"`
	ProviderMessageID pgtype.Text        `json:"provider_message_id"`
	SentAt            pgtype.Timestamptz `json:"sent_at"`
}

// Trilha unificada de auditoria de e-mails (lib/email): uma linha por
// tentativa de envio (sent/failed/skipped), na mesma tabela dos DMs/WhatsApp.
// platform_user_id carrega o e-mail do destinatário (identidade no canal).
func (q *Queries) CreateEmailNotificationLog(ctx context.Context, arg CreateEmailNotificationLogParams) error {
	_, err := q.db.Exec(ctx, createEmailNotificationLog,
		arg.StoreID,
		arg.EventID,
		arg.CartID,
		arg.PlatformUserID,
		arg.NotificationType,
		arg.Status,
		arg.MessageText,
		arg.ErrorMessage,
		arg.ProviderMessageID,
		arg.SentAt,
	)
	return err
}

const createNotificationLog = `-- name: CreateNotificationLog :one

INSERT INTO notification_logs (
    store_id, event_id, cart_id, platform_user_id, platform_handle,
    notification_type, channel, status, message_text
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, store_id, event_id, cart_id, platform_user_id, platform_handle, notification_type, channel, status, message_text, error_message, created_at, sent_at, provider_message_id, undelivered_reason
`

type CreateNotificationLogParams struct {
	StoreID          pgtype.UUID `json:"store_id"`
	EventID          pgtype.UUID `json:"event_id"`
	CartID           pgtype.UUID `json:"cart_id"`
	PlatformUserID   string      `json:"platform_user_id"`
	PlatformHandle   pgtype.Text `json:"platform_handle"`
	NotificationType string      `json:"notification_type"`
	Channel          string      `json:"channel"`
	Status           string      `json:"status"`
	MessageText      pgtype.Text `json:"message_text"`
}

// =============================================================================
// NOTIFICATION LOGS
// =============================================================================
func (q *Queries) CreateNotificationLog(ctx context.Context, arg CreateNotificationLogParams) (NotificationLog, error) {
	row := q.db.QueryRow(ctx, createNotificationLog,
		arg.StoreID,
		arg.EventID,
		arg.CartID,
		arg.PlatformUserID,
		arg.PlatformHandle,
		arg.NotificationType,
		arg.Channel,
		arg.Status,
		arg.MessageText,
	)
	var i NotificationLog
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.EventID,
		&i.CartID,
		&i.PlatformUserID,
		&i.PlatformHandle,
		&i.NotificationType,
		&i.Channel,
		&i.Status,
		&i.MessageText,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.SentAt,
		&i.ProviderMessageID,
		&i.UndeliveredReason,
	)
	return i, err
}

const findPendingPublicNudge = `-- name: FindPendingPublicNudge :one
SELECT nl.id, c.token
FROM notification_logs nl
JOIN carts c ON c.id = nl.cart_id
WHERE nl.store_id = $1
  AND nl.platform_user_id = $2
  AND nl.undelivered_reason = 'nudged_publicly'
  AND nl.status = 'undelivered'
  AND c.status IN ('pending', 'active', 'checkout')
  AND (c.payment_status IS NULL OR c.payment_status NOT IN ('paid', 'refunded'))
ORDER BY nl.created_at DESC
LIMIT 1
`

type FindPendingPublicNudgeParams struct {
	StoreID        pgtype.UUID `json:"store_id"`
	PlatformUserID string      `json:"platform_user_id"`
}

type FindPendingPublicNudgeRow struct {
	ID    pgtype.UUID `json:"id"`
	Token string      `json:"token"`
}

// O convite público em aberto deste comprador, com o token do carrinho a
// entregar.
//
// É a guarda do caminho "comprador respondeu ao convite": só recebe o link quem
// foi chamado ao direct e ainda não foi atendido. Sem ela, toda mensagem que o
// comprador mandasse — inclusive conversa comum — devolveria o link de novo.
//
// Uma linha por convite; ao entregar, o log vira 'sent' e esta busca deixa de
// encontrá-lo. É o que torna a entrega única sem precisar de estado novo.
func (q *Queries) FindPendingPublicNudge(ctx context.Context, arg FindPendingPublicNudgeParams) (FindPendingPublicNudgeRow, error) {
	row := q.db.QueryRow(ctx, findPendingPublicNudge, arg.StoreID, arg.PlatformUserID)
	var i FindPendingPublicNudgeRow
	err := row.Scan(&i.ID, &i.Token)
	return i, err
}

const findStoreByActiveTestSetupCode = `-- name: FindStoreByActiveTestSetupCode :one
SELECT id
FROM stores
WHERE notification_test_setup_code = $1
  AND notification_test_setup_expires_at IS NOT NULL
  AND notification_test_setup_expires_at > now()
LIMIT 1
`

// Looks up the store that owns a non-expired setup code. Used by the IG
// webhook handler to route an incoming DM to the right store.
func (q *Queries) FindStoreByActiveTestSetupCode(ctx context.Context, notificationTestSetupCode pgtype.Text) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, findStoreByActiveTestSetupCode, notificationTestSetupCode)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getLastNotificationForUser = `-- name: GetLastNotificationForUser :one
SELECT id, store_id, event_id, cart_id, platform_user_id, platform_handle, notification_type, channel, status, message_text, error_message, created_at, sent_at, provider_message_id, undelivered_reason FROM notification_logs
WHERE store_id = $1 AND platform_user_id = $2 AND status = 'sent'
ORDER BY created_at DESC
LIMIT 1
`

type GetLastNotificationForUserParams struct {
	StoreID        pgtype.UUID `json:"store_id"`
	PlatformUserID string      `json:"platform_user_id"`
}

// Returns the most recent notification for a user in a store (for cooldown check)
func (q *Queries) GetLastNotificationForUser(ctx context.Context, arg GetLastNotificationForUserParams) (NotificationLog, error) {
	row := q.db.QueryRow(ctx, getLastNotificationForUser, arg.StoreID, arg.PlatformUserID)
	var i NotificationLog
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.EventID,
		&i.CartID,
		&i.PlatformUserID,
		&i.PlatformHandle,
		&i.NotificationType,
		&i.Channel,
		&i.Status,
		&i.MessageText,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.SentAt,
		&i.ProviderMessageID,
		&i.UndeliveredReason,
	)
	return i, err
}

const getNotificationByCartAndType = `-- name: GetNotificationByCartAndType :one
SELECT id, store_id, event_id, cart_id, platform_user_id, platform_handle, notification_type, channel, status, message_text, error_message, created_at, sent_at, provider_message_id, undelivered_reason FROM notification_logs
WHERE cart_id = $1 AND notification_type = $2 AND status = 'sent'
LIMIT 1
`

type GetNotificationByCartAndTypeParams struct {
	CartID           pgtype.UUID `json:"cart_id"`
	NotificationType string      `json:"notification_type"`
}

// Check if a notification of this type was already sent for this cart
func (q *Queries) GetNotificationByCartAndType(ctx context.Context, arg GetNotificationByCartAndTypeParams) (NotificationLog, error) {
	row := q.db.QueryRow(ctx, getNotificationByCartAndType, arg.CartID, arg.NotificationType)
	var i NotificationLog
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.EventID,
		&i.CartID,
		&i.PlatformUserID,
		&i.PlatformHandle,
		&i.NotificationType,
		&i.Channel,
		&i.Status,
		&i.MessageText,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.SentAt,
		&i.ProviderMessageID,
		&i.UndeliveredReason,
	)
	return i, err
}

const getStoreCartMessageSettings = `-- name: GetStoreCartMessageSettings :one
SELECT
    cart_real_time,
    cart_message_cooldown_seconds,
    cart_send_expiration_reminder,
    cart_expiration_reminder_minutes
FROM stores WHERE id = $1
`

type GetStoreCartMessageSettingsRow struct {
	CartRealTime                  bool  `json:"cart_real_time"`
	CartMessageCooldownSeconds    int32 `json:"cart_message_cooldown_seconds"`
	CartSendExpirationReminder    bool  `json:"cart_send_expiration_reminder"`
	CartExpirationReminderMinutes int32 `json:"cart_expiration_reminder_minutes"`
}

// Returns cart message settings for notification triggers
func (q *Queries) GetStoreCartMessageSettings(ctx context.Context, id pgtype.UUID) (GetStoreCartMessageSettingsRow, error) {
	row := q.db.QueryRow(ctx, getStoreCartMessageSettings, id)
	var i GetStoreCartMessageSettingsRow
	err := row.Scan(
		&i.CartRealTime,
		&i.CartMessageCooldownSeconds,
		&i.CartSendExpirationReminder,
		&i.CartExpirationReminderMinutes,
	)
	return i, err
}

const getStoreNotificationSettings = `-- name: GetStoreNotificationSettings :one

SELECT notification_settings FROM stores WHERE id = $1
`

// =============================================================================
// STORE NOTIFICATION SETTINGS
// =============================================================================
func (q *Queries) GetStoreNotificationSettings(ctx context.Context, id pgtype.UUID) (json.RawMessage, error) {
	row := q.db.QueryRow(ctx, getStoreNotificationSettings, id)
	var notification_settings json.RawMessage
	err := row.Scan(&notification_settings)
	return notification_settings, err
}

const getStoreTestRecipient = `-- name: GetStoreTestRecipient :one

SELECT
    notification_test_recipient_psid,
    notification_test_recipient_handle,
    notification_test_setup_code,
    notification_test_setup_expires_at
FROM stores WHERE id = $1
`

type GetStoreTestRecipientRow struct {
	NotificationTestRecipientPsid   pgtype.Text        `json:"notification_test_recipient_psid"`
	NotificationTestRecipientHandle pgtype.Text        `json:"notification_test_recipient_handle"`
	NotificationTestSetupCode       pgtype.Text        `json:"notification_test_setup_code"`
	NotificationTestSetupExpiresAt  pgtype.Timestamptz `json:"notification_test_setup_expires_at"`
}

// =============================================================================
// TEST RECIPIENT (for "Testar notificação" feature)
// =============================================================================
// Returns the configured test recipient and any active setup code for the store.
func (q *Queries) GetStoreTestRecipient(ctx context.Context, id pgtype.UUID) (GetStoreTestRecipientRow, error) {
	row := q.db.QueryRow(ctx, getStoreTestRecipient, id)
	var i GetStoreTestRecipientRow
	err := row.Scan(
		&i.NotificationTestRecipientPsid,
		&i.NotificationTestRecipientHandle,
		&i.NotificationTestSetupCode,
		&i.NotificationTestSetupExpiresAt,
	)
	return i, err
}

const listNotificationsByEvent = `-- name: ListNotificationsByEvent :many
SELECT id, store_id, event_id, cart_id, platform_user_id, platform_handle, notification_type, channel, status, message_text, error_message, created_at, sent_at, provider_message_id, undelivered_reason FROM notification_logs
WHERE event_id = $1
ORDER BY created_at DESC
`

// List all notifications for an event (for analytics)
func (q *Queries) ListNotificationsByEvent(ctx context.Context, eventID pgtype.UUID) ([]NotificationLog, error) {
	rows, err := q.db.Query(ctx, listNotificationsByEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationLog{}
	for rows.Next() {
		var i NotificationLog
		if err := rows.Scan(
			&i.ID,
			&i.StoreID,
			&i.EventID,
			&i.CartID,
			&i.PlatformUserID,
			&i.PlatformHandle,
			&i.NotificationType,
			&i.Channel,
			&i.Status,
			&i.MessageText,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.SentAt,
			&i.ProviderMessageID,
			&i.UndeliveredReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationsByStore = `-- name: ListNotificationsByStore :many
SELECT id, store_id, event_id, cart_id, platform_user_id, platform_handle, notification_type, channel, status, message_text, error_message, created_at, sent_at, provider_message_id, undelivered_reason FROM notification_logs
WHERE store_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListNotificationsByStoreParams struct {
	StoreID pgtype.UUID `json:"store_id"`
	Limit   int32       `json:"limit"`
}

// List recent notifications for a store
func (q *Queries) ListNotificationsByStore(ctx context.Context, arg ListNotificationsByStoreParams) ([]NotificationLog, error) {
	rows, err := q.db.Query(ctx, listNotificationsByStore, arg.StoreID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationLog{}
	for rows.Next() {
		var i NotificationLog
		if err := rows.Scan(
			&i.ID,
			&i.StoreID,
			&i.EventID,
			&i.CartID,
			&i.PlatformUserID,
			&i.PlatformHandle,
			&i.NotificationType,
			&i.Channel,
			&i.Status,
			&i.MessageText,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.SentAt,
			&i.ProviderMessageID,
			&i.UndeliveredReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUndeliveredByEvent = `-- name: ListUndeliveredByEvent :many
SELECT DISTINCT ON (nl.platform_user_id)
    nl.id,
    nl.platform_user_id,
    nl.platform_handle,
    nl.notification_type,
    nl.undelivered_reason,
    nl.created_at,
    nl.cart_id,
    c.token AS cart_token,
    COALESCE(cart_product_total_cents(c.id), 0)::bigint AS cart_total_cents,
    COALESCE((SELECT SUM(ci.quantity)::int FROM cart_items ci WHERE ci.cart_id = c.id), 0)::int AS cart_total_items
FROM notification_logs nl
LEFT JOIN carts c ON c.id = nl.cart_id
WHERE nl.store_id = $1
  AND nl.event_id = $2
  AND nl.undelivered_reason IS NOT NULL
ORDER BY nl.platform_user_id, nl.created_at DESC
`

type ListUndeliveredByEventParams struct {
	StoreID pgtype.UUID `json:"store_id"`
	EventID pgtype.UUID `json:"event_id"`
}

type ListUndeliveredByEventRow struct {
	ID                pgtype.UUID        `json:"id"`
	PlatformUserID    string             `json:"platform_user_id"`
	PlatformHandle    pgtype.Text        `json:"platform_handle"`
	NotificationType  string             `json:"notification_type"`
	UndeliveredReason pgtype.Text        `json:"undelivered_reason"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	CartID            pgtype.UUID        `json:"cart_id"`
	CartToken         pgtype.Text        `json:"cart_token"`
	CartTotalCents    int64              `json:"cart_total_cents"`
	CartTotalItems    int32              `json:"cart_total_items"`
}

// RN-38 — os compradores que nao puderam ser avisados nesta campanha, um por
// linha, com o carrinho e o link para o lojista chamar na mao.
//
// O filtro e undelivered_reason IS NOT NULL, e nao status = 'undelivered', de
// proposito: a lista tem de conter tambem o que foi TENTADO e recusado pelo
// Instagram (status 'failed' + motivo). O status continua distinguindo
// "nem tentamos" de "tentamos e recusaram"; quem responde "quem eu preciso
// chamar na mao" e a coluna de motivo.
//
// DISTINCT ON por comprador: uma campanha longa pode ter varias mensagens nao
// entregues para a MESMA pessoa (o prazo do Instagram fechou para ela, entao
// fecha para tudo). Listar cada tentativa transformaria a lista de "quem
// chamar" numa lista de log — o lojista precisa de pessoas, nao de eventos.
func (q *Queries) ListUndeliveredByEvent(ctx context.Context, arg ListUndeliveredByEventParams) ([]ListUndeliveredByEventRow, error) {
	rows, err := q.db.Query(ctx, listUndeliveredByEvent, arg.StoreID, arg.EventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUndeliveredByEventRow{}
	for rows.Next() {
		var i ListUndeliveredByEventRow
		if err := rows.Scan(
			&i.ID,
			&i.PlatformUserID,
			&i.PlatformHandle,
			&i.NotificationType,
			&i.UndeliveredReason,
			&i.CreatedAt,
			&i.CartID,
			&i.CartToken,
			&i.CartTotalCents,
			&i.CartTotalItems,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNotificationUndelivered = `-- name: MarkNotificationUndelivered :exec
UPDATE notification_logs
SET status = 'undelivered',
    undelivered_reason = $2
WHERE id = $1
`

type MarkNotificationUndeliveredParams struct {
	ID                pgtype.UUID `json:"id"`
	UndeliveredReason pgtype.Text `json:"undelivered_reason"`
}

// RN-38 — nem tentamos, porque a regra do Instagram ja fechava a porta.
// sent_at fica NULL de proposito: nada saiu, e carimbar um horario de envio
// aqui seria exatamente a ilusao de entrega que a regra proibe.
func (q *Queries) MarkNotificationUndelivered(ctx context.Context, arg MarkNotificationUndeliveredParams) error {
	_, err := q.db.Exec(ctx, markNotificationUndelivered, arg.ID, arg.UndeliveredReason)
	return err
}

const setNotificationLogProviderMessageID = `-- name: SetNotificationLogProviderMessageID :exec

UPDATE notification_logs
SET provider_message_id = $2
WHERE id = $1
`

type SetNotificationLogProviderMessageIDParams struct {
	ID                pgtype.UUID `json:"id"`
	ProviderMessageID pgtype.Text `json:"provider_message_id"`
}

// =============================================================================
// WHATSAPP (PRD 006)
// =============================================================================
// Stamps the provider message SID right after a successful send so status
// callbacks can be correlated back to this row.
func (q *Queries) SetNotificationLogProviderMessageID(ctx context.Context, arg SetNotificationLogProviderMessageIDParams) error {
	_, err := q.db.Exec(ctx, setNotificationLogProviderMessageID, arg.ID, arg.ProviderMessageID)
	return err
}

const setNotificationUndeliveredReason = `-- name: SetNotificationUndeliveredReason :exec
UPDATE notification_logs
SET undelivered_reason = $2
WHERE id = $1
`

type SetNotificationUndeliveredReasonParams struct {
	ID                pgtype.UUID `json:"id"`
	UndeliveredReason pgtype.Text `json:"undelivered_reason"`
}

// RN-38 — tentamos e o Instagram recusou. O status continua 'failed' (foi
// tentativa real, e o vocabulario de retry depende disso); o que a coluna
// acrescenta e o motivo legivel, para a linha aparecer na lista do lojista
// junto com as que nunca foram tentadas.
func (q *Queries) SetNotificationUndeliveredReason(ctx context.Context, arg SetNotificationUndeliveredReasonParams) error {
	_, err := q.db.Exec(ctx, setNotificationUndeliveredReason, arg.ID, arg.UndeliveredReason)
	return err
}

const setStoreTestRecipient = `-- name: SetStoreTestRecipient :exec
UPDATE stores
SET notification_test_recipient_psid = $2,
    notification_test_recipient_handle = $3,
    notification_test_setup_code = NULL,
    notification_test_setup_expires_at = NULL
WHERE id = $1
`

type SetStoreTestRecipientParams struct {
	ID                              pgtype.UUID `json:"id"`
	NotificationTestRecipientPsid   pgtype.Text `json:"notification_test_recipient_psid"`
	NotificationTestRecipientHandle pgtype.Text `json:"notification_test_recipient_handle"`
}

// Stores the captured PSID + handle and clears the setup code. Called from the
// IG webhook when an incoming DM matches the active setup code.
func (q *Queries) SetStoreTestRecipient(ctx context.Context, arg SetStoreTestRecipientParams) error {
	_, err := q.db.Exec(ctx, setStoreTestRecipient, arg.ID, arg.NotificationTestRecipientPsid, arg.NotificationTestRecipientHandle)
	return err
}

const setStoreTestSetupCode = `-- name: SetStoreTestSetupCode :exec
UPDATE stores
SET notification_test_setup_code = $2,
    notification_test_setup_expires_at = $3
WHERE id = $1
`

type SetStoreTestSetupCodeParams struct {
	ID                             pgtype.UUID        `json:"id"`
	NotificationTestSetupCode      pgtype.Text        `json:"notification_test_setup_code"`
	NotificationTestSetupExpiresAt pgtype.Timestamptz `json:"notification_test_setup_expires_at"`
}

// Persists a freshly generated setup code with a TTL. Called when the lojista
// starts the "Configurar destinatário de teste" flow in the dashboard.
func (q *Queries) SetStoreTestSetupCode(ctx context.Context, arg SetStoreTestSetupCodeParams) error {
	_, err := q.db.Exec(ctx, setStoreTestSetupCode, arg.ID, arg.NotificationTestSetupCode, arg.NotificationTestSetupExpiresAt)
	return err
}

const updateNotificationLogByProviderMessageID = `-- name: UpdateNotificationLogByProviderMessageID :one
UPDATE notification_logs
SET status = $2,
    error_message = $3,
    sent_at = COALESCE(sent_at, $4)
WHERE provider_message_id = $1
RETURNING id, store_id, event_id, cart_id, platform_user_id, platform_handle, notification_type, channel, status, message_text, error_message, created_at, sent_at, provider_message_id, undelivered_reason
`

type UpdateNotificationLogByProviderMessageIDParams struct {
	ProviderMessageID pgtype.Text        `json:"provider_message_id"`
	Status            string             `json:"status"`
	ErrorMessage      pgtype.Text        `json:"error_message"`
	SentAt            pgtype.Timestamptz `json:"sent_at"`
}

// Twilio status callbacks (sent/delivered/read/failed) arrive keyed by
// MessageSid. sent_at is stamped once and preserved on later transitions.
func (q *Queries) UpdateNotificationLogByProviderMessageID(ctx context.Context, arg UpdateNotificationLogByProviderMessageIDParams) (NotificationLog, error) {
	row := q.db.QueryRow(ctx, updateNotificationLogByProviderMessageID,
		arg.ProviderMessageID,
		arg.Status,
		arg.ErrorMessage,
		arg.SentAt,
	)
	var i NotificationLog
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.EventID,
		&i.CartID,
		&i.PlatformUserID,
		&i.PlatformHandle,
		&i.NotificationType,
		&i.Channel,
		&i.Status,
		&i.MessageText,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.SentAt,
		&i.ProviderMessageID,
		&i.UndeliveredReason,
	)
	return i, err
}

const updateNotificationLogStatus = `-- name: UpdateNotificationLogStatus :exec
UPDATE notification_logs
SET status = $2, sent_at = $3, error_message = $4
WHERE id = $1
`

type UpdateNotificationLogStatusParams struct {
	ID           pgtype.UUID        `json:"id"`
	Status       string             `json:"status"`
	SentAt       pgtype.Timestamptz `json:"sent_at"`
	ErrorMessage pgtype.Text        `json:"error_message"`
}

func (q *Queries) UpdateNotificationLogStatus(ctx context.Context, arg UpdateNotificationLogStatusParams) error {
	_, err := q.db.Exec(ctx, updateNotificationLogStatus,
		arg.ID,
		arg.Status,
		arg.SentAt,
		arg.ErrorMessage,
	)
	return err
}

const updateStoreNotificationSettings = `-- name: UpdateStoreNotificationSettings :exec
UPDATE stores SET notification_settings = $2 WHERE id = $1
`

type UpdateStoreNotificationSettingsParams struct {
	ID                   pgtype.UUID     `json:"id"`
	NotificationSettings json.RawMessage `json:"notification_settings"`
}

func (q *Queries) UpdateStoreNotificationSettings(ctx context.Context, arg UpdateStoreNotificationSettingsParams) error {
	_, err := q.db.Exec(ctx, updateStoreNotificationSettings, arg.ID, arg.NotificationSettings)
	return err
}
