// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: order_event.sql

package sqlc

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const hasOrderEvent = `-- name: HasOrderEvent :one
SELECT EXISTS (
    SELECT 1 FROM order_events
    WHERE cart_id = $1 AND event_type = $2
)::bool AS exists
`

type HasOrderEventParams struct {
	CartID    pgtype.UUID `json:"cart_id"`
	EventType string      `json:"event_type"`
}

func (q *Queries) HasOrderEvent(ctx context.Context, arg HasOrderEventParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasOrderEvent, arg.CartID, arg.EventType)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertOrderEvent = `-- name: InsertOrderEvent :one

INSERT INTO order_events (order_id, cart_id, event_type, occurred_at, source, metadata)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (order_id, event_type) DO NOTHING
RETURNING id, cart_id, event_type, occurred_at, source, metadata, created_at, order_id
`

type InsertOrderEventParams struct {
	OrderID    pgtype.UUID        `json:"order_id"`
	CartID     pgtype.UUID        `json:"cart_id"`
	EventType  string             `json:"event_type"`
	OccurredAt pgtype.Timestamptz `json:"occurred_at"`
	Source     string             `json:"source"`
	Metadata   json.RawMessage    `json:"metadata"`
}

// =============================================================================
// ORDER EVENTS
// =============================================================================
// Customer-facing timeline. Distinct from shipment_tracking_events (carrier
// raw codes) — these events are the lifeline the public page reads from.
// Idempotent insert: ON CONFLICT (order_id, event_type) DO NOTHING relies on
// the unique index from migration 000096 (a timeline pertence à Order). cart_id
// ainda é gravado (dual-key) até a Fase F. A row retornada (ou a ausência dela,
// ErrNoRows) deixa o caller distinguir "first emit" de "retry" e pular e-mails
// duplicados.
func (q *Queries) InsertOrderEvent(ctx context.Context, arg InsertOrderEventParams) (OrderEvent, error) {
	row := q.db.QueryRow(ctx, insertOrderEvent,
		arg.OrderID,
		arg.CartID,
		arg.EventType,
		arg.OccurredAt,
		arg.Source,
		arg.Metadata,
	)
	var i OrderEvent
	err := row.Scan(
		&i.ID,
		&i.CartID,
		&i.EventType,
		&i.OccurredAt,
		&i.Source,
		&i.Metadata,
		&i.CreatedAt,
		&i.OrderID,
	)
	return i, err
}

const listOrderEventsByCart = `-- name: ListOrderEventsByCart :many
SELECT id, cart_id, event_type, occurred_at, source, metadata, created_at, order_id FROM order_events
WHERE cart_id = $1
ORDER BY occurred_at ASC
`

func (q *Queries) ListOrderEventsByCart(ctx context.Context, cartID pgtype.UUID) ([]OrderEvent, error) {
	rows, err := q.db.Query(ctx, listOrderEventsByCart, cartID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrderEvent{}
	for rows.Next() {
		var i OrderEvent
		if err := rows.Scan(
			&i.ID,
			&i.CartID,
			&i.EventType,
			&i.OccurredAt,
			&i.Source,
			&i.Metadata,
			&i.CreatedAt,
			&i.OrderID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
