// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: session_publish_job.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelSessionPublishJob = `-- name: CancelSessionPublishJob :one
UPDATE session_publish_jobs
SET status = 'cancelled',
    cancelled_at = now(),
    updated_at = now()
WHERE id = $1 AND store_id = $2 AND status = 'scheduled'
RETURNING id, store_id, session_id, event_id, media_kind, asset_path, asset_content_type, caption, title, product_ids, starts_at, ends_at, cart_expiration_minutes, cart_max_quantity_per_item, scheduled_for, status, published_media_id, attempts, last_error, last_attempt_at, published_at, cancelled_at, created_at, updated_at
`

type CancelSessionPublishJobParams struct {
	ID      pgtype.UUID `json:"id"`
	StoreID pgtype.UUID `json:"store_id"`
}

// CancelSessionPublishJob so alcanca o que ainda NAO foi reivindicado. Um job
// em 'publishing' ja pode ter criado o container na Graph — cancelar ali
// deixaria o post no ar com o agendamento marcado como cancelado.
func (q *Queries) CancelSessionPublishJob(ctx context.Context, arg CancelSessionPublishJobParams) (SessionPublishJob, error) {
	row := q.db.QueryRow(ctx, cancelSessionPublishJob, arg.ID, arg.StoreID)
	var i SessionPublishJob
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.SessionID,
		&i.EventID,
		&i.MediaKind,
		&i.AssetPath,
		&i.AssetContentType,
		&i.Caption,
		&i.Title,
		&i.ProductIds,
		&i.StartsAt,
		&i.EndsAt,
		&i.CartExpirationMinutes,
		&i.CartMaxQuantityPerItem,
		&i.ScheduledFor,
		&i.Status,
		&i.PublishedMediaID,
		&i.Attempts,
		&i.LastError,
		&i.LastAttemptAt,
		&i.PublishedAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const claimSessionPublishJob = `-- name: ClaimSessionPublishJob :one
UPDATE session_publish_jobs
SET status = 'publishing',
    attempts = attempts + 1,
    last_attempt_at = now(),
    updated_at = now()
WHERE id = $1 AND status = 'scheduled'
RETURNING id, store_id, session_id, event_id, media_kind, asset_path, asset_content_type, caption, title, product_ids, starts_at, ends_at, cart_expiration_minutes, cart_max_quantity_per_item, scheduled_for, status, published_media_id, attempts, last_error, last_attempt_at, published_at, cancelled_at, created_at, updated_at
`

// ClaimSessionPublishJob e a REIVINDICACAO atomica do disparo. O guard
// `status = 'scheduled'` e o que faz o cancelamento valer mesmo quando a task
// asynq ja foi entregue: quem cancelou moveu a linha, e este UPDATE nao acha
// nada. Tambem e o que impede publicacao dupla se a task for entregue duas
// vezes (asynq e at-least-once).
func (q *Queries) ClaimSessionPublishJob(ctx context.Context, id pgtype.UUID) (SessionPublishJob, error) {
	row := q.db.QueryRow(ctx, claimSessionPublishJob, id)
	var i SessionPublishJob
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.SessionID,
		&i.EventID,
		&i.MediaKind,
		&i.AssetPath,
		&i.AssetContentType,
		&i.Caption,
		&i.Title,
		&i.ProductIds,
		&i.StartsAt,
		&i.EndsAt,
		&i.CartExpirationMinutes,
		&i.CartMaxQuantityPerItem,
		&i.ScheduledFor,
		&i.Status,
		&i.PublishedMediaID,
		&i.Attempts,
		&i.LastError,
		&i.LastAttemptAt,
		&i.PublishedAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSessionPublishJob = `-- name: CreateSessionPublishJob :one

INSERT INTO session_publish_jobs (
    store_id, media_kind, asset_path, asset_content_type,
    caption, title, product_ids,
    starts_at, ends_at, cart_expiration_minutes, cart_max_quantity_per_item,
    scheduled_for
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, store_id, session_id, event_id, media_kind, asset_path, asset_content_type, caption, title, product_ids, starts_at, ends_at, cart_expiration_minutes, cart_max_quantity_per_item, scheduled_for, status, published_media_id, attempts, last_error, last_attempt_at, published_at, cancelled_at, created_at, updated_at
`

type CreateSessionPublishJobParams struct {
	StoreID                pgtype.UUID        `json:"store_id"`
	MediaKind              string             `json:"media_kind"`
	AssetPath              string             `json:"asset_path"`
	AssetContentType       string             `json:"asset_content_type"`
	Caption                string             `json:"caption"`
	Title                  string             `json:"title"`
	ProductIds             []pgtype.UUID      `json:"product_ids"`
	StartsAt               pgtype.Timestamptz `json:"starts_at"`
	EndsAt                 pgtype.Timestamptz `json:"ends_at"`
	CartExpirationMinutes  pgtype.Int4        `json:"cart_expiration_minutes"`
	CartMaxQuantityPerItem pgtype.Int4        `json:"cart_max_quantity_per_item"`
	ScheduledFor           pgtype.Timestamptz `json:"scheduled_for"`
}

// =============================================================================
// SESSION PUBLISH JOBS (RN-31 / N3)
// Agendamento de publicacao no Instagram. O agendador e nosso: a Graph nao tem
// scheduled_publish_time e o container expira em 24h.
// =============================================================================
func (q *Queries) CreateSessionPublishJob(ctx context.Context, arg CreateSessionPublishJobParams) (SessionPublishJob, error) {
	row := q.db.QueryRow(ctx, createSessionPublishJob,
		arg.StoreID,
		arg.MediaKind,
		arg.AssetPath,
		arg.AssetContentType,
		arg.Caption,
		arg.Title,
		arg.ProductIds,
		arg.StartsAt,
		arg.EndsAt,
		arg.CartExpirationMinutes,
		arg.CartMaxQuantityPerItem,
		arg.ScheduledFor,
	)
	var i SessionPublishJob
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.SessionID,
		&i.EventID,
		&i.MediaKind,
		&i.AssetPath,
		&i.AssetContentType,
		&i.Caption,
		&i.Title,
		&i.ProductIds,
		&i.StartsAt,
		&i.EndsAt,
		&i.CartExpirationMinutes,
		&i.CartMaxQuantityPerItem,
		&i.ScheduledFor,
		&i.Status,
		&i.PublishedMediaID,
		&i.Attempts,
		&i.LastError,
		&i.LastAttemptAt,
		&i.PublishedAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const failSessionPublishJob = `-- name: FailSessionPublishJob :exec
UPDATE session_publish_jobs
SET status = 'failed',
    last_error = $2,
    updated_at = now()
WHERE id = $1 AND status IN ('scheduled', 'publishing')
`

type FailSessionPublishJobParams struct {
	ID        pgtype.UUID `json:"id"`
	LastError pgtype.Text `json:"last_error"`
}

func (q *Queries) FailSessionPublishJob(ctx context.Context, arg FailSessionPublishJobParams) error {
	_, err := q.db.Exec(ctx, failSessionPublishJob, arg.ID, arg.LastError)
	return err
}

const getSessionPublishJob = `-- name: GetSessionPublishJob :one
SELECT id, store_id, session_id, event_id, media_kind, asset_path, asset_content_type, caption, title, product_ids, starts_at, ends_at, cart_expiration_minutes, cart_max_quantity_per_item, scheduled_for, status, published_media_id, attempts, last_error, last_attempt_at, published_at, cancelled_at, created_at, updated_at FROM session_publish_jobs WHERE id = $1 AND store_id = $2
`

type GetSessionPublishJobParams struct {
	ID      pgtype.UUID `json:"id"`
	StoreID pgtype.UUID `json:"store_id"`
}

func (q *Queries) GetSessionPublishJob(ctx context.Context, arg GetSessionPublishJobParams) (SessionPublishJob, error) {
	row := q.db.QueryRow(ctx, getSessionPublishJob, arg.ID, arg.StoreID)
	var i SessionPublishJob
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.SessionID,
		&i.EventID,
		&i.MediaKind,
		&i.AssetPath,
		&i.AssetContentType,
		&i.Caption,
		&i.Title,
		&i.ProductIds,
		&i.StartsAt,
		&i.EndsAt,
		&i.CartExpirationMinutes,
		&i.CartMaxQuantityPerItem,
		&i.ScheduledFor,
		&i.Status,
		&i.PublishedMediaID,
		&i.Attempts,
		&i.LastError,
		&i.LastAttemptAt,
		&i.PublishedAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDueSessionPublishJobs = `-- name: ListDueSessionPublishJobs :many
SELECT id, store_id, session_id, event_id, media_kind, asset_path, asset_content_type, caption, title, product_ids, starts_at, ends_at, cart_expiration_minutes, cart_max_quantity_per_item, scheduled_for, status, published_media_id, attempts, last_error, last_attempt_at, published_at, cancelled_at, created_at, updated_at FROM session_publish_jobs
WHERE status = 'scheduled' AND scheduled_for <= now()
ORDER BY scheduled_for ASC
LIMIT $1
`

// ListDueSessionPublishJobs e o BACKSTOP do agendador ETA: task perdida (Redis
// limpo, deploy no meio) deixa o job vencido e ninguem o dispara. Mesmo papel
// do SweepEndedTimedEvents.
func (q *Queries) ListDueSessionPublishJobs(ctx context.Context, limit int32) ([]SessionPublishJob, error) {
	rows, err := q.db.Query(ctx, listDueSessionPublishJobs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SessionPublishJob{}
	for rows.Next() {
		var i SessionPublishJob
		if err := rows.Scan(
			&i.ID,
			&i.StoreID,
			&i.SessionID,
			&i.EventID,
			&i.MediaKind,
			&i.AssetPath,
			&i.AssetContentType,
			&i.Caption,
			&i.Title,
			&i.ProductIds,
			&i.StartsAt,
			&i.EndsAt,
			&i.CartExpirationMinutes,
			&i.CartMaxQuantityPerItem,
			&i.ScheduledFor,
			&i.Status,
			&i.PublishedMediaID,
			&i.Attempts,
			&i.LastError,
			&i.LastAttemptAt,
			&i.PublishedAt,
			&i.CancelledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionPublishJobsByStore = `-- name: ListSessionPublishJobsByStore :many
SELECT id, store_id, session_id, event_id, media_kind, asset_path, asset_content_type, caption, title, product_ids, starts_at, ends_at, cart_expiration_minutes, cart_max_quantity_per_item, scheduled_for, status, published_media_id, attempts, last_error, last_attempt_at, published_at, cancelled_at, created_at, updated_at FROM session_publish_jobs
WHERE store_id = $1
  AND ($3::text IS NULL OR status = $3::text)
ORDER BY scheduled_for DESC
LIMIT $2
`

type ListSessionPublishJobsByStoreParams struct {
	StoreID pgtype.UUID `json:"store_id"`
	Limit   int32       `json:"limit"`
	Status  pgtype.Text `json:"status"`
}

func (q *Queries) ListSessionPublishJobsByStore(ctx context.Context, arg ListSessionPublishJobsByStoreParams) ([]SessionPublishJob, error) {
	rows, err := q.db.Query(ctx, listSessionPublishJobsByStore, arg.StoreID, arg.Limit, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SessionPublishJob{}
	for rows.Next() {
		var i SessionPublishJob
		if err := rows.Scan(
			&i.ID,
			&i.StoreID,
			&i.SessionID,
			&i.EventID,
			&i.MediaKind,
			&i.AssetPath,
			&i.AssetContentType,
			&i.Caption,
			&i.Title,
			&i.ProductIds,
			&i.StartsAt,
			&i.EndsAt,
			&i.CartExpirationMinutes,
			&i.CartMaxQuantityPerItem,
			&i.ScheduledFor,
			&i.Status,
			&i.PublishedMediaID,
			&i.Attempts,
			&i.LastError,
			&i.LastAttemptAt,
			&i.PublishedAt,
			&i.CancelledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStuckSessionPublishJobs = `-- name: ListStuckSessionPublishJobs :many
SELECT id, store_id, session_id, event_id, media_kind, asset_path, asset_content_type, caption, title, product_ids, starts_at, ends_at, cart_expiration_minutes, cart_max_quantity_per_item, scheduled_for, status, published_media_id, attempts, last_error, last_attempt_at, published_at, cancelled_at, created_at, updated_at FROM session_publish_jobs
WHERE status = 'publishing' AND last_attempt_at < $1
ORDER BY last_attempt_at ASC
LIMIT $2
`

type ListStuckSessionPublishJobsParams struct {
	LastAttemptAt pgtype.Timestamptz `json:"last_attempt_at"`
	Limit         int32              `json:"limit"`
}

// ListStuckSessionPublishJobs acha o job preso em 'publishing': o processo
// morreu entre a reivindicacao e o desfecho, entao nenhum estado terminal foi
// gravado e a linha nunca mais e reivindicada. Sem isto o agendamento morre em
// silencio, que e o pior desfecho possivel para uma publicacao.
func (q *Queries) ListStuckSessionPublishJobs(ctx context.Context, arg ListStuckSessionPublishJobsParams) ([]SessionPublishJob, error) {
	rows, err := q.db.Query(ctx, listStuckSessionPublishJobs, arg.LastAttemptAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SessionPublishJob{}
	for rows.Next() {
		var i SessionPublishJob
		if err := rows.Scan(
			&i.ID,
			&i.StoreID,
			&i.SessionID,
			&i.EventID,
			&i.MediaKind,
			&i.AssetPath,
			&i.AssetContentType,
			&i.Caption,
			&i.Title,
			&i.ProductIds,
			&i.StartsAt,
			&i.EndsAt,
			&i.CartExpirationMinutes,
			&i.CartMaxQuantityPerItem,
			&i.ScheduledFor,
			&i.Status,
			&i.PublishedMediaID,
			&i.Attempts,
			&i.LastError,
			&i.LastAttemptAt,
			&i.PublishedAt,
			&i.CancelledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSessionPublishJobPublished = `-- name: MarkSessionPublishJobPublished :exec
UPDATE session_publish_jobs
SET status = 'published',
    published_media_id = $2,
    event_id = $3,
    session_id = $4,
    published_at = now(),
    last_error = $5,
    updated_at = now()
WHERE id = $1
`

type MarkSessionPublishJobPublishedParams struct {
	ID               pgtype.UUID `json:"id"`
	PublishedMediaID pgtype.Text `json:"published_media_id"`
	EventID          pgtype.UUID `json:"event_id"`
	SessionID        pgtype.UUID `json:"session_id"`
	LastError        pgtype.Text `json:"last_error"`
}

// MarkSessionPublishJobPublished aceita last_error preenchido de proposito. O
// desfecho "publicou mas nao conseguiu criar o evento" e REAL: o post ja esta
// no ar e retentar republicaria. Ele precisa terminar como 'published' (para
// nao ser reivindicado de novo) carregando o motivo de o vinculo ter faltado.
func (q *Queries) MarkSessionPublishJobPublished(ctx context.Context, arg MarkSessionPublishJobPublishedParams) error {
	_, err := q.db.Exec(ctx, markSessionPublishJobPublished,
		arg.ID,
		arg.PublishedMediaID,
		arg.EventID,
		arg.SessionID,
		arg.LastError,
	)
	return err
}

const releaseSessionPublishJob = `-- name: ReleaseSessionPublishJob :exec
UPDATE session_publish_jobs
SET status = 'scheduled',
    last_error = $2,
    updated_at = now()
WHERE id = $1 AND status = 'publishing'
`

type ReleaseSessionPublishJobParams struct {
	ID        pgtype.UUID `json:"id"`
	LastError pgtype.Text `json:"last_error"`
}

// ReleaseSessionPublishJob devolve o job para a fila depois de uma tentativa
// que falhou mas ainda tem retry. Volta para 'scheduled' de proposito: e o
// unico estado que ClaimSessionPublishJob reivindica, entao o retry do asynq E
// o sweep de backstop enxergam a mesma linha.
func (q *Queries) ReleaseSessionPublishJob(ctx context.Context, arg ReleaseSessionPublishJobParams) error {
	_, err := q.db.Exec(ctx, releaseSessionPublishJob, arg.ID, arg.LastError)
	return err
}
