// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: store.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createStore = `-- name: CreateStore :one
INSERT INTO stores (name, slug)
VALUES ($1, $2)
RETURNING id, name, slug, active, whatsapp_number, email_address, sms_number, created_at, cart_enabled, cart_expiration_minutes, cart_reserve_stock, cart_max_items, cart_max_quantity_per_item, cart_notify_before_expiration, updated_at, clerk_org_id
`

type CreateStoreParams struct {
	Name string `json:"name"`
	Slug string `json:"slug"`
}

func (q *Queries) CreateStore(ctx context.Context, arg CreateStoreParams) (Store, error) {
	row := q.db.QueryRow(ctx, createStore, arg.Name, arg.Slug)
	var i Store
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Active,
		&i.WhatsappNumber,
		&i.EmailAddress,
		&i.SmsNumber,
		&i.CreatedAt,
		&i.CartEnabled,
		&i.CartExpirationMinutes,
		&i.CartReserveStock,
		&i.CartMaxItems,
		&i.CartMaxQuantityPerItem,
		&i.CartNotifyBeforeExpiration,
		&i.UpdatedAt,
		&i.ClerkOrgID,
	)
	return i, err
}

const createStoreWithClerkOrg = `-- name: CreateStoreWithClerkOrg :one
INSERT INTO stores (name, slug, clerk_org_id)
VALUES ($1, $2, $3)
RETURNING id, name, slug, active, whatsapp_number, email_address, sms_number, created_at, cart_enabled, cart_expiration_minutes, cart_reserve_stock, cart_max_items, cart_max_quantity_per_item, cart_notify_before_expiration, updated_at, clerk_org_id
`

type CreateStoreWithClerkOrgParams struct {
	Name       string      `json:"name"`
	Slug       string      `json:"slug"`
	ClerkOrgID pgtype.Text `json:"clerk_org_id"`
}

func (q *Queries) CreateStoreWithClerkOrg(ctx context.Context, arg CreateStoreWithClerkOrgParams) (Store, error) {
	row := q.db.QueryRow(ctx, createStoreWithClerkOrg, arg.Name, arg.Slug, arg.ClerkOrgID)
	var i Store
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Active,
		&i.WhatsappNumber,
		&i.EmailAddress,
		&i.SmsNumber,
		&i.CreatedAt,
		&i.CartEnabled,
		&i.CartExpirationMinutes,
		&i.CartReserveStock,
		&i.CartMaxItems,
		&i.CartMaxQuantityPerItem,
		&i.CartNotifyBeforeExpiration,
		&i.UpdatedAt,
		&i.ClerkOrgID,
	)
	return i, err
}

const deleteStore = `-- name: DeleteStore :exec
DELETE FROM stores WHERE id = $1
`

func (q *Queries) DeleteStore(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteStore, id)
	return err
}

const getStoreByClerkOrgID = `-- name: GetStoreByClerkOrgID :one
SELECT id, name, slug, active, whatsapp_number, email_address, sms_number, created_at, cart_enabled, cart_expiration_minutes, cart_reserve_stock, cart_max_items, cart_max_quantity_per_item, cart_notify_before_expiration, updated_at, clerk_org_id FROM stores WHERE clerk_org_id = $1
`

func (q *Queries) GetStoreByClerkOrgID(ctx context.Context, clerkOrgID pgtype.Text) (Store, error) {
	row := q.db.QueryRow(ctx, getStoreByClerkOrgID, clerkOrgID)
	var i Store
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Active,
		&i.WhatsappNumber,
		&i.EmailAddress,
		&i.SmsNumber,
		&i.CreatedAt,
		&i.CartEnabled,
		&i.CartExpirationMinutes,
		&i.CartReserveStock,
		&i.CartMaxItems,
		&i.CartMaxQuantityPerItem,
		&i.CartNotifyBeforeExpiration,
		&i.UpdatedAt,
		&i.ClerkOrgID,
	)
	return i, err
}

const getStoreByClerkUserID = `-- name: GetStoreByClerkUserID :one
SELECT s.id, s.name, s.slug, s.active, s.whatsapp_number, s.email_address, s.sms_number, s.created_at, s.cart_enabled, s.cart_expiration_minutes, s.cart_reserve_stock, s.cart_max_items, s.cart_max_quantity_per_item, s.cart_notify_before_expiration, s.updated_at, s.clerk_org_id
FROM stores s
JOIN memberships m ON s.id = m.store_id
WHERE m.clerk_user_id = $1 AND m.status = 'active'
ORDER BY m.last_accessed_at DESC NULLS LAST, m.created_at ASC
LIMIT 1
`

// Get first store for a clerk user (for backwards compatibility)
func (q *Queries) GetStoreByClerkUserID(ctx context.Context, clerkUserID pgtype.Text) (Store, error) {
	row := q.db.QueryRow(ctx, getStoreByClerkUserID, clerkUserID)
	var i Store
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Active,
		&i.WhatsappNumber,
		&i.EmailAddress,
		&i.SmsNumber,
		&i.CreatedAt,
		&i.CartEnabled,
		&i.CartExpirationMinutes,
		&i.CartReserveStock,
		&i.CartMaxItems,
		&i.CartMaxQuantityPerItem,
		&i.CartNotifyBeforeExpiration,
		&i.UpdatedAt,
		&i.ClerkOrgID,
	)
	return i, err
}

const getStoreByID = `-- name: GetStoreByID :one
SELECT id, name, slug, active, whatsapp_number, email_address, sms_number, created_at, cart_enabled, cart_expiration_minutes, cart_reserve_stock, cart_max_items, cart_max_quantity_per_item, cart_notify_before_expiration, updated_at, clerk_org_id FROM stores WHERE id = $1
`

func (q *Queries) GetStoreByID(ctx context.Context, id pgtype.UUID) (Store, error) {
	row := q.db.QueryRow(ctx, getStoreByID, id)
	var i Store
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Active,
		&i.WhatsappNumber,
		&i.EmailAddress,
		&i.SmsNumber,
		&i.CreatedAt,
		&i.CartEnabled,
		&i.CartExpirationMinutes,
		&i.CartReserveStock,
		&i.CartMaxItems,
		&i.CartMaxQuantityPerItem,
		&i.CartNotifyBeforeExpiration,
		&i.UpdatedAt,
		&i.ClerkOrgID,
	)
	return i, err
}

const getStoreByOwnerClerkUserID = `-- name: GetStoreByOwnerClerkUserID :one
SELECT s.id, s.name, s.slug, s.active, s.whatsapp_number, s.email_address, s.sms_number, s.created_at, s.cart_enabled, s.cart_expiration_minutes, s.cart_reserve_stock, s.cart_max_items, s.cart_max_quantity_per_item, s.cart_notify_before_expiration, s.updated_at, s.clerk_org_id
FROM stores s
JOIN memberships m ON s.id = m.store_id
WHERE m.clerk_user_id = $1 AND m.role = 'owner'
LIMIT 1
`

// Get store where clerk user is owner
func (q *Queries) GetStoreByOwnerClerkUserID(ctx context.Context, clerkUserID pgtype.Text) (Store, error) {
	row := q.db.QueryRow(ctx, getStoreByOwnerClerkUserID, clerkUserID)
	var i Store
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Active,
		&i.WhatsappNumber,
		&i.EmailAddress,
		&i.SmsNumber,
		&i.CreatedAt,
		&i.CartEnabled,
		&i.CartExpirationMinutes,
		&i.CartReserveStock,
		&i.CartMaxItems,
		&i.CartMaxQuantityPerItem,
		&i.CartNotifyBeforeExpiration,
		&i.UpdatedAt,
		&i.ClerkOrgID,
	)
	return i, err
}

const getStoreBySlug = `-- name: GetStoreBySlug :one
SELECT id, name, slug, active, whatsapp_number, email_address, sms_number, created_at, cart_enabled, cart_expiration_minutes, cart_reserve_stock, cart_max_items, cart_max_quantity_per_item, cart_notify_before_expiration, updated_at, clerk_org_id FROM stores WHERE slug = $1
`

func (q *Queries) GetStoreBySlug(ctx context.Context, slug string) (Store, error) {
	row := q.db.QueryRow(ctx, getStoreBySlug, slug)
	var i Store
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Active,
		&i.WhatsappNumber,
		&i.EmailAddress,
		&i.SmsNumber,
		&i.CreatedAt,
		&i.CartEnabled,
		&i.CartExpirationMinutes,
		&i.CartReserveStock,
		&i.CartMaxItems,
		&i.CartMaxQuantityPerItem,
		&i.CartNotifyBeforeExpiration,
		&i.UpdatedAt,
		&i.ClerkOrgID,
	)
	return i, err
}

const listStoreMembers = `-- name: ListStoreMembers :many
SELECT id, store_id, email, role, password_hash, created_at, clerk_user_id, name, avatar_url, updated_at, status, invited_by, invited_at, last_accessed_at FROM memberships WHERE store_id = $1 ORDER BY created_at
`

func (q *Queries) ListStoreMembers(ctx context.Context, storeID pgtype.UUID) ([]Membership, error) {
	rows, err := q.db.Query(ctx, listStoreMembers, storeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Membership{}
	for rows.Next() {
		var i Membership
		if err := rows.Scan(
			&i.ID,
			&i.StoreID,
			&i.Email,
			&i.Role,
			&i.PasswordHash,
			&i.CreatedAt,
			&i.ClerkUserID,
			&i.Name,
			&i.AvatarUrl,
			&i.UpdatedAt,
			&i.Status,
			&i.InvitedBy,
			&i.InvitedAt,
			&i.LastAccessedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStore = `-- name: UpdateStore :one
UPDATE stores
SET
  name = $2,
  whatsapp_number = $3,
  email_address = $4,
  sms_number = $5,
  updated_at = now()
WHERE id = $1
RETURNING id, name, slug, active, whatsapp_number, email_address, sms_number, created_at, cart_enabled, cart_expiration_minutes, cart_reserve_stock, cart_max_items, cart_max_quantity_per_item, cart_notify_before_expiration, updated_at, clerk_org_id
`

type UpdateStoreParams struct {
	ID             pgtype.UUID `json:"id"`
	Name           string      `json:"name"`
	WhatsappNumber pgtype.Text `json:"whatsapp_number"`
	EmailAddress   pgtype.Text `json:"email_address"`
	SmsNumber      pgtype.Text `json:"sms_number"`
}

func (q *Queries) UpdateStore(ctx context.Context, arg UpdateStoreParams) (Store, error) {
	row := q.db.QueryRow(ctx, updateStore,
		arg.ID,
		arg.Name,
		arg.WhatsappNumber,
		arg.EmailAddress,
		arg.SmsNumber,
	)
	var i Store
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Active,
		&i.WhatsappNumber,
		&i.EmailAddress,
		&i.SmsNumber,
		&i.CreatedAt,
		&i.CartEnabled,
		&i.CartExpirationMinutes,
		&i.CartReserveStock,
		&i.CartMaxItems,
		&i.CartMaxQuantityPerItem,
		&i.CartNotifyBeforeExpiration,
		&i.UpdatedAt,
		&i.ClerkOrgID,
	)
	return i, err
}

const updateStoreCartSettings = `-- name: UpdateStoreCartSettings :one
UPDATE stores
SET
  cart_enabled = $2,
  cart_expiration_minutes = $3,
  cart_reserve_stock = $4,
  cart_max_items = $5,
  cart_max_quantity_per_item = $6,
  cart_notify_before_expiration = $7,
  updated_at = now()
WHERE id = $1
RETURNING id, name, slug, active, whatsapp_number, email_address, sms_number, created_at, cart_enabled, cart_expiration_minutes, cart_reserve_stock, cart_max_items, cart_max_quantity_per_item, cart_notify_before_expiration, updated_at, clerk_org_id
`

type UpdateStoreCartSettingsParams struct {
	ID                         pgtype.UUID `json:"id"`
	CartEnabled                bool        `json:"cart_enabled"`
	CartExpirationMinutes      int32       `json:"cart_expiration_minutes"`
	CartReserveStock           bool        `json:"cart_reserve_stock"`
	CartMaxItems               int32       `json:"cart_max_items"`
	CartMaxQuantityPerItem     int32       `json:"cart_max_quantity_per_item"`
	CartNotifyBeforeExpiration bool        `json:"cart_notify_before_expiration"`
}

func (q *Queries) UpdateStoreCartSettings(ctx context.Context, arg UpdateStoreCartSettingsParams) (Store, error) {
	row := q.db.QueryRow(ctx, updateStoreCartSettings,
		arg.ID,
		arg.CartEnabled,
		arg.CartExpirationMinutes,
		arg.CartReserveStock,
		arg.CartMaxItems,
		arg.CartMaxQuantityPerItem,
		arg.CartNotifyBeforeExpiration,
	)
	var i Store
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Active,
		&i.WhatsappNumber,
		&i.EmailAddress,
		&i.SmsNumber,
		&i.CreatedAt,
		&i.CartEnabled,
		&i.CartExpirationMinutes,
		&i.CartReserveStock,
		&i.CartMaxItems,
		&i.CartMaxQuantityPerItem,
		&i.CartNotifyBeforeExpiration,
		&i.UpdatedAt,
		&i.ClerkOrgID,
	)
	return i, err
}

const updateStoreClerkOrgID = `-- name: UpdateStoreClerkOrgID :one
UPDATE stores
SET clerk_org_id = $2, updated_at = now()
WHERE id = $1
RETURNING id, name, slug, active, whatsapp_number, email_address, sms_number, created_at, cart_enabled, cart_expiration_minutes, cart_reserve_stock, cart_max_items, cart_max_quantity_per_item, cart_notify_before_expiration, updated_at, clerk_org_id
`

type UpdateStoreClerkOrgIDParams struct {
	ID         pgtype.UUID `json:"id"`
	ClerkOrgID pgtype.Text `json:"clerk_org_id"`
}

func (q *Queries) UpdateStoreClerkOrgID(ctx context.Context, arg UpdateStoreClerkOrgIDParams) (Store, error) {
	row := q.db.QueryRow(ctx, updateStoreClerkOrgID, arg.ID, arg.ClerkOrgID)
	var i Store
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Active,
		&i.WhatsappNumber,
		&i.EmailAddress,
		&i.SmsNumber,
		&i.CreatedAt,
		&i.CartEnabled,
		&i.CartExpirationMinutes,
		&i.CartReserveStock,
		&i.CartMaxItems,
		&i.CartMaxQuantityPerItem,
		&i.CartNotifyBeforeExpiration,
		&i.UpdatedAt,
		&i.ClerkOrgID,
	)
	return i, err
}
