// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: store.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeOnboarding = `-- name: CompleteOnboarding :exec
UPDATE stores
SET onboarding_complete = true, updated_at = now()
WHERE id = $1
`

func (q *Queries) CompleteOnboarding(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, completeOnboarding, id)
	return err
}

const createStore = `-- name: CreateStore :one
INSERT INTO stores (name, slug)
VALUES ($1, $2)
RETURNING id, name, slug, active, whatsapp_number, email_address, sms_number, created_at, cart_enabled, cart_expiration_minutes, cart_reserve_stock, cart_max_items, cart_max_quantity_per_item, cart_notify_before_expiration, updated_at, onboarding_complete
`

type CreateStoreParams struct {
	Name string `json:"name"`
	Slug string `json:"slug"`
}

func (q *Queries) CreateStore(ctx context.Context, arg CreateStoreParams) (Store, error) {
	row := q.db.QueryRow(ctx, createStore, arg.Name, arg.Slug)
	var i Store
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Active,
		&i.WhatsappNumber,
		&i.EmailAddress,
		&i.SmsNumber,
		&i.CreatedAt,
		&i.CartEnabled,
		&i.CartExpirationMinutes,
		&i.CartReserveStock,
		&i.CartMaxItems,
		&i.CartMaxQuantityPerItem,
		&i.CartNotifyBeforeExpiration,
		&i.UpdatedAt,
		&i.OnboardingComplete,
	)
	return i, err
}

const createStoreUser = `-- name: CreateStoreUser :one
INSERT INTO store_users (store_id, email, role, password_hash)
VALUES ($1, $2, $3, $4)
RETURNING id, store_id, email, role, password_hash, created_at, clerk_user_id, name, avatar_url, updated_at, status, invited_by, invited_at
`

type CreateStoreUserParams struct {
	StoreID      pgtype.UUID `json:"store_id"`
	Email        string      `json:"email"`
	Role         string      `json:"role"`
	PasswordHash pgtype.Text `json:"password_hash"`
}

func (q *Queries) CreateStoreUser(ctx context.Context, arg CreateStoreUserParams) (StoreUser, error) {
	row := q.db.QueryRow(ctx, createStoreUser,
		arg.StoreID,
		arg.Email,
		arg.Role,
		arg.PasswordHash,
	)
	var i StoreUser
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.Email,
		&i.Role,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.ClerkUserID,
		&i.Name,
		&i.AvatarUrl,
		&i.UpdatedAt,
		&i.Status,
		&i.InvitedBy,
		&i.InvitedAt,
	)
	return i, err
}

const getStoreByID = `-- name: GetStoreByID :one
SELECT id, name, slug, active, whatsapp_number, email_address, sms_number, created_at, cart_enabled, cart_expiration_minutes, cart_reserve_stock, cart_max_items, cart_max_quantity_per_item, cart_notify_before_expiration, updated_at, onboarding_complete FROM stores WHERE id = $1
`

func (q *Queries) GetStoreByID(ctx context.Context, id pgtype.UUID) (Store, error) {
	row := q.db.QueryRow(ctx, getStoreByID, id)
	var i Store
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Active,
		&i.WhatsappNumber,
		&i.EmailAddress,
		&i.SmsNumber,
		&i.CreatedAt,
		&i.CartEnabled,
		&i.CartExpirationMinutes,
		&i.CartReserveStock,
		&i.CartMaxItems,
		&i.CartMaxQuantityPerItem,
		&i.CartNotifyBeforeExpiration,
		&i.UpdatedAt,
		&i.OnboardingComplete,
	)
	return i, err
}

const getStoreBySlug = `-- name: GetStoreBySlug :one
SELECT id, name, slug, active, whatsapp_number, email_address, sms_number, created_at, cart_enabled, cart_expiration_minutes, cart_reserve_stock, cart_max_items, cart_max_quantity_per_item, cart_notify_before_expiration, updated_at, onboarding_complete FROM stores WHERE slug = $1
`

func (q *Queries) GetStoreBySlug(ctx context.Context, slug string) (Store, error) {
	row := q.db.QueryRow(ctx, getStoreBySlug, slug)
	var i Store
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Active,
		&i.WhatsappNumber,
		&i.EmailAddress,
		&i.SmsNumber,
		&i.CreatedAt,
		&i.CartEnabled,
		&i.CartExpirationMinutes,
		&i.CartReserveStock,
		&i.CartMaxItems,
		&i.CartMaxQuantityPerItem,
		&i.CartNotifyBeforeExpiration,
		&i.UpdatedAt,
		&i.OnboardingComplete,
	)
	return i, err
}

const listStoreUsers = `-- name: ListStoreUsers :many
SELECT id, store_id, email, role, password_hash, created_at, clerk_user_id, name, avatar_url, updated_at, status, invited_by, invited_at FROM store_users WHERE store_id = $1 ORDER BY created_at
`

func (q *Queries) ListStoreUsers(ctx context.Context, storeID pgtype.UUID) ([]StoreUser, error) {
	rows, err := q.db.Query(ctx, listStoreUsers, storeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StoreUser{}
	for rows.Next() {
		var i StoreUser
		if err := rows.Scan(
			&i.ID,
			&i.StoreID,
			&i.Email,
			&i.Role,
			&i.PasswordHash,
			&i.CreatedAt,
			&i.ClerkUserID,
			&i.Name,
			&i.AvatarUrl,
			&i.UpdatedAt,
			&i.Status,
			&i.InvitedBy,
			&i.InvitedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStore = `-- name: UpdateStore :one
UPDATE stores
SET
  name = $2,
  whatsapp_number = $3,
  email_address = $4,
  sms_number = $5,
  updated_at = now()
WHERE id = $1
RETURNING id, name, slug, active, whatsapp_number, email_address, sms_number, created_at, cart_enabled, cart_expiration_minutes, cart_reserve_stock, cart_max_items, cart_max_quantity_per_item, cart_notify_before_expiration, updated_at, onboarding_complete
`

type UpdateStoreParams struct {
	ID             pgtype.UUID `json:"id"`
	Name           string      `json:"name"`
	WhatsappNumber pgtype.Text `json:"whatsapp_number"`
	EmailAddress   pgtype.Text `json:"email_address"`
	SmsNumber      pgtype.Text `json:"sms_number"`
}

func (q *Queries) UpdateStore(ctx context.Context, arg UpdateStoreParams) (Store, error) {
	row := q.db.QueryRow(ctx, updateStore,
		arg.ID,
		arg.Name,
		arg.WhatsappNumber,
		arg.EmailAddress,
		arg.SmsNumber,
	)
	var i Store
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Active,
		&i.WhatsappNumber,
		&i.EmailAddress,
		&i.SmsNumber,
		&i.CreatedAt,
		&i.CartEnabled,
		&i.CartExpirationMinutes,
		&i.CartReserveStock,
		&i.CartMaxItems,
		&i.CartMaxQuantityPerItem,
		&i.CartNotifyBeforeExpiration,
		&i.UpdatedAt,
		&i.OnboardingComplete,
	)
	return i, err
}

const updateStoreCartSettings = `-- name: UpdateStoreCartSettings :one
UPDATE stores
SET
  cart_enabled = $2,
  cart_expiration_minutes = $3,
  cart_reserve_stock = $4,
  cart_max_items = $5,
  cart_max_quantity_per_item = $6,
  cart_notify_before_expiration = $7,
  updated_at = now()
WHERE id = $1
RETURNING id, name, slug, active, whatsapp_number, email_address, sms_number, created_at, cart_enabled, cart_expiration_minutes, cart_reserve_stock, cart_max_items, cart_max_quantity_per_item, cart_notify_before_expiration, updated_at, onboarding_complete
`

type UpdateStoreCartSettingsParams struct {
	ID                         pgtype.UUID `json:"id"`
	CartEnabled                bool        `json:"cart_enabled"`
	CartExpirationMinutes      int32       `json:"cart_expiration_minutes"`
	CartReserveStock           bool        `json:"cart_reserve_stock"`
	CartMaxItems               int32       `json:"cart_max_items"`
	CartMaxQuantityPerItem     int32       `json:"cart_max_quantity_per_item"`
	CartNotifyBeforeExpiration bool        `json:"cart_notify_before_expiration"`
}

func (q *Queries) UpdateStoreCartSettings(ctx context.Context, arg UpdateStoreCartSettingsParams) (Store, error) {
	row := q.db.QueryRow(ctx, updateStoreCartSettings,
		arg.ID,
		arg.CartEnabled,
		arg.CartExpirationMinutes,
		arg.CartReserveStock,
		arg.CartMaxItems,
		arg.CartMaxQuantityPerItem,
		arg.CartNotifyBeforeExpiration,
	)
	var i Store
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Active,
		&i.WhatsappNumber,
		&i.EmailAddress,
		&i.SmsNumber,
		&i.CreatedAt,
		&i.CartEnabled,
		&i.CartExpirationMinutes,
		&i.CartReserveStock,
		&i.CartMaxItems,
		&i.CartMaxQuantityPerItem,
		&i.CartNotifyBeforeExpiration,
		&i.UpdatedAt,
		&i.OnboardingComplete,
	)
	return i, err
}
