// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: store.sql

package sqlc

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const createStore = `-- name: CreateStore :one
INSERT INTO stores (name, slug)
VALUES ($1, $2)
RETURNING id, name, slug, active, whatsapp_number, email_address, sms_number, created_at, cart_enabled, cart_expiration_minutes, cart_reserve_stock, cart_max_items, cart_max_quantity_per_item, updated_at, description, website, logo_url, address_street, address_city, address_state, address_zip, address_country, send_on_live_end, cart_allow_edit, checkout_send_methods, notification_settings, cart_message_cooldown_seconds, cart_send_expiration_reminder, cart_expiration_reminder_minutes, cart_real_time, cnpj, address_number, address_complement, address_district, address_state_register, default_package_weight_grams, default_package_format, default_height_cm, default_width_cm, default_length_cm
`

type CreateStoreParams struct {
	Name string `json:"name"`
	Slug string `json:"slug"`
}

func (q *Queries) CreateStore(ctx context.Context, arg CreateStoreParams) (Store, error) {
	row := q.db.QueryRow(ctx, createStore, arg.Name, arg.Slug)
	var i Store
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Active,
		&i.WhatsappNumber,
		&i.EmailAddress,
		&i.SmsNumber,
		&i.CreatedAt,
		&i.CartEnabled,
		&i.CartExpirationMinutes,
		&i.CartReserveStock,
		&i.CartMaxItems,
		&i.CartMaxQuantityPerItem,
		&i.UpdatedAt,
		&i.Description,
		&i.Website,
		&i.LogoUrl,
		&i.AddressStreet,
		&i.AddressCity,
		&i.AddressState,
		&i.AddressZip,
		&i.AddressCountry,
		&i.SendOnLiveEnd,
		&i.CartAllowEdit,
		&i.CheckoutSendMethods,
		&i.NotificationSettings,
		&i.CartMessageCooldownSeconds,
		&i.CartSendExpirationReminder,
		&i.CartExpirationReminderMinutes,
		&i.CartRealTime,
		&i.Cnpj,
		&i.AddressNumber,
		&i.AddressComplement,
		&i.AddressDistrict,
		&i.AddressStateRegister,
		&i.DefaultPackageWeightGrams,
		&i.DefaultPackageFormat,
		&i.DefaultHeightCm,
		&i.DefaultWidthCm,
		&i.DefaultLengthCm,
	)
	return i, err
}

const deleteStore = `-- name: DeleteStore :exec
DELETE FROM stores WHERE id = $1
`

func (q *Queries) DeleteStore(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteStore, id)
	return err
}

const getStoreByID = `-- name: GetStoreByID :one
SELECT id, name, slug, active, whatsapp_number, email_address, sms_number, created_at, cart_enabled, cart_expiration_minutes, cart_reserve_stock, cart_max_items, cart_max_quantity_per_item, updated_at, description, website, logo_url, address_street, address_city, address_state, address_zip, address_country, send_on_live_end, cart_allow_edit, checkout_send_methods, notification_settings, cart_message_cooldown_seconds, cart_send_expiration_reminder, cart_expiration_reminder_minutes, cart_real_time, cnpj, address_number, address_complement, address_district, address_state_register, default_package_weight_grams, default_package_format, default_height_cm, default_width_cm, default_length_cm FROM stores WHERE id = $1
`

func (q *Queries) GetStoreByID(ctx context.Context, id pgtype.UUID) (Store, error) {
	row := q.db.QueryRow(ctx, getStoreByID, id)
	var i Store
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Active,
		&i.WhatsappNumber,
		&i.EmailAddress,
		&i.SmsNumber,
		&i.CreatedAt,
		&i.CartEnabled,
		&i.CartExpirationMinutes,
		&i.CartReserveStock,
		&i.CartMaxItems,
		&i.CartMaxQuantityPerItem,
		&i.UpdatedAt,
		&i.Description,
		&i.Website,
		&i.LogoUrl,
		&i.AddressStreet,
		&i.AddressCity,
		&i.AddressState,
		&i.AddressZip,
		&i.AddressCountry,
		&i.SendOnLiveEnd,
		&i.CartAllowEdit,
		&i.CheckoutSendMethods,
		&i.NotificationSettings,
		&i.CartMessageCooldownSeconds,
		&i.CartSendExpirationReminder,
		&i.CartExpirationReminderMinutes,
		&i.CartRealTime,
		&i.Cnpj,
		&i.AddressNumber,
		&i.AddressComplement,
		&i.AddressDistrict,
		&i.AddressStateRegister,
		&i.DefaultPackageWeightGrams,
		&i.DefaultPackageFormat,
		&i.DefaultHeightCm,
		&i.DefaultWidthCm,
		&i.DefaultLengthCm,
	)
	return i, err
}

const getStoreByOwnerUserID = `-- name: GetStoreByOwnerUserID :one
SELECT s.id, s.name, s.slug, s.active, s.whatsapp_number, s.email_address, s.sms_number, s.created_at, s.cart_enabled, s.cart_expiration_minutes, s.cart_reserve_stock, s.cart_max_items, s.cart_max_quantity_per_item, s.updated_at, s.description, s.website, s.logo_url, s.address_street, s.address_city, s.address_state, s.address_zip, s.address_country, s.send_on_live_end, s.cart_allow_edit, s.checkout_send_methods, s.notification_settings, s.cart_message_cooldown_seconds, s.cart_send_expiration_reminder, s.cart_expiration_reminder_minutes, s.cart_real_time, s.cnpj, s.address_number, s.address_complement, s.address_district, s.address_state_register, s.default_package_weight_grams, s.default_package_format, s.default_height_cm, s.default_width_cm, s.default_length_cm
FROM stores s
JOIN memberships m ON s.id = m.store_id
WHERE m.user_id = $1 AND m.role = 'owner'
LIMIT 1
`

// Get store where user is owner
func (q *Queries) GetStoreByOwnerUserID(ctx context.Context, userID pgtype.UUID) (Store, error) {
	row := q.db.QueryRow(ctx, getStoreByOwnerUserID, userID)
	var i Store
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Active,
		&i.WhatsappNumber,
		&i.EmailAddress,
		&i.SmsNumber,
		&i.CreatedAt,
		&i.CartEnabled,
		&i.CartExpirationMinutes,
		&i.CartReserveStock,
		&i.CartMaxItems,
		&i.CartMaxQuantityPerItem,
		&i.UpdatedAt,
		&i.Description,
		&i.Website,
		&i.LogoUrl,
		&i.AddressStreet,
		&i.AddressCity,
		&i.AddressState,
		&i.AddressZip,
		&i.AddressCountry,
		&i.SendOnLiveEnd,
		&i.CartAllowEdit,
		&i.CheckoutSendMethods,
		&i.NotificationSettings,
		&i.CartMessageCooldownSeconds,
		&i.CartSendExpirationReminder,
		&i.CartExpirationReminderMinutes,
		&i.CartRealTime,
		&i.Cnpj,
		&i.AddressNumber,
		&i.AddressComplement,
		&i.AddressDistrict,
		&i.AddressStateRegister,
		&i.DefaultPackageWeightGrams,
		&i.DefaultPackageFormat,
		&i.DefaultHeightCm,
		&i.DefaultWidthCm,
		&i.DefaultLengthCm,
	)
	return i, err
}

const getStoreBySlug = `-- name: GetStoreBySlug :one
SELECT id, name, slug, active, whatsapp_number, email_address, sms_number, created_at, cart_enabled, cart_expiration_minutes, cart_reserve_stock, cart_max_items, cart_max_quantity_per_item, updated_at, description, website, logo_url, address_street, address_city, address_state, address_zip, address_country, send_on_live_end, cart_allow_edit, checkout_send_methods, notification_settings, cart_message_cooldown_seconds, cart_send_expiration_reminder, cart_expiration_reminder_minutes, cart_real_time, cnpj, address_number, address_complement, address_district, address_state_register, default_package_weight_grams, default_package_format, default_height_cm, default_width_cm, default_length_cm FROM stores WHERE slug = $1
`

func (q *Queries) GetStoreBySlug(ctx context.Context, slug string) (Store, error) {
	row := q.db.QueryRow(ctx, getStoreBySlug, slug)
	var i Store
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Active,
		&i.WhatsappNumber,
		&i.EmailAddress,
		&i.SmsNumber,
		&i.CreatedAt,
		&i.CartEnabled,
		&i.CartExpirationMinutes,
		&i.CartReserveStock,
		&i.CartMaxItems,
		&i.CartMaxQuantityPerItem,
		&i.UpdatedAt,
		&i.Description,
		&i.Website,
		&i.LogoUrl,
		&i.AddressStreet,
		&i.AddressCity,
		&i.AddressState,
		&i.AddressZip,
		&i.AddressCountry,
		&i.SendOnLiveEnd,
		&i.CartAllowEdit,
		&i.CheckoutSendMethods,
		&i.NotificationSettings,
		&i.CartMessageCooldownSeconds,
		&i.CartSendExpirationReminder,
		&i.CartExpirationReminderMinutes,
		&i.CartRealTime,
		&i.Cnpj,
		&i.AddressNumber,
		&i.AddressComplement,
		&i.AddressDistrict,
		&i.AddressStateRegister,
		&i.DefaultPackageWeightGrams,
		&i.DefaultPackageFormat,
		&i.DefaultHeightCm,
		&i.DefaultWidthCm,
		&i.DefaultLengthCm,
	)
	return i, err
}

const getStoreByUserID = `-- name: GetStoreByUserID :one
SELECT s.id, s.name, s.slug, s.active, s.whatsapp_number, s.email_address, s.sms_number, s.created_at, s.cart_enabled, s.cart_expiration_minutes, s.cart_reserve_stock, s.cart_max_items, s.cart_max_quantity_per_item, s.updated_at, s.description, s.website, s.logo_url, s.address_street, s.address_city, s.address_state, s.address_zip, s.address_country, s.send_on_live_end, s.cart_allow_edit, s.checkout_send_methods, s.notification_settings, s.cart_message_cooldown_seconds, s.cart_send_expiration_reminder, s.cart_expiration_reminder_minutes, s.cart_real_time, s.cnpj, s.address_number, s.address_complement, s.address_district, s.address_state_register, s.default_package_weight_grams, s.default_package_format, s.default_height_cm, s.default_width_cm, s.default_length_cm
FROM stores s
JOIN memberships m ON s.id = m.store_id
WHERE m.user_id = $1 AND m.status = 'active'
`

// Get the single store for a user (1 user = 1 store)
func (q *Queries) GetStoreByUserID(ctx context.Context, userID pgtype.UUID) (Store, error) {
	row := q.db.QueryRow(ctx, getStoreByUserID, userID)
	var i Store
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Active,
		&i.WhatsappNumber,
		&i.EmailAddress,
		&i.SmsNumber,
		&i.CreatedAt,
		&i.CartEnabled,
		&i.CartExpirationMinutes,
		&i.CartReserveStock,
		&i.CartMaxItems,
		&i.CartMaxQuantityPerItem,
		&i.UpdatedAt,
		&i.Description,
		&i.Website,
		&i.LogoUrl,
		&i.AddressStreet,
		&i.AddressCity,
		&i.AddressState,
		&i.AddressZip,
		&i.AddressCountry,
		&i.SendOnLiveEnd,
		&i.CartAllowEdit,
		&i.CheckoutSendMethods,
		&i.NotificationSettings,
		&i.CartMessageCooldownSeconds,
		&i.CartSendExpirationReminder,
		&i.CartExpirationReminderMinutes,
		&i.CartRealTime,
		&i.Cnpj,
		&i.AddressNumber,
		&i.AddressComplement,
		&i.AddressDistrict,
		&i.AddressStateRegister,
		&i.DefaultPackageWeightGrams,
		&i.DefaultPackageFormat,
		&i.DefaultHeightCm,
		&i.DefaultWidthCm,
		&i.DefaultLengthCm,
	)
	return i, err
}

const getStoreNameByID = `-- name: GetStoreNameByID :one
SELECT name, cart_expiration_minutes, cart_max_quantity_per_item FROM stores WHERE id = $1
`

type GetStoreNameByIDRow struct {
	Name                   string `json:"name"`
	CartExpirationMinutes  int32  `json:"cart_expiration_minutes"`
	CartMaxQuantityPerItem int32  `json:"cart_max_quantity_per_item"`
}

func (q *Queries) GetStoreNameByID(ctx context.Context, id pgtype.UUID) (GetStoreNameByIDRow, error) {
	row := q.db.QueryRow(ctx, getStoreNameByID, id)
	var i GetStoreNameByIDRow
	err := row.Scan(&i.Name, &i.CartExpirationMinutes, &i.CartMaxQuantityPerItem)
	return i, err
}

const listStoreMembers = `-- name: ListStoreMembers :many
SELECT id, store_id, role, created_at, updated_at, status, invited_by, invited_at, user_id FROM memberships WHERE store_id = $1 ORDER BY created_at
`

func (q *Queries) ListStoreMembers(ctx context.Context, storeID pgtype.UUID) ([]Membership, error) {
	rows, err := q.db.Query(ctx, listStoreMembers, storeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Membership{}
	for rows.Next() {
		var i Membership
		if err := rows.Scan(
			&i.ID,
			&i.StoreID,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Status,
			&i.InvitedBy,
			&i.InvitedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStore = `-- name: UpdateStore :one
UPDATE stores
SET
  name = $2,
  whatsapp_number = $3,
  email_address = $4,
  sms_number = $5,
  description = $6,
  website = $7,
  logo_url = $8,
  address_street = $9,
  address_city = $10,
  address_state = $11,
  address_zip = $12,
  address_country = $13,
  cnpj = $14,
  address_number = $15,
  address_complement = $16,
  address_district = $17,
  address_state_register = $18,
  updated_at = now()
WHERE id = $1
RETURNING id, name, slug, active, whatsapp_number, email_address, sms_number, created_at, cart_enabled, cart_expiration_minutes, cart_reserve_stock, cart_max_items, cart_max_quantity_per_item, updated_at, description, website, logo_url, address_street, address_city, address_state, address_zip, address_country, send_on_live_end, cart_allow_edit, checkout_send_methods, notification_settings, cart_message_cooldown_seconds, cart_send_expiration_reminder, cart_expiration_reminder_minutes, cart_real_time, cnpj, address_number, address_complement, address_district, address_state_register, default_package_weight_grams, default_package_format, default_height_cm, default_width_cm, default_length_cm
`

type UpdateStoreParams struct {
	ID                   pgtype.UUID `json:"id"`
	Name                 string      `json:"name"`
	WhatsappNumber       pgtype.Text `json:"whatsapp_number"`
	EmailAddress         pgtype.Text `json:"email_address"`
	SmsNumber            pgtype.Text `json:"sms_number"`
	Description          pgtype.Text `json:"description"`
	Website              pgtype.Text `json:"website"`
	LogoUrl              pgtype.Text `json:"logo_url"`
	AddressStreet        pgtype.Text `json:"address_street"`
	AddressCity          pgtype.Text `json:"address_city"`
	AddressState         pgtype.Text `json:"address_state"`
	AddressZip           pgtype.Text `json:"address_zip"`
	AddressCountry       pgtype.Text `json:"address_country"`
	Cnpj                 pgtype.Text `json:"cnpj"`
	AddressNumber        pgtype.Text `json:"address_number"`
	AddressComplement    pgtype.Text `json:"address_complement"`
	AddressDistrict      pgtype.Text `json:"address_district"`
	AddressStateRegister pgtype.Text `json:"address_state_register"`
}

func (q *Queries) UpdateStore(ctx context.Context, arg UpdateStoreParams) (Store, error) {
	row := q.db.QueryRow(ctx, updateStore,
		arg.ID,
		arg.Name,
		arg.WhatsappNumber,
		arg.EmailAddress,
		arg.SmsNumber,
		arg.Description,
		arg.Website,
		arg.LogoUrl,
		arg.AddressStreet,
		arg.AddressCity,
		arg.AddressState,
		arg.AddressZip,
		arg.AddressCountry,
		arg.Cnpj,
		arg.AddressNumber,
		arg.AddressComplement,
		arg.AddressDistrict,
		arg.AddressStateRegister,
	)
	var i Store
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Active,
		&i.WhatsappNumber,
		&i.EmailAddress,
		&i.SmsNumber,
		&i.CreatedAt,
		&i.CartEnabled,
		&i.CartExpirationMinutes,
		&i.CartReserveStock,
		&i.CartMaxItems,
		&i.CartMaxQuantityPerItem,
		&i.UpdatedAt,
		&i.Description,
		&i.Website,
		&i.LogoUrl,
		&i.AddressStreet,
		&i.AddressCity,
		&i.AddressState,
		&i.AddressZip,
		&i.AddressCountry,
		&i.SendOnLiveEnd,
		&i.CartAllowEdit,
		&i.CheckoutSendMethods,
		&i.NotificationSettings,
		&i.CartMessageCooldownSeconds,
		&i.CartSendExpirationReminder,
		&i.CartExpirationReminderMinutes,
		&i.CartRealTime,
		&i.Cnpj,
		&i.AddressNumber,
		&i.AddressComplement,
		&i.AddressDistrict,
		&i.AddressStateRegister,
		&i.DefaultPackageWeightGrams,
		&i.DefaultPackageFormat,
		&i.DefaultHeightCm,
		&i.DefaultWidthCm,
		&i.DefaultLengthCm,
	)
	return i, err
}

const updateStoreCartSettings = `-- name: UpdateStoreCartSettings :one
UPDATE stores
SET
  cart_enabled = $2,
  cart_expiration_minutes = $3,
  cart_reserve_stock = $4,
  cart_max_quantity_per_item = $5,
  cart_allow_edit = $6,
  cart_real_time = $7,
  send_on_live_end = $8,
  checkout_send_methods = $9,
  cart_message_cooldown_seconds = $10,
  cart_send_expiration_reminder = $11,
  cart_expiration_reminder_minutes = $12,
  updated_at = now()
WHERE id = $1
RETURNING id, name, slug, active, whatsapp_number, email_address, sms_number, created_at, cart_enabled, cart_expiration_minutes, cart_reserve_stock, cart_max_items, cart_max_quantity_per_item, updated_at, description, website, logo_url, address_street, address_city, address_state, address_zip, address_country, send_on_live_end, cart_allow_edit, checkout_send_methods, notification_settings, cart_message_cooldown_seconds, cart_send_expiration_reminder, cart_expiration_reminder_minutes, cart_real_time, cnpj, address_number, address_complement, address_district, address_state_register, default_package_weight_grams, default_package_format, default_height_cm, default_width_cm, default_length_cm
`

type UpdateStoreCartSettingsParams struct {
	ID                            pgtype.UUID     `json:"id"`
	CartEnabled                   bool            `json:"cart_enabled"`
	CartExpirationMinutes         int32           `json:"cart_expiration_minutes"`
	CartReserveStock              bool            `json:"cart_reserve_stock"`
	CartMaxQuantityPerItem        int32           `json:"cart_max_quantity_per_item"`
	CartAllowEdit                 bool            `json:"cart_allow_edit"`
	CartRealTime                  bool            `json:"cart_real_time"`
	SendOnLiveEnd                 bool            `json:"send_on_live_end"`
	CheckoutSendMethods           json.RawMessage `json:"checkout_send_methods"`
	CartMessageCooldownSeconds    int32           `json:"cart_message_cooldown_seconds"`
	CartSendExpirationReminder    bool            `json:"cart_send_expiration_reminder"`
	CartExpirationReminderMinutes int32           `json:"cart_expiration_reminder_minutes"`
}

func (q *Queries) UpdateStoreCartSettings(ctx context.Context, arg UpdateStoreCartSettingsParams) (Store, error) {
	row := q.db.QueryRow(ctx, updateStoreCartSettings,
		arg.ID,
		arg.CartEnabled,
		arg.CartExpirationMinutes,
		arg.CartReserveStock,
		arg.CartMaxQuantityPerItem,
		arg.CartAllowEdit,
		arg.CartRealTime,
		arg.SendOnLiveEnd,
		arg.CheckoutSendMethods,
		arg.CartMessageCooldownSeconds,
		arg.CartSendExpirationReminder,
		arg.CartExpirationReminderMinutes,
	)
	var i Store
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Active,
		&i.WhatsappNumber,
		&i.EmailAddress,
		&i.SmsNumber,
		&i.CreatedAt,
		&i.CartEnabled,
		&i.CartExpirationMinutes,
		&i.CartReserveStock,
		&i.CartMaxItems,
		&i.CartMaxQuantityPerItem,
		&i.UpdatedAt,
		&i.Description,
		&i.Website,
		&i.LogoUrl,
		&i.AddressStreet,
		&i.AddressCity,
		&i.AddressState,
		&i.AddressZip,
		&i.AddressCountry,
		&i.SendOnLiveEnd,
		&i.CartAllowEdit,
		&i.CheckoutSendMethods,
		&i.NotificationSettings,
		&i.CartMessageCooldownSeconds,
		&i.CartSendExpirationReminder,
		&i.CartExpirationReminderMinutes,
		&i.CartRealTime,
		&i.Cnpj,
		&i.AddressNumber,
		&i.AddressComplement,
		&i.AddressDistrict,
		&i.AddressStateRegister,
		&i.DefaultPackageWeightGrams,
		&i.DefaultPackageFormat,
		&i.DefaultHeightCm,
		&i.DefaultWidthCm,
		&i.DefaultLengthCm,
	)
	return i, err
}

const updateStoreCheckoutSettings = `-- name: UpdateStoreCheckoutSettings :one
UPDATE stores
SET
  checkout_send_methods = $2,
  send_on_live_end = $3,
  updated_at = now()
WHERE id = $1
RETURNING id, name, slug, active, whatsapp_number, email_address, sms_number, created_at, cart_enabled, cart_expiration_minutes, cart_reserve_stock, cart_max_items, cart_max_quantity_per_item, updated_at, description, website, logo_url, address_street, address_city, address_state, address_zip, address_country, send_on_live_end, cart_allow_edit, checkout_send_methods, notification_settings, cart_message_cooldown_seconds, cart_send_expiration_reminder, cart_expiration_reminder_minutes, cart_real_time, cnpj, address_number, address_complement, address_district, address_state_register, default_package_weight_grams, default_package_format, default_height_cm, default_width_cm, default_length_cm
`

type UpdateStoreCheckoutSettingsParams struct {
	ID                  pgtype.UUID     `json:"id"`
	CheckoutSendMethods json.RawMessage `json:"checkout_send_methods"`
	SendOnLiveEnd       bool            `json:"send_on_live_end"`
}

func (q *Queries) UpdateStoreCheckoutSettings(ctx context.Context, arg UpdateStoreCheckoutSettingsParams) (Store, error) {
	row := q.db.QueryRow(ctx, updateStoreCheckoutSettings, arg.ID, arg.CheckoutSendMethods, arg.SendOnLiveEnd)
	var i Store
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Active,
		&i.WhatsappNumber,
		&i.EmailAddress,
		&i.SmsNumber,
		&i.CreatedAt,
		&i.CartEnabled,
		&i.CartExpirationMinutes,
		&i.CartReserveStock,
		&i.CartMaxItems,
		&i.CartMaxQuantityPerItem,
		&i.UpdatedAt,
		&i.Description,
		&i.Website,
		&i.LogoUrl,
		&i.AddressStreet,
		&i.AddressCity,
		&i.AddressState,
		&i.AddressZip,
		&i.AddressCountry,
		&i.SendOnLiveEnd,
		&i.CartAllowEdit,
		&i.CheckoutSendMethods,
		&i.NotificationSettings,
		&i.CartMessageCooldownSeconds,
		&i.CartSendExpirationReminder,
		&i.CartExpirationReminderMinutes,
		&i.CartRealTime,
		&i.Cnpj,
		&i.AddressNumber,
		&i.AddressComplement,
		&i.AddressDistrict,
		&i.AddressStateRegister,
		&i.DefaultPackageWeightGrams,
		&i.DefaultPackageFormat,
		&i.DefaultHeightCm,
		&i.DefaultWidthCm,
		&i.DefaultLengthCm,
	)
	return i, err
}

const updateStoreLogoURL = `-- name: UpdateStoreLogoURL :one
UPDATE stores
SET
  logo_url = $2,
  updated_at = now()
WHERE id = $1
RETURNING id, name, slug, active, whatsapp_number, email_address, sms_number, created_at, cart_enabled, cart_expiration_minutes, cart_reserve_stock, cart_max_items, cart_max_quantity_per_item, updated_at, description, website, logo_url, address_street, address_city, address_state, address_zip, address_country, send_on_live_end, cart_allow_edit, checkout_send_methods, notification_settings, cart_message_cooldown_seconds, cart_send_expiration_reminder, cart_expiration_reminder_minutes, cart_real_time, cnpj, address_number, address_complement, address_district, address_state_register, default_package_weight_grams, default_package_format, default_height_cm, default_width_cm, default_length_cm
`

type UpdateStoreLogoURLParams struct {
	ID      pgtype.UUID `json:"id"`
	LogoUrl pgtype.Text `json:"logo_url"`
}

func (q *Queries) UpdateStoreLogoURL(ctx context.Context, arg UpdateStoreLogoURLParams) (Store, error) {
	row := q.db.QueryRow(ctx, updateStoreLogoURL, arg.ID, arg.LogoUrl)
	var i Store
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Active,
		&i.WhatsappNumber,
		&i.EmailAddress,
		&i.SmsNumber,
		&i.CreatedAt,
		&i.CartEnabled,
		&i.CartExpirationMinutes,
		&i.CartReserveStock,
		&i.CartMaxItems,
		&i.CartMaxQuantityPerItem,
		&i.UpdatedAt,
		&i.Description,
		&i.Website,
		&i.LogoUrl,
		&i.AddressStreet,
		&i.AddressCity,
		&i.AddressState,
		&i.AddressZip,
		&i.AddressCountry,
		&i.SendOnLiveEnd,
		&i.CartAllowEdit,
		&i.CheckoutSendMethods,
		&i.NotificationSettings,
		&i.CartMessageCooldownSeconds,
		&i.CartSendExpirationReminder,
		&i.CartExpirationReminderMinutes,
		&i.CartRealTime,
		&i.Cnpj,
		&i.AddressNumber,
		&i.AddressComplement,
		&i.AddressDistrict,
		&i.AddressStateRegister,
		&i.DefaultPackageWeightGrams,
		&i.DefaultPackageFormat,
		&i.DefaultHeightCm,
		&i.DefaultWidthCm,
		&i.DefaultLengthCm,
	)
	return i, err
}

const updateStoreShippingDefaults = `-- name: UpdateStoreShippingDefaults :one
UPDATE stores
SET
  default_package_weight_grams = $2,
  default_package_format       = $3,
  default_height_cm            = $4,
  default_width_cm             = $5,
  default_length_cm            = $6,
  updated_at                   = now()
WHERE id = $1
RETURNING id, name, slug, active, whatsapp_number, email_address, sms_number, created_at, cart_enabled, cart_expiration_minutes, cart_reserve_stock, cart_max_items, cart_max_quantity_per_item, updated_at, description, website, logo_url, address_street, address_city, address_state, address_zip, address_country, send_on_live_end, cart_allow_edit, checkout_send_methods, notification_settings, cart_message_cooldown_seconds, cart_send_expiration_reminder, cart_expiration_reminder_minutes, cart_real_time, cnpj, address_number, address_complement, address_district, address_state_register, default_package_weight_grams, default_package_format, default_height_cm, default_width_cm, default_length_cm
`

type UpdateStoreShippingDefaultsParams struct {
	ID                        pgtype.UUID `json:"id"`
	DefaultPackageWeightGrams int32       `json:"default_package_weight_grams"`
	DefaultPackageFormat      string      `json:"default_package_format"`
	DefaultHeightCm           pgtype.Int4 `json:"default_height_cm"`
	DefaultWidthCm            pgtype.Int4 `json:"default_width_cm"`
	DefaultLengthCm           pgtype.Int4 `json:"default_length_cm"`
}

func (q *Queries) UpdateStoreShippingDefaults(ctx context.Context, arg UpdateStoreShippingDefaultsParams) (Store, error) {
	row := q.db.QueryRow(ctx, updateStoreShippingDefaults,
		arg.ID,
		arg.DefaultPackageWeightGrams,
		arg.DefaultPackageFormat,
		arg.DefaultHeightCm,
		arg.DefaultWidthCm,
		arg.DefaultLengthCm,
	)
	var i Store
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Active,
		&i.WhatsappNumber,
		&i.EmailAddress,
		&i.SmsNumber,
		&i.CreatedAt,
		&i.CartEnabled,
		&i.CartExpirationMinutes,
		&i.CartReserveStock,
		&i.CartMaxItems,
		&i.CartMaxQuantityPerItem,
		&i.UpdatedAt,
		&i.Description,
		&i.Website,
		&i.LogoUrl,
		&i.AddressStreet,
		&i.AddressCity,
		&i.AddressState,
		&i.AddressZip,
		&i.AddressCountry,
		&i.SendOnLiveEnd,
		&i.CartAllowEdit,
		&i.CheckoutSendMethods,
		&i.NotificationSettings,
		&i.CartMessageCooldownSeconds,
		&i.CartSendExpirationReminder,
		&i.CartExpirationReminderMinutes,
		&i.CartRealTime,
		&i.Cnpj,
		&i.AddressNumber,
		&i.AddressComplement,
		&i.AddressDistrict,
		&i.AddressStateRegister,
		&i.DefaultPackageWeightGrams,
		&i.DefaultPackageFormat,
		&i.DefaultHeightCm,
		&i.DefaultWidthCm,
		&i.DefaultLengthCm,
	)
	return i, err
}
