// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acceptInvitation = `-- name: AcceptInvitation :one
UPDATE store_invitations
SET status = 'accepted', accepted_at = now()
WHERE id = $1 AND status = 'pending'
RETURNING id, store_id, email, role, token, invited_by, status, expires_at, accepted_at, created_at
`

func (q *Queries) AcceptInvitation(ctx context.Context, id pgtype.UUID) (StoreInvitation, error) {
	row := q.db.QueryRow(ctx, acceptInvitation, id)
	var i StoreInvitation
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.Email,
		&i.Role,
		&i.Token,
		&i.InvitedBy,
		&i.Status,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.CreatedAt,
	)
	return i, err
}

const countStoreMembers = `-- name: CountStoreMembers :one
SELECT COUNT(*) FROM memberships WHERE store_id = $1 AND status = 'active'
`

func (q *Queries) CountStoreMembers(ctx context.Context, storeID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countStoreMembers, storeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createInvitation = `-- name: CreateInvitation :one

INSERT INTO store_invitations (store_id, email, role, token, invited_by, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, store_id, email, role, token, invited_by, status, expires_at, created_at
`

type CreateInvitationParams struct {
	StoreID   pgtype.UUID        `json:"store_id"`
	Email     string             `json:"email"`
	Role      string             `json:"role"`
	Token     string             `json:"token"`
	InvitedBy pgtype.UUID        `json:"invited_by"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

type CreateInvitationRow struct {
	ID        pgtype.UUID        `json:"id"`
	StoreID   pgtype.UUID        `json:"store_id"`
	Email     string             `json:"email"`
	Role      string             `json:"role"`
	Token     string             `json:"token"`
	InvitedBy pgtype.UUID        `json:"invited_by"`
	Status    string             `json:"status"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// ============================================
// INVITATION QUERIES
// ============================================
func (q *Queries) CreateInvitation(ctx context.Context, arg CreateInvitationParams) (CreateInvitationRow, error) {
	row := q.db.QueryRow(ctx, createInvitation,
		arg.StoreID,
		arg.Email,
		arg.Role,
		arg.Token,
		arg.InvitedBy,
		arg.ExpiresAt,
	)
	var i CreateInvitationRow
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.Email,
		&i.Role,
		&i.Token,
		&i.InvitedBy,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createMembership = `-- name: CreateMembership :one
INSERT INTO memberships (store_id, user_id, role, status, invited_by, invited_at)
VALUES ($1, $2, $3, 'active', $4, $5)
RETURNING id, store_id, user_id, role, status, invited_by, invited_at, created_at, updated_at
`

type CreateMembershipParams struct {
	StoreID   pgtype.UUID        `json:"store_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Role      string             `json:"role"`
	InvitedBy pgtype.UUID        `json:"invited_by"`
	InvitedAt pgtype.Timestamptz `json:"invited_at"`
}

type CreateMembershipRow struct {
	ID        pgtype.UUID        `json:"id"`
	StoreID   pgtype.UUID        `json:"store_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Role      string             `json:"role"`
	Status    string             `json:"status"`
	InvitedBy pgtype.UUID        `json:"invited_by"`
	InvitedAt pgtype.Timestamptz `json:"invited_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// Create a membership (user joins a store)
func (q *Queries) CreateMembership(ctx context.Context, arg CreateMembershipParams) (CreateMembershipRow, error) {
	row := q.db.QueryRow(ctx, createMembership,
		arg.StoreID,
		arg.UserID,
		arg.Role,
		arg.InvitedBy,
		arg.InvitedAt,
	)
	var i CreateMembershipRow
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.InvitedBy,
		&i.InvitedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOwnerMembership = `-- name: CreateOwnerMembership :one
INSERT INTO memberships (store_id, user_id, role, status)
VALUES ($1, $2, 'owner', 'active')
RETURNING id, store_id, user_id, role, status, created_at, updated_at
`

type CreateOwnerMembershipParams struct {
	StoreID pgtype.UUID `json:"store_id"`
	UserID  pgtype.UUID `json:"user_id"`
}

type CreateOwnerMembershipRow struct {
	ID        pgtype.UUID        `json:"id"`
	StoreID   pgtype.UUID        `json:"store_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Role      string             `json:"role"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// Create owner membership when creating a new store
func (q *Queries) CreateOwnerMembership(ctx context.Context, arg CreateOwnerMembershipParams) (CreateOwnerMembershipRow, error) {
	row := q.db.QueryRow(ctx, createOwnerMembership, arg.StoreID, arg.UserID)
	var i CreateOwnerMembershipRow
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one

INSERT INTO users (clerk_id, email, name, avatar_url)
VALUES ($1, $2, $3, $4)
RETURNING id, clerk_id, email, name, avatar_url, created_at, updated_at
`

type CreateUserParams struct {
	ClerkID   string      `json:"clerk_id"`
	Email     string      `json:"email"`
	Name      pgtype.Text `json:"name"`
	AvatarUrl pgtype.Text `json:"avatar_url"`
}

// ============================================
// USER QUERIES (new users table)
// ============================================
// Create a new user (from Clerk webhook or sync fallback)
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ClerkID,
		arg.Email,
		arg.Name,
		arg.AvatarUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ClerkID,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteInvitation = `-- name: DeleteInvitation :exec
DELETE FROM store_invitations WHERE store_id = $1 AND id = $2
`

type DeleteInvitationParams struct {
	StoreID pgtype.UUID `json:"store_id"`
	ID      pgtype.UUID `json:"id"`
}

func (q *Queries) DeleteInvitation(ctx context.Context, arg DeleteInvitationParams) error {
	_, err := q.db.Exec(ctx, deleteInvitation, arg.StoreID, arg.ID)
	return err
}

const deleteMembership = `-- name: DeleteMembership :exec
DELETE FROM memberships WHERE store_id = $1 AND id = $2
`

type DeleteMembershipParams struct {
	StoreID pgtype.UUID `json:"store_id"`
	ID      pgtype.UUID `json:"id"`
}

func (q *Queries) DeleteMembership(ctx context.Context, arg DeleteMembershipParams) error {
	_, err := q.db.Exec(ctx, deleteMembership, arg.StoreID, arg.ID)
	return err
}

const deleteMembershipByUserID = `-- name: DeleteMembershipByUserID :exec
DELETE FROM memberships WHERE user_id = $1
`

// Delete membership by user ID (for when member accepts invite to new store)
func (q *Queries) DeleteMembershipByUserID(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteMembershipByUserID, userID)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE clerk_id = $1
`

// Delete a user (cascades to memberships)
func (q *Queries) DeleteUser(ctx context.Context, clerkID string) error {
	_, err := q.db.Exec(ctx, deleteUser, clerkID)
	return err
}

const expireInvitations = `-- name: ExpireInvitations :exec
UPDATE store_invitations
SET status = 'expired'
WHERE status = 'pending' AND expires_at < now()
`

// Mark expired invitations (run periodically)
func (q *Queries) ExpireInvitations(ctx context.Context) error {
	_, err := q.db.Exec(ctx, expireInvitations)
	return err
}

const getInvitationByEmail = `-- name: GetInvitationByEmail :one
SELECT
  si.id,
  si.store_id,
  si.email,
  si.role,
  si.token,
  si.invited_by,
  si.status,
  si.expires_at,
  si.accepted_at,
  si.created_at
FROM store_invitations si
WHERE si.store_id = $1 AND si.email = $2 AND si.status = 'pending'
`

type GetInvitationByEmailParams struct {
	StoreID pgtype.UUID `json:"store_id"`
	Email   string      `json:"email"`
}

func (q *Queries) GetInvitationByEmail(ctx context.Context, arg GetInvitationByEmailParams) (StoreInvitation, error) {
	row := q.db.QueryRow(ctx, getInvitationByEmail, arg.StoreID, arg.Email)
	var i StoreInvitation
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.Email,
		&i.Role,
		&i.Token,
		&i.InvitedBy,
		&i.Status,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getInvitationByID = `-- name: GetInvitationByID :one
SELECT
  si.id,
  si.store_id,
  si.email,
  si.role,
  si.token,
  si.invited_by,
  si.status,
  si.expires_at,
  si.accepted_at,
  si.created_at,
  s.name as store_name,
  s.slug as store_slug
FROM store_invitations si
JOIN stores s ON s.id = si.store_id
WHERE si.store_id = $1 AND si.id = $2
`

type GetInvitationByIDParams struct {
	StoreID pgtype.UUID `json:"store_id"`
	ID      pgtype.UUID `json:"id"`
}

type GetInvitationByIDRow struct {
	ID         pgtype.UUID        `json:"id"`
	StoreID    pgtype.UUID        `json:"store_id"`
	Email      string             `json:"email"`
	Role       string             `json:"role"`
	Token      string             `json:"token"`
	InvitedBy  pgtype.UUID        `json:"invited_by"`
	Status     string             `json:"status"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	AcceptedAt pgtype.Timestamptz `json:"accepted_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	StoreName  string             `json:"store_name"`
	StoreSlug  string             `json:"store_slug"`
}

func (q *Queries) GetInvitationByID(ctx context.Context, arg GetInvitationByIDParams) (GetInvitationByIDRow, error) {
	row := q.db.QueryRow(ctx, getInvitationByID, arg.StoreID, arg.ID)
	var i GetInvitationByIDRow
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.Email,
		&i.Role,
		&i.Token,
		&i.InvitedBy,
		&i.Status,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.CreatedAt,
		&i.StoreName,
		&i.StoreSlug,
	)
	return i, err
}

const getInvitationByToken = `-- name: GetInvitationByToken :one
SELECT
  si.id,
  si.store_id,
  si.email,
  si.role,
  si.token,
  si.invited_by,
  si.status,
  si.expires_at,
  si.accepted_at,
  si.created_at,
  s.name as store_name,
  s.slug as store_slug,
  inviter_user.name as inviter_name
FROM store_invitations si
JOIN stores s ON s.id = si.store_id
JOIN memberships inviter ON inviter.id = si.invited_by
JOIN users inviter_user ON inviter_user.id = inviter.user_id
WHERE si.token = $1
`

type GetInvitationByTokenRow struct {
	ID          pgtype.UUID        `json:"id"`
	StoreID     pgtype.UUID        `json:"store_id"`
	Email       string             `json:"email"`
	Role        string             `json:"role"`
	Token       string             `json:"token"`
	InvitedBy   pgtype.UUID        `json:"invited_by"`
	Status      string             `json:"status"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	AcceptedAt  pgtype.Timestamptz `json:"accepted_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	StoreName   string             `json:"store_name"`
	StoreSlug   string             `json:"store_slug"`
	InviterName pgtype.Text        `json:"inviter_name"`
}

func (q *Queries) GetInvitationByToken(ctx context.Context, token string) (GetInvitationByTokenRow, error) {
	row := q.db.QueryRow(ctx, getInvitationByToken, token)
	var i GetInvitationByTokenRow
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.Email,
		&i.Role,
		&i.Token,
		&i.InvitedBy,
		&i.Status,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.CreatedAt,
		&i.StoreName,
		&i.StoreSlug,
		&i.InviterName,
	)
	return i, err
}

const getMembershipByID = `-- name: GetMembershipByID :one
SELECT
  m.id,
  m.store_id,
  m.user_id,
  m.role,
  m.status,
  m.invited_by,
  m.invited_at,
  m.created_at,
  m.updated_at,
  u.clerk_id,
  u.email,
  u.name,
  u.avatar_url
FROM memberships m
JOIN users u ON u.id = m.user_id
WHERE m.id = $1
`

type GetMembershipByIDRow struct {
	ID        pgtype.UUID        `json:"id"`
	StoreID   pgtype.UUID        `json:"store_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Role      string             `json:"role"`
	Status    string             `json:"status"`
	InvitedBy pgtype.UUID        `json:"invited_by"`
	InvitedAt pgtype.Timestamptz `json:"invited_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	ClerkID   string             `json:"clerk_id"`
	Email     string             `json:"email"`
	Name      pgtype.Text        `json:"name"`
	AvatarUrl pgtype.Text        `json:"avatar_url"`
}

// Get membership by ID with user info
func (q *Queries) GetMembershipByID(ctx context.Context, id pgtype.UUID) (GetMembershipByIDRow, error) {
	row := q.db.QueryRow(ctx, getMembershipByID, id)
	var i GetMembershipByIDRow
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.InvitedBy,
		&i.InvitedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClerkID,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
	)
	return i, err
}

const getMembershipByUserID = `-- name: GetMembershipByUserID :one

SELECT
  m.id,
  m.store_id,
  m.user_id,
  m.role,
  m.status,
  m.created_at,
  m.updated_at,
  u.email,
  u.name,
  u.avatar_url,
  s.name as store_name,
  s.slug as store_slug
FROM memberships m
JOIN users u ON u.id = m.user_id
JOIN stores s ON s.id = m.store_id
WHERE m.user_id = $1 AND m.status = 'active'
`

type GetMembershipByUserIDRow struct {
	ID        pgtype.UUID        `json:"id"`
	StoreID   pgtype.UUID        `json:"store_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Role      string             `json:"role"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	Email     string             `json:"email"`
	Name      pgtype.Text        `json:"name"`
	AvatarUrl pgtype.Text        `json:"avatar_url"`
	StoreName string             `json:"store_name"`
	StoreSlug string             `json:"store_slug"`
}

// ============================================
// MEMBERSHIP QUERIES (Single store per user)
// ============================================
// Get the single membership for a user (1 user = 1 store)
func (q *Queries) GetMembershipByUserID(ctx context.Context, userID pgtype.UUID) (GetMembershipByUserIDRow, error) {
	row := q.db.QueryRow(ctx, getMembershipByUserID, userID)
	var i GetMembershipByUserIDRow
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.StoreName,
		&i.StoreSlug,
	)
	return i, err
}

const getStoreMembers = `-- name: GetStoreMembers :many
SELECT
  m.id,
  m.store_id,
  m.user_id,
  m.role,
  m.status,
  m.invited_by,
  m.invited_at,
  m.created_at,
  m.updated_at,
  u.clerk_id,
  u.email,
  u.name,
  u.avatar_url
FROM memberships m
JOIN users u ON u.id = m.user_id
WHERE m.store_id = $1
ORDER BY
  CASE m.role WHEN 'owner' THEN 0 WHEN 'admin' THEN 1 ELSE 2 END,
  m.created_at ASC
`

type GetStoreMembersRow struct {
	ID        pgtype.UUID        `json:"id"`
	StoreID   pgtype.UUID        `json:"store_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Role      string             `json:"role"`
	Status    string             `json:"status"`
	InvitedBy pgtype.UUID        `json:"invited_by"`
	InvitedAt pgtype.Timestamptz `json:"invited_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	ClerkID   string             `json:"clerk_id"`
	Email     string             `json:"email"`
	Name      pgtype.Text        `json:"name"`
	AvatarUrl pgtype.Text        `json:"avatar_url"`
}

// List all members of a store with user info
func (q *Queries) GetStoreMembers(ctx context.Context, storeID pgtype.UUID) ([]GetStoreMembersRow, error) {
	rows, err := q.db.Query(ctx, getStoreMembers, storeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetStoreMembersRow{}
	for rows.Next() {
		var i GetStoreMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.StoreID,
			&i.UserID,
			&i.Role,
			&i.Status,
			&i.InvitedBy,
			&i.InvitedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClerkID,
			&i.Email,
			&i.Name,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByClerkID = `-- name: GetUserByClerkID :one
SELECT id, clerk_id, email, name, avatar_url, created_at, updated_at
FROM users
WHERE clerk_id = $1
`

// Get user by Clerk ID
func (q *Queries) GetUserByClerkID(ctx context.Context, clerkID string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByClerkID, clerkID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ClerkID,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, clerk_id, email, name, avatar_url, created_at, updated_at
FROM users
WHERE email = $1
`

// Get user by email
func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ClerkID,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, clerk_id, email, name, avatar_url, created_at, updated_at
FROM users
WHERE id = $1
`

// Get user by ID
func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ClerkID,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listStoreInvitations = `-- name: ListStoreInvitations :many
SELECT
  si.id,
  si.store_id,
  si.email,
  si.role,
  si.token,
  si.invited_by,
  si.status,
  si.expires_at,
  si.accepted_at,
  si.created_at,
  inviter_user.name as inviter_name
FROM store_invitations si
JOIN memberships inviter ON inviter.id = si.invited_by
JOIN users inviter_user ON inviter_user.id = inviter.user_id
WHERE si.store_id = $1
ORDER BY si.created_at DESC
`

type ListStoreInvitationsRow struct {
	ID          pgtype.UUID        `json:"id"`
	StoreID     pgtype.UUID        `json:"store_id"`
	Email       string             `json:"email"`
	Role        string             `json:"role"`
	Token       string             `json:"token"`
	InvitedBy   pgtype.UUID        `json:"invited_by"`
	Status      string             `json:"status"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	AcceptedAt  pgtype.Timestamptz `json:"accepted_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	InviterName pgtype.Text        `json:"inviter_name"`
}

func (q *Queries) ListStoreInvitations(ctx context.Context, storeID pgtype.UUID) ([]ListStoreInvitationsRow, error) {
	rows, err := q.db.Query(ctx, listStoreInvitations, storeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStoreInvitationsRow{}
	for rows.Next() {
		var i ListStoreInvitationsRow
		if err := rows.Scan(
			&i.ID,
			&i.StoreID,
			&i.Email,
			&i.Role,
			&i.Token,
			&i.InvitedBy,
			&i.Status,
			&i.ExpiresAt,
			&i.AcceptedAt,
			&i.CreatedAt,
			&i.InviterName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeInvitation = `-- name: RevokeInvitation :exec
UPDATE store_invitations
SET status = 'revoked'
WHERE store_id = $1 AND id = $2 AND status = 'pending'
`

type RevokeInvitationParams struct {
	StoreID pgtype.UUID `json:"store_id"`
	ID      pgtype.UUID `json:"id"`
}

func (q *Queries) RevokeInvitation(ctx context.Context, arg RevokeInvitationParams) error {
	_, err := q.db.Exec(ctx, revokeInvitation, arg.StoreID, arg.ID)
	return err
}

const updateMembershipRole = `-- name: UpdateMembershipRole :one
UPDATE memberships
SET role = $3, updated_at = now()
WHERE store_id = $1 AND id = $2
RETURNING id, store_id, user_id, role, status, created_at, updated_at
`

type UpdateMembershipRoleParams struct {
	StoreID pgtype.UUID `json:"store_id"`
	ID      pgtype.UUID `json:"id"`
	Role    string      `json:"role"`
}

type UpdateMembershipRoleRow struct {
	ID        pgtype.UUID        `json:"id"`
	StoreID   pgtype.UUID        `json:"store_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Role      string             `json:"role"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateMembershipRole(ctx context.Context, arg UpdateMembershipRoleParams) (UpdateMembershipRoleRow, error) {
	row := q.db.QueryRow(ctx, updateMembershipRole, arg.StoreID, arg.ID, arg.Role)
	var i UpdateMembershipRoleRow
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
  email = $2,
  name = $3,
  avatar_url = $4,
  updated_at = now()
WHERE clerk_id = $1
RETURNING id, clerk_id, email, name, avatar_url, created_at, updated_at
`

type UpdateUserParams struct {
	ClerkID   string      `json:"clerk_id"`
	Email     string      `json:"email"`
	Name      pgtype.Text `json:"name"`
	AvatarUrl pgtype.Text `json:"avatar_url"`
}

// Update user info (from Clerk webhook)
func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ClerkID,
		arg.Email,
		arg.Name,
		arg.AvatarUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ClerkID,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (clerk_id, email, name, avatar_url)
VALUES ($1, $2, $3, $4)
ON CONFLICT (clerk_id) DO UPDATE SET
  email = CASE WHEN $2 = '' THEN users.email ELSE $2 END,
  name = CASE WHEN $3 IS NULL THEN users.name ELSE $3 END,
  avatar_url = CASE WHEN $4 IS NULL THEN users.avatar_url ELSE $4 END,
  updated_at = now()
RETURNING id, clerk_id, email, name, avatar_url, created_at, updated_at
`

type UpsertUserParams struct {
	ClerkID   string      `json:"clerk_id"`
	Email     string      `json:"email"`
	Name      pgtype.Text `json:"name"`
	AvatarUrl pgtype.Text `json:"avatar_url"`
}

// Create or update user (for sync endpoint fallback)
// Only updates email/name/avatar if the new value is not empty
func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUser,
		arg.ClerkID,
		arg.Email,
		arg.Name,
		arg.AvatarUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ClerkID,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const validateStoreAccess = `-- name: ValidateStoreAccess :one
SELECT
  m.id,
  m.role
FROM memberships m
WHERE m.user_id = $1 AND m.store_id = $2 AND m.status = 'active'
`

type ValidateStoreAccessParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	StoreID pgtype.UUID `json:"store_id"`
}

type ValidateStoreAccessRow struct {
	ID   pgtype.UUID `json:"id"`
	Role string      `json:"role"`
}

// Check if user has access to a store and return their membership info
func (q *Queries) ValidateStoreAccess(ctx context.Context, arg ValidateStoreAccessParams) (ValidateStoreAccessRow, error) {
	row := q.db.QueryRow(ctx, validateStoreAccess, arg.UserID, arg.StoreID)
	var i ValidateStoreAccessRow
	err := row.Scan(&i.ID, &i.Role)
	return i, err
}

const validateStoreAccessByClerkID = `-- name: ValidateStoreAccessByClerkID :one
SELECT
  m.id,
  m.role,
  u.id as user_id
FROM memberships m
JOIN users u ON u.id = m.user_id
WHERE u.clerk_id = $1 AND m.store_id = $2 AND m.status = 'active'
`

type ValidateStoreAccessByClerkIDParams struct {
	ClerkID string      `json:"clerk_id"`
	StoreID pgtype.UUID `json:"store_id"`
}

type ValidateStoreAccessByClerkIDRow struct {
	ID     pgtype.UUID `json:"id"`
	Role   string      `json:"role"`
	UserID pgtype.UUID `json:"user_id"`
}

// Check if user has access to a store using Clerk ID (for middleware)
func (q *Queries) ValidateStoreAccessByClerkID(ctx context.Context, arg ValidateStoreAccessByClerkIDParams) (ValidateStoreAccessByClerkIDRow, error) {
	row := q.db.QueryRow(ctx, validateStoreAccessByClerkID, arg.ClerkID, arg.StoreID)
	var i ValidateStoreAccessByClerkIDRow
	err := row.Scan(&i.ID, &i.Role, &i.UserID)
	return i, err
}
